### ISSUE TITLE
omiagent host sometimes throws a strand assertion in the binary transport causing process to die

### ISSUE THREAD

**Issue by paulcallen** [Microsoft/omi#109]

**Comment by JumpingYang001** [comment]
Do we have repro steps or some information for this? thanks.

**Comment by paulcallen** [comment]
no reliable repro on this yet. But it happens enough to require an issue to track it. I have not seen a core for this yet to be able to track it down more.

**Comment by sarojcare** [comment]
Close the case as no repro.
