### ISSUE TITLE
Header files (mi.h, etc) are copied during configure, leading to potential errors

### ISSUE THREAD

**Issue by jeffaco** [Microsoft/omi#110]
The configure script copies some base header files and changes them based on the build configuration.

This is often problematic in that, after doing a rebase operation, builds may start to fail until configure is rerun. This is not something that developers expect, wasting a potentially large amount of time.

Can this be resolved such that builds are more stable without requiring configure to modify base files?

**Comment by sarojcare** [comment]
Case need to be closed as low priority.
