### ISSUE TITLE
On HP, CIM_Error Rtti tests fail consistently

### ISSUE THREAD

**Issue by palladia** [Microsoft/omi#177]
on hp_v3_ia64, libtest_wsman.so:TestWSMAN_GetClass_CIM_Error_StandardRtti and libtest_wsman.so:TestWSMAN_GetClass_CIM_Error_StandardRtti_OOP tests fail consistently.

This is the actual response from server:

<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://www.w3.org/2003/05/soap-envelope" xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:wsen="http://schemas.xmlsoap.org/ws/2004/09/enumeration" xmlns:e="http://schemas.xmlsoap.org/ws/2004/08/eventing" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:wsmb="http://schemas.dmtf.org/wbem/wsman/1/cimbinding.xsd" xmlns:wsman="http://schemas.dmtf.org/wbem/wsman/1/wsman.xsd" xmlns:wxf="http://schemas.xmlsoap.org/ws/2004/09/transfer" xmlns:cim="http://schemas.dmtf.org/wbem/wscim/1/common" xmlns:msftwinrm="http://schemas.microsoft.com/wbem/wsman/1/wsman.xsd" xmlns:wsmid="http://schemas.dmtf.org/wbem/wsman/identity/1/wsmanidentity.xsd">
<SOAP-ENV:Header>
<wsa:To>
http://schemas.xmlsoap.org/ws/2004/08/addressing/role/anonymous
</wsa:To>
<wsa:Action>
http://schemas.xmlsoap.org/ws/2004/09/transfer/GetResponse
</wsa:Action>
<wsa:MessageID>uuid:2D9060DE-4533-0005-0000-000000010000</wsa:MessageID>
<wsa:RelatesTo>uuid:DFCFFC30-89CA-4C3F-8E8C-4DA843C58615</wsa:RelatesTo>
</SOAP-ENV:Header>
<SOAP-ENV:Body>
<CLASS NAME="CIM_Error" DERIVATION="">
<QUALIFIER NAME="Version" TYPE="string" TOSUBCLASS="false" TRANSLATABLE="true">
<VALUE>2.22.1</VALUE>
</QUALIFIER>
<QUALIFIER NAME="UMLPackagePath" TYPE="string">
<VALUE>CIM::Interop</VALUE>
</QUALIFIER>
<QUALIFIER NAME="indication" TYPE="boolean">
<VALUE>true</VALUE>
</QUALIFIER>
<PROPERTY NAME="ErrorType" TYPE="uint16" CLASSORIGIN="CIM_Error"/>
<PROPERTY NAME="OtherErrorType" TYPE="string" CLASSORIGIN="CIM_Error"/>
<PROPERTY NAME="OwningEntity" TYPE="string" CLASSORIGIN="CIM_Error"/>
<PROPERTY NAME="MessageID" TYPE="string" CLASSORIGIN="CIM_Error">
<QUALIFIER NAME="required" TYPE="boolean">
<VALUE>true</VALUE>
</QUALIFIER>
</PROPERTY>
<PROPERTY NAME="Message" TYPE="string" CLASSORIGIN="CIM_Error"/>
<PROPERTY.ARRAY NAME="MessageArguments" TYPE="string" CLASSORIGIN="CIM_Error"/>
<PROPERTY NAME="PerceivedSeverity" TYPE="uint16" CLASSORIGIN="CIM_Error"/>
<PROPERTY NAME="ProbableCause" TYPE="uint16" CLASSORIGIN="CIM_Error"/>
<PROPERTY NAME="ProbableCauseDescription" TYPE="string" CLASSORIGIN="CIM_Error"/>
<PROPERTY.ARRAY NAME="RecommendedActions" TYPE="string" CLASSORIGIN="CIM_Error"/>
<PROPERTY NAME="ErrorSource" TYPE="string" CLASSORIGIN="CIM_Error"/>
<PROPERTY NAME="ErrorSourceFormat" TYPE="uint16" CLASSORIGIN="CIM_Error">
<VALUE>0</VALUE>
</PROPERTY>
<PROPERTY NAME="OtherErrorSourceFormat" TYPE="string" CLASSORIGIN="CIM_Error"/>
<PROPERTY NAME="CIMStatusCode" TYPE="uint32" CLASSORIGIN="CIM_Error"/>
<PROPERTY NAME="CIMStatusCodeDescription" TYPE="string" CLASSORIGIN="CIM_Error"/>
</CLASS>
</SOAP-ENV:Body>
</SOAP-ENV:Envelope>

**Comment by yakman2020** [comment]
I deactivated these tests for now, pending debugging

**Comment by sarojcare** [comment]
George will close the case.
