### ISSUE TITLE
Needs to be public

### ISSUE THREAD

**Issue by andschwa** [Microsoft/omi#24]
Tracking here so the issue doesn't get lost.

@agup006 Last I heard this was being discussed with legal. Has there been any movement?

While OMI is "open-source" the only release is through The Open Group, and so our real repository is private.

This causes a lot of pain with our other internal project which takes a dependency on OMI, as every user needs to get authenticated in both GitHub organizations.

**Comment by agup006** [comment]
This can finally be closed :)
