### ISSUE TITLE
NTLM cred error messages need to be more specific

### ISSUE THREAD

**Issue by yakman2020** [Microsoft/omi#244]
The CIError produced in httpclientauth.c and httpauth.c when the credential file is not the correct permissions, or missing should  be in the form:

    "The permissions of the file /Users/the_user/.omi/ntlmcred are 10755. The permissions must be 600"

In other words, include the specific file, and the specific action required.

**Comment by sarojcare** [comment]
It is nice to have but it is low priority. George will close the case.
