### ISSUE TITLE
allowed omi authentication needs to be different on http and https

### ISSUE THREAD

**Issue by yakman2020** [Microsoft/omi#247]
Since basic auth is insecure on http, there should be a control to disallow it on http, but allow on https. 
Currently if we enable the http socket there is no way to control this.

**Comment by paulcallen** [comment]
Configuration for client and server
- Enable/disable Basic, SPNEGO, Kerberos authentication (all enabled by default)
- Allow unencrypted (disabled by default)

With Allow-unencrypted option being available we can configure omiserver to listen on HTTP and HTTPS by default as part of instalation

**Comment by yakman2020** [comment]
There is a prototype implementation in the branch brcampbe/cryptctl. 

It does server side only. 

To complete it will be necessary to 
- add the same config file keys to the client file.
- create regression tests. 
- The client should check the encryption control value in HttpClient_StartRequestV2 with the other bits of  configuration. 
- The server needs to vary the 401 response ("http 1.1/401 \nBasic\nSpengo\nKerberos\n" should only return the authentication options that are allowed on the server, so if Basic was turned off on http, it should only offer Negotiate and  Kerberos.

- There is a bit more work to do on the server side to terminate the command when the unauthorized non-encrypted traffic occurs.  Simply sending the 401 response back is a start, but not enough to completely close the connection.
