### ISSUE TITLE
Add kerberos authentication

### ISSUE THREAD

**Issue by paulcallen** [Microsoft/omi#249]
- Add as authentication option for SPNEGO
- Add as a top-level authentication option, such that it is interoperable with Windows WinRM

**Comment by yakman2020** [comment]
Adding kerberos authentication for linux as of 10 May 2017.  Currently we are kerberizing our test environment and checking what combinations of server and client are working together.  We know the unit tests are working in redhat/centos 7.3 and ubuntu 16.04. We are configuring other machines for test and will keep folks posted as we verify different environments. 

We will also be adding some documentation of how we are setting up our kerberised environment.

**Comment by yakman2020** [comment]
We have gotten red hat 6 and 7 and ubuntu 14.04 and 16.04 on both intel/amd and power, and macOS into our unit tests, and tried end to end combinations locally. We are working to get kerberos into the end to end testing now. Currently, linux to linux appears authentication and encryption seem to work fine. 

Windows to linux authentication also appears to be working. 

Linux to windows authentication is running into a problem with authorization. We are debugging that now.  

Windows to MacOS isn't a supported configuration, but it has been tried and there is a problem with  key format compatibility. which could be a setup issue. MacOS to linux and linux to mac authentication appears to be working, but we have not tried encryption yet.

**Comment by yakman2020** [comment]
A bit more debugging of the setup reveals that linux->windows works. We can now say we have authentication:
 -  linux->linux
 - win->linux
 - linux->win

we have encryption linux->linux and win->linux.  Still working on linux->win.

**Comment by abhi1202** [comment]
@yakman2020  thanks for giving this information. Are you saying that now OMI is inter-operable with Windows Management Framework (WinRM) using kerberos ? I have been using basic authentication till now which works fine with https transport.

**Comment by yakman2020** [comment]
Yes.

**Comment by yakman2020** [comment]
Kerberos authentication should be working now linux to win, win to linux and linux to linux. We are finalizing kerberos based encryption using gss over http as of the next pull request. 

Mac to linux or windows is in progress. We are not sure whether it will be working by the next release, but we expect it soon.

**Comment by yakman2020** [comment]
mac kerberos authentication is now getting ready for a pr and we expect to be in master in a fee days. Encryption over http will be up next.

**Comment by yakman2020** [comment]
Encryption over http for mac and linux is pushed into master.
