### ISSUE TITLE
we need to make the existence of the config file optional as it may not exist on all platforms

### ISSUE THREAD

**Issue by JumpingYang001** [Microsoft/omi#252]
For  omicli and powershell, we need to add /etc/opt/omi/conf/omicli.conf (I just find this in recent changes), and then it works fine.
If we don't have the conf file, omicli will get nothing when remoting to others.
I found this on Mac, but we may need it optional on all platforms as Paul said.

**Comment by paulcallen** [comment]
this will be an issue if you install powershell and not OMI.

**Comment by palladia** [comment]
Fixed by #255
