### ISSUE TITLE
another windows error that is not decoded well

### ISSUE THREAD

**Issue by paulcallen** [Microsoft/omi#254]
did this:
`./omicli --hostname <windows-box>  -u <user> -p <password>  --auth Basic  --encryption none gi root/cimv2 { Win32_Process Handle 1 }`
`./omicli: result: MI_RESULT_FAILED`
`./omicli: result: Internal error parsing Wsman fault message`

Process ID 1 on this windows box does not exist. Should have resulted in MI_RESULT_NOT_FOUND with the appropriate extracted string from the packet.

<s:Envelope xml:lang="en-US" xmlns:s="http://www.w3.org/2003/05/soap-envelope" xmlns:a="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:x="http://schemas.xmlsoap.org/ws/2004/09/transfer" xmlns:e="http://schemas.xmlsoap.org/ws/2004/08/eventing" xmlns:n="http://schemas.xmlsoap.org/ws/2004/09/enumeration" xmlns:w="http://schemas.dmtf.org/wbem/wsman/1/wsman.xsd" xmlns:p="http://schemas.microsoft.com/wbem/wsman/1/wsman.xsd"><s:Header><a:Action>http://schemas.xmlsoap.org/ws/2004/08/addressing/fault</a:Action><a:MessageID>uuid:3679CAE4-326C-485F-9BC9-033FE51D4CEE</a:MessageID><a:To>http://schemas.xmlsoap.org/ws/2004/08/addressing/role/anonymous</a:To><a:RelatesTo>uuid:6E063D19-4AF3-0005-0000-000000010000</a:RelatesTo></s:Header><s:Body><s:Fault><s:Code><s:Value>s:Sender</s:Value><s:Subcode><s:Value>a:DestinationUnreachable</s:Value></s:Subcode></s:Code><s:Reason><s:Text xml:lang="en-US">The WS-Management service cannot process the request. The service cannot find the resource identified by the resource URI and selectors. </s:Text></s:Reason><s:Detail><w:FaultDetail>http://schemas.dmtf.org/wbem/wsman/1/wsman/faultDetail/InvalidResourceURI</w:FaultDetail><f:WSManFault xmlns:f="http://schemas.microsoft.com/wbem/wsman/1/wsmanfault" Code="2150858752" Machine="1.2.3.4"><f:Message><f:ProviderFault provider="WMI Provider" path="C:\Windows\system32\WsmWmiPl.dll"><f:WSManFault xmlns:f="http://schemas.microsoft.com/wbem/wsman/1/wsmanfault" Code="2150858752" Machine="paulall4.redmond.corp.microsoft.com"><f:Message>The WS-Management service cannot process the request. The service cannot find the resource identified by the resource URI and selectors. </f:Message></f:WSManFault><f:ExtendedError><p:__ExtendedStatus xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:p="http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/__ExtendedStatus" xmlns:cim="http://schemas.dmtf.org/wbem/wscim/1/common" xsi:type="p:__ExtendedStatus_Type"><p:Description xsi:nil="true" xsi:type="cim:cimString"/><p:Operation xsi:type="cim:cimString">GetObject</p:Operation><p:ParameterInfo xsi:type="cim:cimString">Win32_Process.Handle=&quot;2&quot;</p:ParameterInfo><p:ProviderName xsi:type="cim:cimString">CIMWin32</p:ProviderName><p:StatusCode xsi:nil="true" xsi:type="cim:cimUnsignedInt"/></p:__ExtendedStatus></f:ExtendedError></f:ProviderFault></f:Message></f:WSManFault></s:Detail></s:Fault></s:Body></s:Envelope>

**Comment by JumpingYang001** [comment]
From omiclient-recv.trc, it shows there are 2 "<s:Envelope..." nodes in response, and the first node is truncated.

<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://www.w3.org/2003/05/soap-envelope" xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:wsen="http://schemas.xmlsoap.org/ws/2004/09/enumeration" xmlns:e="http://schemas.xmlsoap.org/ws/2004/08/eventing" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:wsmb="http://schemas.dmtf.org/wbem/wsman/1/cimbinding.xsd" xmlns:wsman="http://schemas.dmtf.org/wbem/wsman/1/wsman.xsd" xmlns:wxf="http://schemas.xmlsoap.org/ws/2004/09/transfer" xmlns:cim="http://schemas.dmtf.org/wbem/wscim/1/common" xmlns:msftwinrm="http://schemas.microsoft.com/wbem/wsman/1/wsman.xsd" xmlns:wsmid="http://schemas.dmtf.org/wbem/wsman/identity/1/wsmanidentity.xsd"><SOAP-ENV:Header><wsa:To>http://schemas.xmlsoap.org/ws/2004/08/addressing/role/anonymous</wsa:To><wsa:Action>http://schemas.xmlsoap.org/ws/2004/09/enumeration/EnumerateResponse</wsa:Action><wsa:MessageID>uuid:CBE0ACF1-45F5-0005-0000-000000010000</wsa:MessageID><wsa:RelatesTo>uuid:CBDF488D-45F5-0005-0000-000000010000</wsa:RelatesTo></SOAP-ENV:Header><SOAP-ENV:Body><wsen:EnumerateResponse><wsen:EnumerationContext>1164378112</wsen:EnumerationContext><wsman:Items><p:OMI_Identify xmlns:p="http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/OMI_Identify"><p:InstanceID>2FDB5542-5896-45D5-9BE9-DC04430AAABE</p:InstanceID><p:SystemName>psl64-cent7-02</p:SystemName><p:ProductName>OMI</p:ProductName><p:ProductVendor>Microsoft</p:ProductVendor><p:ProductVersionMajor>1</p:ProductVersionMajor><p:ProductVersionMinor>1</p:ProductVersionMinor><p:ProductVersionRevision>0</p:ProductVersionRevision><p:ProductVersionString>1.1.0-63</p:ProductVersionString><p:Platform>LINUX_X86_64_GNU</p:Platform><p:OperatingSystem>LINUX</p:OperatingSystem><p:Architecture>X86_64</p:Architecture><p:Compiler>GNU</p:Compiler><p:ConfigPrefix>GNU</p:ConfigPrefix><p:ConfigLibDir>/opt/omi/lib</p:ConfigLibDir><p:ConfigBinDir>/opt/omi/bin</p:ConfigBinDir><p:ConfigIncludeDir>/opt/omi/include</p:ConfigIncludeDir><p:ConfigDataDir>/opt/omi/share</p:ConfigDataDir><p:ConfigLocalStateDir>/var/opt/omi</p:ConfigLocalStateDir><p:ConfigSysConfDir>/etc/opt/omi/conf</p:ConfigSysConfDir><p:ConfigProviderDir>/etc/opt/omi/conf</p:ConfigProviderDir><p:ConfigLogFile>/var/opt/omi/log/omiserver.log</p:ConfigLogFile><p:ConfigPIDFile>/var/opt/omi/run/omiserver.pid</p:ConfigPIDFile><p:ConfigRegisterDir>/etc/opt/omi/conf/omiregister</p:ConfigRegisterDir><p:ConfigSchemaDir>/opt/omi/share/omischema</p:ConfigSchemaDir><p:ConfigNameSpaces>root-omi</p:ConfigNameSpaces><p:ConfigNameSpaces>interop</p:ConfigNameSpaces></p:OMI_Identify></wsman:Items><wsman:EndOfSequence/></wsen:EnumerateResponse></SOAP-ENV:Body></SOAP-ENV:Envelope>
HTTP/1.1 500 
Content-Type: application/soap+xml;charset=UTF-8
Server: Microsoft-HTTPAPI/2.0
Date: Fri, 31 Mar 2017 06:39:02 GMT
Content-Length: 2408

**<s:Envelope xml:lang="en-US" xmlns:s="http://www.w3.org/2003/05/soap-envelope"** xmlns:a="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:x="http://schemas.xmlsoap.org/ws/2004/09/transfer" xmlns:e="http://schemas.xmlsoap.org/ws/2004/08/eventing" xmlns:n="http://schemas.xmlsoap.org/ws/2004/09/enumeration" xmlns:w="http://schemas.dmtf.org/wbem/wsman/1/wsman.xsd" xmlns:p="http://schemas.microsoft.com/wbem/wsman/1/wsman.xsd"><s:Header><a:Action>http://schemas.xmlsoap.org/ws/2004/08/addressing/fault</a:Action><a:MessageID>uuid:E91DABF1-3E6F-45A4-B066-87C99EE89BB2</a:MessageID><a:To>http://schemas.xmlsoap.org/ws/2004/08/addressing/role/anonymous</a:To><a:RelatesTo>uuid:10AAB9F5-4C01-0005-0000-000000010000</a:RelatesTo></s:Header><s:Body><s:Fault><s:Code><s:Value>s:Sender</s:Value><s:Subcode><s:Value>a:DestinationUnreachable</s:Value></s:Subcode></s:Code><s:Reason><s:Text xml:lang="en-US">The WS-Management service cannot process the request. The service cannot find the resource identified by the resource URI and selectors. </s:Text></s:Reason><s:Detail><w:FaultDetail>http://schemas.dmtf.org/wbem/wsman/1/wsman/faultDetail/InvalidResourceURI</w:FaultDetail><f:WSManFault xmlns:f="http://schemas.microsoft.com/wbem/wsman/1/wsmanfault" Code="2150858752" Machine="10.68.240.26"><f:Message><f:ProviderFault provider="WMI Provider" path="C:\Windows\system32\WsmWmiPl.dll"><f:WSManFault xmlns:f="http://schemas.microsoft.com/wbem/wsman/1/wsmanfault" Code="2150858752" Machine="VMMUR-W12R2-02.SCX.com"><f:Message>The WS-Management service cannot process the request. The service cannot find the resource identified by the resource URI and selectors. </f:Message></f:WSManFault><f:ExtendedError><p:__ExtendedStatus xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:p="http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/__ExtendedStatus" xmlns:cim="http://schemas.dmtf.org/wbe


**<s:Envelope xml:lang="en-US" xmlns:s="http://www.w3.org/2003/05/soap-envelope"** xmlns:a="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:x="http://schemas.xmlsoap.org/ws/2004/09/transfer" xmlns:e="http://schemas.xmlsoap.org/ws/2004/08/eventing" xmlns:n="http://schemas.xmlsoap.org/ws/2004/09/enumeration" xmlns:w="http://schemas.dmtf.org/wbem/wsman/1/wsman.xsd" xmlns:p="http://schemas.microsoft.com/wbem/wsman/1/wsman.xsd"><s:Header><a:Action>http://schemas.xmlsoap.org/ws/2004/08/addressing/fault</a:Action><a:MessageID>uuid:E91DABF1-3E6F-45A4-B066-87C99EE89BB2</a:MessageID><a:To>http://schemas.xmlsoap.org/ws/2004/08/addressing/role/anonymous</a:To><a:RelatesTo>uuid:10AAB9F5-4C01-0005-0000-000000010000</a:RelatesTo></s:Header><s:Body><s:Fault><s:Code><s:Value>s:Sender</s:Value><s:Subcode><s:Value>a:DestinationUnreachable</s:Value></s:Subcode></s:Code><s:Reason><s:Text xml:lang="en-US">The WS-Management service cannot process the request. The service cannot find the resource identified by the resource URI and selectors. </s:Text></s:Reason><s:Detail><w:FaultDetail>http://schemas.dmtf.org/wbem/wsman/1/wsman/faultDetail/InvalidResourceURI</w:FaultDetail><f:WSManFault xmlns:f="http://schemas.microsoft.com/wbem/wsman/1/wsmanfault" Code="2150858752" Machine="10.68.240.26"><f:Message><f:ProviderFault provider="WMI Provider" path="C:\Windows\system32\WsmWmiPl.dll"><f:WSManFault xmlns:f="http://schemas.microsoft.com/wbem/wsman/1/wsmanfault" Code="2150858752" Machine="VMMUR-W12R2-02.SCX.com"><f:Message>The WS-Management service cannot process the request. The service cannot find the resource identified by the resource URI and selectors. </f:Message></f:WSManFault><f:ExtendedError><p:__ExtendedStatus xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:p="http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/__ExtendedStatus" xmlns:cim="http://schemas.dmtf.org/wbem/wscim/1/common" xsi:type="p:__ExtendedStatus_Type"><p:Description xsi:nil="true" xsi:type="cim:cimString"/><p:Operation xsi:type="cim:cimString">GetObject</p:Operation><p:ParameterInfo xsi:type="cim:cimString">Win32_Process.Handle=&quot;1&quot;</p:ParameterInfo><p:ProviderName xsi:type="cim:cimString">CIMWin32</p:ProviderName><p:StatusCode xsi:nil="true" xsi:type="cim:cimUnsignedInt"/></p:__ExtendedStatus></f:ExtendedError></f:ProviderFault></f:Message></f:WSManFault></s:Detail></s:Fault></s:Body></s:Envelope>

**Comment by JumpingYang001** [comment]
I debug into the code, and see it go to https://github.com/Microsoft/omi/blob/bf678c710e44be84119432963f74f8ebb3964145/Unix/wsman/wsmanclient.c#L537

**Comment by JumpingYang001** [comment]
I print below message in wsmanclient.c#L537 as below:
```
if ((WS_ParseFaultBody(xml, &fault) != 0) ||
            xml->status)
        {
			fprintf(stderr, "WS_ParseFaultBody text %s\n",xml->text);
			fprintf(stderr, "WS_ParseFaultBody ptr %s\n",xml->ptr);
			fprintf(stderr, "WS_ParseFaultBody status %d\n",xml->status);
			fprintf(stderr, "WS_ParseFaultBody message %s\n",xml->message);
			fprintf(stderr, "WS_ParseFaultBody stack %s\n",xml->stack->data);
			fprintf(stderr, "WS_ParseFaultBody nameSpaces %s\n",xml->nameSpaces->name);
			fprintf(stderr, "WS_ParseFaultBody registeredNameSpaces %s\n",xml->registeredNameSpaces->uri);
			fprintf(stderr, "WS_ParseFaultBody\n");
            goto error;
        }

```

Output:

```
WS_ParseFaultBody text <s
WS_ParseFaultBody ptr </f:WSManFault><f:ExtendedError><p:__ExtendedStatus xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:p="http://schemas.dmtf.org/wbem/wscim/1/cim-schema/2/__ExtendedStatus" xmlns:cim="http://schemas.dmtf.org/wbem/wscim/1/common" xsi:type="p:__ExtendedStatus_Type"><p:Description xsi:nil="true" xsi:type="cim:cimString"/><p:Operation xsi:type="cim:cimString">GetObject</p:Operation><p:ParameterInfo xsi:type="cim:cimString">Win32_Process.Handle=&quot;1&quot;</p:ParameterInfo><p:ProviderName xsi:type="cim:cimString">CIMWin32</p:ProviderName><p:StatusCode xsi:nil="true" xsi:type="cim:cimUnsignedInt"/></p:__ExtendedStatus></f:ExtendedError></f:ProviderFault></f:Message></f:WSManFault></s:Detail></s:Fault></s:Body></s:Envelope>
WS_ParseFaultBody status -1
WS_ParseFaultBody message Failed to parse XML. The element name ProviderFault end tag was expected but Message was found instead.
WS_ParseFaultBody stack Envelope
WS_ParseFaultBody nameSpaces s
WS_ParseFaultBody registeredNameSpaces http://www.w3.org/2003/05/soap-envelope
WS_ParseFaultBody
output/bin/omicli: result: MI_RESULT_FAILED
output/bin/omicli: result: Internal error parsing Wsman fault message
```

**Comment by JumpingYang001** [comment]
The root cause is the response body contains <f:Message> in <f:Message>, I will fix it.

**Comment by JumpingYang001** [comment]
I fixed this issue on  https://github.com/Microsoft/omi/commit/5eb96067054261d067ec30b4f9f82c5274af3dc6

And below is what I get from command:
```
root@psl64-cent7-02  # output/bin/omicli --hostname 10.68.240.26 -u administrator -p *** --auth Basic --encryption none gi root/cimv2 { Win32_Process Handle 1 }
output/bin/omicli: result: MI_RESULT_FAILED
output/bin/omicli: result: ERROR_WSMAN_DESTINATION_UNREACHABLE: The WS-Management service cannot process the request. The service cannot find the resource identified by the resource URI and selectors. 
```

Any other need to change?  MI_RESULT_FAILED should change to MI_RESULT_NOT_FOUND?
