### ISSUE TITLE
typo in omicli usage: "extrinisic" should be "extrinsic"

### ISSUE THREAD

**Issue by Wayenyin** [Microsoft/omi#264]
run omicli --help
Usage: /opt/omi/bin/omicli [OPTIONS] COMMAND ...
...
iv NAMESPACE INSTANCENAME METHODNAME PARAMETERS
        Peform a CIM extrinisic method [i]nvocation operation.
...

Actual: extrinisic 
Expect: extrinsic

**Comment by JumpingYang001** [comment]
I have fixed it in #265 , you can close it now.

**Comment by Wayenyin** [comment]
I have checked this typo and it work fine now.

Repo Steps:
  1. Successfully install OMI (version 1.2.0-63);
  2. Run command: /opt/omi/bin/omicli --help
      Usage: /opt/omi/bin/omicli [OPTIONS] COMMAND ...
       ...
      iv NAMESPACE INSTANCENAME METHODNAME PARAMETERS
          Peform a CIM extrinsic method [i]nvocation operation.
       ...
