### ISSUE TITLE
systemctl control scripts don't restart OMI on failure

### ISSUE THREAD

**Issue by jeffaco** [Microsoft/omi#268]
The existing systemctl control scripts for OMI don't restart omiserver on failure. They're missing the restart clause:

```
Restart=on-failure
```

This should be added under the `[Service]` section, tested, and committed assuming it works with no ill effects.

**Comment by LiweiPeng** [comment]
I also recommend to consider the following RestartSec parameter. The default 100ms may not be the best value. For example, if some underlining issues are not resolved, quickly restart won't help.


RestartSec=
Configures the time to sleep before restarting a service (as configured with Restart=). Takes a unit-less value in seconds, or a time span value such as "5min 20s". Defaults to 100ms.

**Comment by paulcallen** [comment]
Lets try out a `RestartSec=5s` as our pid files can be locked and take a moment or so to unlock when a process goes away.

**Comment by JumpingYang001** [comment]
I try below setting for omid.service, and it restart and works after I kill it on CentOS7:
```
root@psl64-cent7-02  # systemctl edit --full omid
  GNU nano 2.3.1 File: ...stemd/system/.#omid.serviceba816db79ed9daa4           

[Unit]
Description=OMI CIM Server
After=network.target

[Service]
Type=forking
Environment="OMI_HOME=/opt/omi"
PIDFile=/var/opt/omi/run/omiserver.pid
ExecStartPre=/opt/omi/bin/support/installssllinks
ExecStart=/opt/omi/bin/omiserver -d
ExecStop=/opt/omi/bin/omiserver -s
ExecReload=/opt/omi/bin/omiserver -r
TimeoutStartSec=5
Restart=on-failure
RestartSec=5s

[Install]
WantedBy=multi-user.target

                               [ Read 18 lines ]
``` 

Restarted after kill:
```
root@psl64-cent7-02  # systemctl status omid
â omid.service - OMI CIM Server
   Loaded: loaded (/etc/systemd/system/omid.service; enabled; vendor preset: disabled)
   Active: active (running) since Thu 2017-03-30 22:41:01 PDT; 33s ago
 Main PID: 48717 (omiserver)
   CGroup: /system.slice/omid.service
           ââ48717 /opt/omi/bin/omiserver -d

Mar 30 22:41:01 psl64-cent7-02 systemd[1]: Starting OMI CIM Server...
Mar 30 22:41:01 psl64-cent7-02 systemd[1]: PID file /var/opt/omi/run/omiserv....
Mar 30 22:41:01 psl64-cent7-02 systemd[1]: Started OMI CIM Server.
Hint: Some lines were ellipsized, use -l to show in full.

~
root@psl64-cent7-02  # systemctl status omid
â omid.service - OMI CIM Server
   Loaded: loaded (/etc/systemd/system/omid.service; enabled; vendor preset: disabled)
   Active: activating (auto-restart) (Result: signal) since Thu 2017-03-30 22:41:54 PDT; 3s ago
  Process: 48801 ExecStop=/opt/omi/bin/omiserver -s (code=exited, status=0/SUCCESS)
 Main PID: 48717 (code=killed, signal=KILL)

Mar 30 22:41:54 psl64-cent7-02 systemd[1]: Unit omid.service entered failed ....
Mar 30 22:41:54 psl64-cent7-02 systemd[1]: omid.service failed.
Hint: Some lines were ellipsized, use -l to show in full.

~
root@psl64-cent7-02  # systemctl status omid
â omid.service - OMI CIM Server
   Loaded: loaded (/etc/systemd/system/omid.service; enabled; vendor preset: disabled)
   Active: active (running) since Thu 2017-03-30 22:42:00 PDT; 9s ago
  Process: 48801 ExecStop=/opt/omi/bin/omiserver -s (code=exited, status=0/SUCCESS)
  Process: 48842 ExecStart=/opt/omi/bin/omiserver -d (code=exited, status=0/SUCCESS)
  Process: 48805 ExecStartPre=/opt/omi/bin/support/installssllinks (code=exited, status=0/SUCCESS)
 Main PID: 48846 (omiserver)
   CGroup: /system.slice/omid.service
           ââ48846 /opt/omi/bin/omiserver -d

Mar 30 22:41:59 psl64-cent7-02 systemd[1]: omid.service holdoff time over, s....
Mar 30 22:41:59 psl64-cent7-02 systemd[1]: Starting OMI CIM Server...
Mar 30 22:42:00 psl64-cent7-02 systemd[1]: PID file /var/opt/omi/run/omiserv....
Mar 30 22:42:00 psl64-cent7-02 systemd[1]: Started OMI CIM Server.
Hint: Some lines were ellipsized, use -l to show in full.
```

**Comment by JumpingYang001** [comment]
BTW, I am not sure if need to set "StartLimitIntervalSec=" and "StartLimitBurst="
https://www.freedesktop.org/software/systemd/man/systemd.unit.html#StartLimitIntervalSec=
Default value is 5 times within 10 seconds.

Just pick up this.

**Comment by jeffaco** [comment]
We've seen timing issues where the service controller gets confused because it tells OMI to stop but sometimes, based on activity and speed of the machine, OMI can't stop right away (and keeps it's PID file around until it's coming down).

Due to that, I'd definitely suggest you wait 5 seconds or so before attempting to restart.

We also need to be sure that the service_control script always restarts via the service controller, AND that scxadmin (in [SCXcore](https://github.com/Microsoft/SCXcore)) also restarts via the service controller. If we don't always do that, then we'll definitely have more timing issues/problems down the road. So definitely verify those two things if you choose to pick this up.

**Comment by jeffaco** [comment]
In general, our providers don't have services as such, they rely on OMI. So we're not going to have this issue in other providers, although I'll betcha OMS has a problem with this (both with upstart and systemctl). I'll ping Laura about this so she can enter appropriate issues against OMS.

The only exception I can think of is the [Apache-Provider](https://github.com/Microsoft/Apache-Provider), which actually has a shared memory segment that's shared between the provider and an Apache module. But there, Apache owns it's service, so if it doesn't restart, that's Apache's problem.

**Comment by yakman2020** [comment]
I have started a branch to implement this.

**Comment by yakman2020** [comment]
A fix for this was checked into master, commit  c66ce12
