### ISSUE TITLE
Mac isn't a supported platform

### ISSUE THREAD

**Issue by pcgeek86** [Microsoft/omi#298]
I was checking out the OMI package and noticed that it's not available for Mac, or at least not listed as a supported operating system, and there's not an installation package for it.

Are there plans to support Mac with OMI, or is Linux the primary focus for the time being?

Cheers,
Trevor Sullivan

**Comment by paulcallen** [comment]
@pcgeek86 thanks Trevor for the question. 

Mac OSX platform support comes down to customer needs, and the biggest customers of OMI (system center operations management, etc) don't have a need for an OMI server-side component on OSX. We do ship client bits with PowerShell such that PowerShell can remote using PSRP over WSMAN to Windows, but they come pre-packaged into the PowerShell package itself. For testing purposes we do actually have client and server working, and we have most OMI tests (if not all) running on that platform. We just have not had the time or customer requirements to build out the install infrastructure needed for OSX.

Can you give us some background on what is driving your ask?

Thanks

**Comment by pcgeek86** [comment]
Sure, thanks for the response, Paul. I'm just developing on a Mac, hence the ask. As long as it works on Mac, it doesn't need to be officially supported. I'm also planning on embedding OMI in a Linux Docker container to enable remote debugging of the container.
