### ISSUE TITLE
CI Travis on Linux or Mac OSX looks like not stable and fail occasionally

### ISSUE THREAD

**Issue by JumpingYang001** [Microsoft/omi#309]
Failed on Linux: https://travis-ci.org/Microsoft/omi/jobs/230968205
CI failed in this function: https://github.com/Microsoft/omi/blob/master/Unix/tests/miapi/main.cpp#L5801
```
libtest_miapi.so:Test_MultiThreads_Enumerate/ConsumeInstance_Async...
main.cpp(5850): 
	Compare: successThreadCount == sthreadCount
		LHS: 7
		RHS: 8
		(Some enumerate threads failed)
=== PAL_DumpAllocStats:
usage: 1861
peakUsage: 722608
numAllocs: 17261
numFrees: 17258

WARNING: /home/travis/build/Microsoft/omi/Unix/output1/bin/omiserver: server has unfreed blocks on exit

WARNING: one or more blocks still allocated!
BLOCK: server.c(966): ptr=0x192e600: magic=89ABCDEF id=5 size=61
BLOCK: batch.c(74): ptr=0x192cd30: magic=89ABCDEF id=1 size=776
BLOCK: batch.c(38): ptr=0x192c8f0: magic=89ABCDEF id=0 size=1024


	[Failed]  libtest_miapi.so:Test_MultiThreads_Enumerate/ConsumeInstance_Async	2.73314
```

Failed on Mac: https://travis-ci.org/Microsoft/omi/jobs/230968214
Mac fail due to timeout:
```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received

The build has been terminated
```

**Comment by paulcallen** [comment]
mac failure is generally a CI infrastructure problem and tends to hang in random places.
Not seen that particular test fail like that on Linux though.

**Comment by jeffaco** [comment]
As Paul said, this sort of error is generally a Travis infrastructure issue. In particular, the latest builds of [Travis](https://travis-ci.org/Microsoft/omi/builds/230992099) appears to be successful.

Pending more specific, consistent failures, I'm going to close this issue.

**Comment by paulcallen** [comment]
the mac one was probably infrastructure. The Linux failure was to do with the issue I just merged with main -- a race condition I have never seen before
