### ISSUE TITLE
Error installing OMI could not determine current runlevel

### ISSUE THREAD

**Issue by MaximoTrinidad** [Microsoft/omi#317]
Operating System: Windows 10 Bash (Ubuntu 16.04.2)

Repro:
sudo apt install omi

Error Message: 
"Configuring OMI service ...
invoke-rc.d: could not determine current runlevel"

![omierr_2017-05-26_11-36-25](https://cloud.githubusercontent.com/assets/19892435/26501444/aae11f2c-4207-11e7-89f7-7f0622e88f00.jpg)

**Comment by paulcallen** [comment]
I am guessing this is because of the service installer [here](https://github.com/Microsoft/omi/blob/15d9c277faa32511c9a2ca7ab20efbbaa93c536c/Unix/installbuilder/service_scripts/service_control.linux#L75).
On Bash for Windows we are checking to see if system is running and it is not. We then check if /usr/sbin/invoke-rc.d exists and it does so we try to run it. In reality, on this platform this is present, but does not work, and we should use /sbin/service instead.
Wondering if we should check for /sbin/service before we check for /usr/sbin/invoke-rc.d.
@jeffaco - thoughts?

**Comment by jeffaco** [comment]
@paulcallen The ordering basically went from "most common" to "least common", trying to get through the conditionals as quickly as possible (in terms of performance). I think we could change the order safely (although we'd need a test pass to be certain).

It's odd that something was deployed that didn't work. That's just bad behavior, but that's also something that we'd be unlikely to get changed ...

**Comment by JumpingYang001** [comment]
I meet same error in docker container(image is docker pull ubuntu:16.04):
```
root@7f7c309bbc4b:/# dpkg -i omi-1.2.0-35.ssl_100.x64.deb 
Selecting previously unselected package omi.
(Reading database ... 11548 files and directories currently installed.)
Preparing to unpack omi-1.2.0-35.ssl_100.x64.deb ...
Creating omiusers group ...
Unpacking omi (1.2.0.35) ...
Setting up omi (1.2.0.35) ...
Generating a 2048 bit RSA private key
.....................+++
.........................................+++
writing new private key to '/etc/opt/omi/ssl/omikey.pem'
-----
Configuring OMI service ...
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of start.
Processing triggers for systemd (229-4ubuntu17)
root@7f7c309bbc4b:/# /usr/sbin/invoke-rc.d omid start
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of start.
root@7f7c309bbc4b:/#
```

To make the error "invoke-rc.d: could not determine current runlevel" disapper just need to run below command:
```
export RUNLEVEL=1
```

after run above  command, I remain 1 error in docker container now:
```
root@7f7c309bbc4b:/# /usr/sbin/invoke-rc.d omid start
invoke-rc.d: policy-rc.d denied execution of start.
root@7f7c309bbc4b:/# 
```

To fix this issue on docker container, there is a workaround:
```
root@7f7c309bbc4b:/# cat /usr/sbin/policy-rc.d
#!/bin/sh
exit 101
root@7f7c309bbc4b:/# sed -i 's/101/0/g' /usr/sbin/policy-rc.d
root@7f7c309bbc4b:/# cat /usr/sbin/policy-rc.d               
#!/bin/sh
exit 0
root@7f7c309bbc4b:/# /usr/sbin/invoke-rc.d omid start        
 * Starting Microsoft OMI Server: 
   ...done.
root@7f7c309bbc4b:/# 
```

**Comment by JumpingYang001** [comment]
@MaximoTrinidad maybe you can try run `export RUNLEVEL=1`, and install again, the error might gone.

**Comment by MaximoTrinidad** [comment]
Hi @JumpingYang001,

I got it going!

So, I tried the following based on the workaround above:
-----------------------
sudo su
  export RUNLEVEL=1
  /usr/sbin/invoke-rc.d omid start
  service omid status  #-> Still shows "not running"
  service omid start
  service omid status #-> Now shows it "is running"
exit
------------------------

Now, I dealing with psl-omi-provider which I'm getting the same "invoke-rc.d run level" error.  
I'm not giving up!
:)

**Comment by JumpingYang001** [comment]
/usr/sbin/invoke-rc.d and /usr/sbin/service are different shell script, and they have some difference on dealting with upstart and systemd.
For the error "invoke-rc.d run level", it throw from the invoke-rc.d script, it get this error when /sbin/runlevel query out is 0 and (/run/systemd/system or systemctl is not exist):
```
root@7f7c309bbc4b:/# cat /usr/sbin/invoke-rc.d
## Queries sysvinit for the current runlevel
if ! RL=`${RUNLEVELHELPER}`; then
    if [ -n "$is_systemd" ] && systemctl is-active --quiet sysinit.target; then
        # under systemd, the [2345] runlevels are only set upon reaching them;
        # if we are past sysinit.target (roughly equivalent to rcS), consider
        # this as runlevel 5 (this is only being used for validating rcN.d
        # symlinks, so the precise value does not matter much)
        RL=5
    else
        printerror "could not determine current runlevel"
        # this usually fails in schroots etc., ignore failure (#823611)
        RL=
    fi
fi
```

BTW, @MaximoTrinidad  do you mean when you are installing psl-omi-provider on Win10 Bash (Ubuntu 16.04.2), and after run `export RUNLEVEL=1` it still get the "invoke-rc.d: could not determine current runlevel" error?

**Comment by JumpingYang001** [comment]
BTW, looks like this error didn't block anythings, and it just continue to work other things:
```
root@7f7c309bbc4b:/# runlevel
unknown
root@7f7c309bbc4b:/# /usr/sbin/invoke-rc.d omid restart
invoke-rc.d: could not determine current runlevel
 * Shutting down Microsoft OMI Server: 
   ...done.
 * Starting Microsoft OMI Server: 
   ...done.
```

**Comment by MaximoTrinidad** [comment]
@JumpingYang001,

Yes! in Windows 10 Bash. At the same time I'm haven't been able to see OMI working on a full Ubuntuy system as there's no errors when installing.  I haven't created an issue yet on that one. 

I'm tight up completing all my VM setup in Azure for an MVP Community event next week in Orlando. So, I'm duplicating all my environments, issues and applying all workarounds to them. 

You got to love technology!
:)

**Comment by MaximoTrinidad** [comment]
In my case... The policy-rc.d doesn't exist in /usr/sbin folder. But, I found the invoke-rc.d file.

So, I tried the following based on the workaround above:
-----------------------
sudo su
  export RUNLEVEL=1
  /usr/sbin/invoke-rc.d omid start
  service omid status  #-> Still shows "not running"
  service omid start
  service omid status #-> Now shows it "is running"
exit
-----------------------

I got it started!

Now, I'm finally becoming savy with Linux but.. What are the steps for creating the NTLM_USER_FILE?  

The instructions are a little very vague for a person who's learning Linux.  
So, I can just want to make sure the following are the steps for "setting up credentials:

1. I need to create the ".omi" folder with "mkdir ~/.omi" at the user level. 
2. Then, I can use gedit to create the file "ntlmcred" with "gedit ~/.omi/ntlmcred"
3. And, add the hostOrIP|user|pwd to the file.

I just need confirmation.

:)

**Comment by JumpingYang001** [comment]
Now we support 2 authentication:Basic and Negotiate.
For basic authentication, you needn't do anything on credential, it will use your host username and password, just make sure you open port 5895 and 5986 which is setted with httpport and httpsport  in /etc/opt/omi/conf/omiserver.conf.
For Negotiate authentication, you need to uncomment "#NtlmCredsFile=/etc/opt/omi/.creds/ntlm" in /etc/opt/omi/conf/omiserver.conf and run below configure for CentOS:
```
mkdir /etc/opt/omi/.creds
echo 'yourdomain:yourusername:yourpassword'>/etc/opt/omi/.creds/ntlm
chmod 700 /etc/opt/omi/.creds
chmod 600 /etc/opt/omi/.creds/ntlm
chown root:root /etc/opt/omi/.creds/ntlm
systemctl restart omid
```
If you use Ubuntu, run below commands:
```
mkdir /etc/opt/omi/.creds
echo 'yourdomain:yourusername:yourpassword'>/etc/opt/omi/.creds/ntlm
chmod 700 /etc/opt/omi/.creds
chmod 700 /etc/opt/omi/.creds/ntlm
chown root:root /etc/opt/omi/.creds/ntlm
service omid restart
```

**Comment by JumpingYang001** [comment]
centos Negotiate reuqirements:
yum -y install epel-release
yum install gssntlmssp.x86_64 -y
yum install krb5-libs -y
ln -s /lib64/libcrypto.so.10 /lib64/libcrypto.so.1.0.0
ln -s /lib64/libssl.so.10 /lib64/libssl.so.1.0.0
firewall-cmd --zone=public --add-port=5986/tcp --permanent
firewall-cmd --zone=public --add-port=5985/tcp --permanent
firewall-cmd --reload

**Comment by JumpingYang001** [comment]
Ubuntu:
```
apt-get install gss-ntlmssp -y
apt-get install libkrb5-dev -y
apt-get install libnss-winbind -y
apt-get install libpam-winbind -y
```
BTW, NTLM_USER_FILE is deprecated now.

**Comment by JumpingYang001** [comment]
BashOnWindows is very different with native Ubuntu OS, it not in VM and not in container, it is like cygwin.
It is just mount C:\ from Windows to /mnt/c in Bash.exe process, so they can use same file system.
I have repro this issue for omi and psl-omi-provider, the only affect is the omid service not started and the "invoke-rc.d: could not determine current runlevel" (even this error will not affect any remain work).
I have cat /usr/sbin/invoke.rc.d>/test.txt as attachment bashonwin.invoke-rc.d.txt, we can cat on native Ubuntu 16.04.02 LTS and check if they have difference using https://www.diffchecker.com/diff
cat invoke.rc.d on bash.exe : [bashonwin.invoke-rc.d.txt](https://github.com/Microsoft/omi/files/1036917/bashonwin.invoke-rc.d.txt)
I cat /etc/os-release on bash.exe, it shows I am running on Ubuntu 16.04.02 LTS (Xenial Xerus).

**Comment by JumpingYang001** [comment]
Looks like ubuntu 16.04 lts and ubuntu 16.04.2 lts are a little different, ubuntu 16.04 lts published on 2016-04-21, ubuntu 16.04.2 lts published on 2017-2-17.
@paulcallen , we officially support ubuntu 16.04 lts or ubuntu 16.04.2 lts?

@MaximoTrinidad , could you cat /etc/os-release on bash.exe? your result might also show "Ubuntu 16.04.02 LTS"?

**Comment by JumpingYang001** [comment]
Our Nebula env is "Ubuntu 16.04 LTS": so we just support 16.04 lts .
```
cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
UBUNTU_CODENAME=xenial
```

**Comment by JumpingYang001** [comment]
I have tried "Ubuntu 16.04.2 LTS": It works fine for installing OMI.
```
root@jumping-03:~# dpkg -i omi-1.2.0-35.ssl_100.x64.deb
Selecting previously unselected package omi.
(Reading database ... 59652 files and directories currently installed.)
Preparing to unpack omi-1.2.0-35.ssl_100.x64.deb ...
Creating omiusers group ...
Unpacking omi (1.2.0.35) ...
Setting up omi (1.2.0.35) ...
Generating a 2048 bit RSA private key
...............................+++
..........................................................+++
writing new private key to '/etc/opt/omi/ssl/omikey.pem'
-----
Configuring OMI service ...
Created symlink from /etc/systemd/system/multi-user.target.wants/omid.service to /lib/systemd/system/omid.service.
Processing triggers for systemd (229-4ubuntu16) ...
Processing triggers for ureadahead (0.100.0-19) ...
root@jumping-03:~# runlevel
N 5
root@jumping-03:~# cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.2 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.2 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
```

**Comment by yakman2020** [comment]
A fix for this was checked into master.  commit  c66ce12
