### ISSUE TITLE
OMI providers can have hard-to-detect leaks and make it difficult to find problem providers

### ISSUE THREAD

**Issue by jeffaco** [Microsoft/omi#322]
Currently, OMI runs all out-of-process providers in a single process per hosting account. For example, if a provider is registered as:

```
HOSTING=@requestor@
```

then all `@requestor` providers will run in the same omiagent process for that requestor.

This is problematic in two ways:

1. Most providers unload by default. As a result, if they have memory leaks, it would be difficult or even impossible for provider authors to be aware of that (unless the provider author specifically checked for that), and

2. In the field, it's impossible to know WHICH provider is problematic. You'd know that the `omiagent` process is growing (or crashing, or whatever), but it's difficult to determine which specific provider is responsible.

I'd like to suggest a new configuration parameter in the `/etc/opt/omi/conf/omiserver.conf` file: `PROVIDERDEBUG`, with values of `true` or `false`, and a default value of `false`. If the value of `PROVIDERDEBUG` is `false` (or isn't specified), then providers behave exactly as they do today.

However, if the value of `PROVIDERDEBUG` is `true`, then two changes are made:

1. All out-of-process providers run in their own `omiagent` process. If you run five separate providers, all running as `@requestor`, then you'd have five separate processes reflecting those providers, and

2. All providers are registered as `NOUNLOAD` by default, even if they don't request that capability.

This allows provider authors to isolate which provider is growing in memory over time (using `lsof` or other methods to determine which `omiagent` process is which, or perhaps looking at the omiserver's log file to get PIDs of launched `omiagent` processes). This also allows provider authors to verify that their provider is not leaking memory over time, even if it allows unloading, without source code changes.

**Comment by palladia** [comment]
A new "agentDebugging" parameter has been added to omiserver.conf to do this.  The NOUNLOAD feature was not done though.
