### ISSUE TITLE
Debian 9(Stretch) has OpenSSL 1.1.0f

### ISSUE THREAD

**Issue by tofkamp** [Microsoft/omi#337]
While installing binary .deb package OMI 1.2.0-35 x64 on Debian 9, I receive the following error:
Error: OpenSSL version '1.1.0f' is not supported. Only OpenSSL versions 0.9.8* and 1.0.* are supported.

**Comment by jeffaco** [comment]
We're looking at this. This will take us some time to resolve.

**Comment by JumpingYang001** [comment]
Jeff fixed this issue in #352, will close this issue once new version release, thanks.

**Comment by monperrus** [comment]
Does it mean that the new release will be done against all OpensSSL versions 0.9, 1.0.*, and 1.1.*? When is it planned? Thanks

**Comment by JumpingYang001** [comment]
New release might be at the end of this month, you can check that time.

**Comment by jeffaco** [comment]
The next release of OMI will support OpenSSL 0.9.8, 1.0.*, and 1.1.*.

Note that certain (but not all) providers need to be updated to support OpenSSL v1.1.* as well. That's separate from the OMI work that I completed.

**Comment by jeffaco** [comment]
The [PSRP Provider](https://github.com/PowerShell/psl-omi-provider) is the only provider where I'm unsure of it's dependency on OpenSSL. I suspect that .NET cares about this, but really @paulcallen would know for sure.

@paulcallen, can you comment?

**Comment by JumpingYang001** [comment]
@monperrus , for https://github.com/PowerShell/psl-omi-provider, this project was transitioned to PowerShell team, so OMI team doesn't own it anymore, thanks.

**Comment by JumpingYang001** [comment]
Fixed in https://github.com/Microsoft/omi/releases/tag/v1.4.0-4, close it.
