### ISSUE TITLE
Centrify and Quest use their own libgssapi

### ISSUE THREAD

**Issue by yakman2020** [Microsoft/omi#345]
Centrify and QAS are used by some customers, and use their own gss library, bypassing the stock one. Currently we dynalink the standard libgssapi_krb5 or libgssapi.so, and that is fixed a compile time. We should create a link in /opt/omi during package install, or if developer via output/var/run so customers can redirect the gss we link with.

This is going to require some testing, so should not be done in 1.3, but maybe 1.4 or 1.5

**Comment by palladia** [comment]
There is no immediate plan to support this.  Closing.
