### ISSUE TITLE
OMI doesn't allow logging to standard output to be redirected to files

### ISSUE THREAD

**Issue by jeffaco** [Microsoft/omi#347]
If I start OMI via the command line and redirect STDOUT/STDERR, I get unexpected behavior. When running under `root`, note this:

```
> /opt/omi/bin/omiserver --loglevel verbose -l > foo 2 >& 1
2017/07/06 15:59:36 [114261,114261] INFO: null(0): EventId=40011 Priority=INFO done with receiving msg(0x1c49b88:15:BinProtocolNotification:0)
2017/07/06 15:59:36 [114261,114261] INFO: null(0): EventId=40011 Priority=INFO done with receiving msg(0x1c38978:4099:EnumerateInstancesReq:2711)
--- Additional messages edited out ---
```

If OMI is run as a non-daemon via the command line, STDOUT/STDERR redirection should be allowed and honored. Otherwise, on the console, it can be difficult to capture and possibly terminal window buffering (causing message loss).

**Comment by sarojcare** [comment]
George will close the case.
