### ISSUE TITLE
Nested omicli command fails because ~/.omi doesn't exist

### ISSUE THREAD

**Issue by palladia** [Microsoft/omi#359]
Jumping reported that:

root@omi-cent7x64-03  # /opt/omi/bin/omicli iv -u test -p 123456 --auth Basic --hostname 10.226.186.163 root/scx { SCX_OperatingSystem } ExecuteShellCommand { command '/opt/omi/bin/omicli iv -u root --auth NegoNoCreds --hostname 10.226.186.163 root/scx { SCX_OperatingSystem } ExecuteShellCommand { command \"ls /root\"  timeout 0 } --port 5986 --encryption https'  timeout 0 } --port 5986 --encryption https
instance of SCX_OperatingSystem_OUTPUT
{
    ReturnValue=FALSE
    ReturnCode=2
    StdOut=instance of OMI_Error
{
    OwningEntity=OMI:CIMOM
    MessageID=OMI:MI_Result:1
    Message=credentials directory ~/.omi cannot be opened
    MessageArguments={}
    PerceivedSeverity=7
    ProbableCause=117
    ProbableCauseDescription=credentials directory ~/.omi cannot be opened
    CIMStatusCode=1
    OMI_Code=1
    OMI_Category=0
    OMI_Type=MI
    OMI_ErrorMessage=A general error occurred, not covered by a more specific error code.
}

    StdErr=/opt/omi/bin/omicli: result: MI_RESULT_ACCESS_DENIED

}

This may be caused by the fact that nested omicli command is run under a login shell, and therefore doesn't have a home directory.  One may be able to avoid this by setting $HOME manually.  Alternatively, we may want to explore possibly using home directory.

**Comment by JumpingYang001** [comment]
Just close this since we didn't find any problem for it.
