### ISSUE TITLE
What happens if omiengine dies unexpectedly

### ISSUE THREAD

**Issue by palladia** [Microsoft/omi#375]
With current implementation of nonroot (to be released as 1.4), if the engine dies unexpectedly, the server will log a FATAL error, and then restart the engine automatically.

From discussions with Jeff, he is of the opinion that the server, upon detection of the dead engine, should just exit and not try to restart the engine.  With this implementation, system service would automatically restart the omi service, and you get a brand new server and engine.  

Paul and I can both see the merits of doing it that way.  But at this point in the delivery process, this discussion is pushed off into a future release.

**Comment by palladia** [comment]
After further discussions, this is what will be changed in following release cycle:

1.  Remove the engine-restart flag.  Server will exit if it detects that the engine has died.
2.  Add detection code in agent to make sure that if the server dies, it kills itself.
3.  Since the selector timeout is 1 second, make sure that the server restart delay is at least 1 second.

**Comment by sbadakhc** [comment]
Hi,

In which file is the restart flag set?

**Comment by palladia** [comment]
Restart flag removed, and new logic implemented with #411
