### ISSUE TITLE
Should installation shells scripts use absolute or relative command paths?

### ISSUE THREAD

**Issue by palladia** [Microsoft/omi#376]
Installation shell scripts in installbuilder/datafiles currently consist of a mix system commands and applications.  Some of these commands are expressed as absolute paths, e.g. /usr/local/bin/openssl, but most are simply relative, relying on the $PATH environment variable to determine its full path.

Should the scripts be changed so that we are consistent? 

Some arguments for absolute paths:
* We have run into issues where other versions of command have been placed earlier in the $PATH
* Not every root has /usr/sbin in its $PATH

Some arguments against absolute paths:
* It's a lot of work to convert all those commands into absolute ones
* There is no standard on where commands must reside
* If a local admin has changed root's $PATH, there must be a good reason, and we should honor it.
* We should strive to write shell commands that use just its basic features, and not rely on a specific version of the command.

**Comment by JumpingYang001** [comment]
Is this issue fixed?

**Comment by palladia** [comment]
There is no resource right now to make this kind of enhancements.
