### ISSUE TITLE
omiserver should use systemd unit files to manage the omi keytab.

### ISSUE THREAD

**Issue by yakman2020** [Microsoft/omi#388]
We are currently using a cron job, that works fine everywhere, but not as efficient as using a systemd unit which is triggered by a change in /etc/krb5.keytab.

**Comment by maxhaase** [comment]
It doesn't "work fine everywhere", it doesn't work on CentOS 7 servers installed on Azure. 

A work-around [to prevent 1440 emails sent to root every day] is to comment this file in crontab:

* * * * * [ \( ! -f /etc/opt/omi/creds/omi.keytab \) -o \( /etc/krb5.keytab -nt /etc/opt/omi/creds/omi.keytab \) ] && /opt/omi/bin/support/ktstrip /etc/krb5.keytab /etc/opt/omi/creds/omi.keytab

But I don't know if that affects the system negatively.

**Comment by palladia** [comment]
Recent releases have fixed several issues that caused crontab to generate email.  

There is currently no resource to replace crontab with something else.  Closing this item.
