### ISSUE TITLE
omicli fails on root/virtualization/v2 WSMan query

### ISSUE THREAD

**Issue by alexpilotti** [Microsoft/omi#398]
Querying classes in root/virtualization/v2 from a remote Windows Server fails:

`omicli --auth Basic -u Administrator -p blahblah  --encryption https  --hostname myhost wql root/virtualization/v2 "select ElementName from Msvm_VirtualSystemSettingData"
`

Error:

> omicli: result: ERROR_INTERNAL_ERROR: The WS-Management service cannot process the request. The resource URI and __cimnamespace selector attempted to use different namespaces. Try removing the __cimnamespace selector or using a DMTF resource URI. If a non-DMTF resource URI is used with a __cimnamespace selector, the namespaces must match. 

Enumerating instances in the same class works.
Enumerating remote resources in root/cimv2 works.

Branch: master
Client OS: ubuntu 16.04
Server OS: Windows Server 2016

**Comment by JumpingYang001** [comment]
Following is what I get from omiclient-send.trc:
```
<s:Envelope xmlns:s="http://www.w3.org/2003/05/soap-envelope" xmlns:a="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:n="http://schemas.xmlsoap.org/ws/2004/09/enumeration" xmlns:w="http://schemas.dmtf.org/wbem/wsman/1/wsman.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema" xmlns:h="http://schemas.microsoft.com/wbem/wsman/1/windows/shell" xmlns:p="http://schemas.microsoft.com/wbem/wsman/1/wsman.xsd" ><s:Header><a:To>HTTP://10.226.213.157:5985/wsman/</a:To><w:ResourceURI s:mustUnderstand="true">http://schemas.microsoft.com/wbem/wsman/1/wmi/root/cimv2/*</w:ResourceURI><a:ReplyTo><a:Address s:mustUnderstand="true">http://schemas.xmlsoap.org/ws/2004/08/addressing/role/anonymous</a:Address></a:ReplyTo><a:Action>http://schemas.xmlsoap.org/ws/2004/09/enumeration/Enumerate</a:Action><w:MaxEnvelopeSize s:mustUnderstand="true">102400</w:MaxEnvelopeSize><a:MessageID>uuid:8EE8FC2E-58A8-0005-0000-000000010000</a:MessageID><w:OperationTimeout>PT1M30S</w:OperationTimeout><w:Locale xml:lang="en-us" s:mustUnderstand="false"/><p:DataLocale xml:lang="en-us" s:mustUnderstand="false"/><w:OptionSet s:mustUnderstand="true"></w:OptionSet><w:SelectorSet><w:Selector Name="__cimnamespace">root/virtualization/v2</w:Selector></w:SelectorSet></s:Header><s:Body><n:Enumerate><w:OptimizeEnumeration/><w:MaxElements>1000</w:MaxElements><w:Filter Dialect="http://schemas.microsoft.com/wbem/wsman/1/WQL">select ElementName from Msvm_VirtualSystemSettingData</w:Filter></n:Enumerate></s:Body></s:Envelope>
```

looks like we don't have option to change ResourceURI node for omicli: `<w:ResourceURI s:mustUnderstand="true">http://schemas.microsoft.com/wbem/wsman/1/wmi/root/cimv2/*</w:ResourceURI>`

**Comment by JumpingYang001** [comment]
If "root/virtualization/v2" doesn't exist on remote Windows, it will also show this error, @alexpilotti  , have you enable Hyper-v on your remote Windows?
check with this PowerShell command to make sure you have this namespace on remote Windows:
```
gwmi -namespace "root\virtualization\v2" Msvm_VirtualSystemSettingData | select ElementName 
```

**Comment by palladia** [comment]
No response for quite a while.  Closing.

**Comment by alexpilotti** [comment]
@JumpingYang001 apologies, I just saw now the updates on this thread.
Yes, Hyper-V was enabled and the "root\virtualization\v2" namespace was definitely there.

**Comment by JumpingYang001** [comment]
@alexpilotti thanks.

re-open to track.

**Comment by paulcallen** [comment]
resourceuri is: http://schemas.microsoft.com/wbem/wsman/1/wmi/root/cimv2/*
Selector is: root/virtualization/v2

resource URI is saying namespace is root/cimv2

**Comment by sarojcare** [comment]
Jumping will try out as per Paul's comment and update the status.

**Comment by JumpingYang001** [comment]
`http://schemas.microsoft.com/wbem/wsman/1/wmi/root/cimv2/*` is "DEFAULTSCHEMA2" here: https://github.com/Microsoft/omi/blob/edbe231042173018c52903e4170dd8b782fc4f8a/Unix/wsman/wsbuf.c#L3009 , and currently we don't have any options implementation to set ResourceUri : https://github.com/Microsoft/omi/blob/edbe231042173018c52903e4170dd8b782fc4f8a/Unix/common/MI.h#L9520 .

I will build a private omicli to test if `http://schemas.microsoft.com/wbem/wsman/1/wmi/root/virtualization/v2/*` works, but I need a physical machine with enabled hyper-v, so I can test the `virtualization/v2` namespace.

BTW, we also tried remoting to localhost with `root/cimv2/test` on Linux and it works fine:
```
root@ost86-ct6-02  # /opt/omi/bin/omicli wql -u root -p 05eOsG^17 --auth Basic --hostname ost86-ct6-02 root/cimv2/test "select * from MSFT_President" --port 5985 --encryption none
instance of MSFT_President
{
    Key=1
    First=George
    Last=Washington
}
instance of MSFT_President
{
    Key=2
    First=John
    Last=Adams
} 
```
@paulcallen , the best way to fix the issue should be implementing a new `--setResourceUri` in omicli with calling https://github.com/Microsoft/omi/blob/edbe231042173018c52903e4170dd8b782fc4f8a/Unix/common/MI.h#L9520, any ideas?

If we want to implement it, then we have to wait my other 3 assigned issue to be fixed.

**Comment by JumpingYang001** [comment]
now I understand the problem, wql and cql will always use default schema2: 
https://github.com/Microsoft/omi/blob/edbe231042173018c52903e4170dd8b782fc4f8a/Unix/wsman/wsbuf.c#L3006
