### ISSUE TITLE
omicli get class operation fails using WSMan

### ISSUE THREAD

**Issue by alexpilotti** [Microsoft/omi#399]
`omicli --auth Basic -u Administrator -p blahblah  --encryption https --hostname myhost gc root/cimv2 Win32_Process
`

Fails with:

> omicli: strand.c:3028: _Strand_ScheduleImp: Assertion `allowMultiSchedule || (initialState & methodBit) == 0' failed.
> Aborted
 
Branch: master
Client OS: Ubuntu 16.04
Server OS: Windows Server 2016

**Comment by JumpingYang001** [comment]
@alexpilotti, from the test matrix provided by @paulcallen, for "get class" operation, we only support Linux->local and Windows->Linux, Paul, could you help to confirm this again? thank you!

**Comment by paulcallen** [comment]
@JumpingYang001 you are correct, however we should fail with an MI_RESULT_OPERATION_NOT_SUPPORTED error, not an assertion :)
To be precise, we support Get Class locally over the binary protocol and do not support Get Class over WSMAN for the client, although we do support it I believe in the server as Jumping stated.

**Comment by JumpingYang001** [comment]
@paulcallen , got it, thanks for sharing this!

**Comment by AlFeersum** [comment]
Could really do with supporting Linux->Windows too... even if it'll happen later, as long as it's on the roadmap that's good.  Moving from a predominantly Windows environment to a predominantly Linux environment where Windows is now providing legacy apps (and will do so for the foreseeable future), managing from a single place (i.e. a 'nix host) would mean less administration overhead.

**Comment by palladia** [comment]
Since we are in maintenance mode, there is no resource to implement this right now.
