### ISSUE TITLE
Add support for MI_OPERATIONOPTIONS in omicli

### ISSUE THREAD

**Issue by Indhukrishna** [Microsoft/omi#400]
MI client API allows the use of operation options to be passed to the provider. Currently, omicli does not support this. It would be good to have this support as part of omicli. 

From @paulcallen

To add this to omicli it would probably look like this:
./omicli iv … --operationoptions @{name, value, name, value} … rest of options
Such that if we see –operationoptions we expect to extract an MI_Instance next using the @{…} data. Then we would migrate the MI_Instance into MI_OperationOptions before passing to the MI client API.

**Comment by palladia** [comment]
As we are in maintenance mode, there is no plan to implement new features right now.
