### ISSUE TITLE
[Debian 8 x64/x86] Install omi package: start omi service process failed after registering provider

### ISSUE THREAD

**Issue by Wayenyin** [Microsoft/omi#412]
**ENV**
 
       Clients:omi86-deb8-t1 [10.226.225.35]
               omi64-deb8-t1 [10.226.172.25]
**Build**
 
-  omi build 1.4.0-2:[\\\\redmond\wsscfs\OSTCData\Builds\omi\develop\1.4.0-2\Linux_ULINUX_1.0_x64_64_Release\openssl_1.0.0](\\redmond\wsscfs\OSTCData\Builds\omi\develop\1.4.0-2\Linux_ULINUX_1.0_x64_64_Release\openssl_1.0.0) 
        
-  provider path: [\\\\ostcnfs-01\OSTCDATA\Team\v-zhenpy\providers\Linux_ULINUX_1.0_x64_64_Release\openssl_1.0.0\libTestClass_AllDMTFArrays.so
](\\ostcnfs-01\OSTCDATA\Team\v-zhenpy\providers\Linux_ULINUX_1.0_x64_64_Release\openssl_1.0.0\libTestClass_AllDMTFArrays.so
)

**Repro Steps**
1. Install omi package version 1.4.0-2;
2. Check omi process and package;
    ```
    root@omi86-deb8-t1  # ps -ef|grep omi
    root      4752     1  0 01:30 ?        00:00:00 /opt/omi/bin/omiserver --configfile=/etc/opt/omi/conf/omiserver.conf -d
    omi       4753  4752  0 01:30 ?        00:00:00 /opt/omi/bin/omiengine --configfile=/etc/opt/omi/conf/omiserver.conf -d --logfilefd 3 --socketpair 9
    root      4768  1885  0 01:30 pts/1    00:00:00 grep omi

    ~
    root@omi86-deb8-t1  # dpkg -l|grep omi
    ii  omi                           1.4.0.2                     i386         Open Management Infrastructure

    ~
    ```
3. Register provider and restart omi service process: [\\\\ostcnfs-01\OSTCDATA\Team\v-zhenpy\providers\Linux_ULINUX_1.0_x64_64_Release\openssl_1.0.0\libTestClass_AllDMTFArrays.so
](\\ostcnfs-01\OSTCDATA\Team\v-zhenpy\providers\Linux_ULINUX_1.0_x64_64_Release\openssl_1.0.0\libTestClass_AllDMTFArrays.so)
      ```
      root@omi86-deb8-t1  # /opt/omi/bin/omireg --hosting '@requestor@' -n root/cimv2 /root/libTestClass_AllDMTFArrays.so
      Created namespace directory: /etc/opt/omi/conf/omiregister/root-cimv2
      Created /opt/omi/lib/libTestClass_AllDMTFArrays.so
      Created /etc/opt/omi/conf/omiregister/root-cimv2/TestClass_AllDMTFArrays.reg
      /opt/omi/bin/omiserver: refreshed server

      ~
      root@omi86-deb8-t1  # /opt/omi/bin/service_control start
      ```
 

4. Check omi process but failed:
         ```
         root@omi86-deb8-t1  # ps -ef|grep omi
         root      4826  1885  0 01:34 pts/1    00:00:00 grep omi
         
         ~
         ```

**Expectly:** The omi service process should exist and be active.
**Actual:**  The omi sercie process cannot be found.

**Get details from /var/opt/omi/log/omiagent.root.root.log:**
   ```
    2017/10/16 00:08:44 [2887,2887] FATAL: null(0): EventId=10004 Priority=FATAL abnormal termination of parent process detected. Old parent: 2867, New parent: 1
    2017/10/16 00:22:29 [3315,3315] FATAL: null(0): EventId=10004 Priority=FATAL abnormal termination of parent process detected. Old parent: 3296, New parent: 1
    2017/10/16 00:22:29 [3349,3349] FATAL: null(0): EventId=10004 Priority=FATAL abnormal termination of parent process detected. Old parent: 3296, New parent: 1 
    ```

**Comment by palladia** [comment]
Dup of #413
