### ISSUE TITLE
ubuntu 16.04 (xenial) is missing link to libgssapi_krb5.so

### ISSUE THREAD

**Issue by yakman2020** [Microsoft/omi#416]
In the directory  /usr/lib/x86_64-linux-gnu/ normally (in other distros and other version of ubuntu) the usual convention is followed and the file libgssapi_krb5.so.2.2 is linked to libgssapi_krb5.2.so and libgssapi_krb5.so. 

In xenial, that last link is missing. So programs that link libgssapi_krb5.so get a file not found. 

This problem is not an issue in trusty, yakkety, zesty and artful. (14.04,16.10, 17.04, and 17.10)

The current workaround is to add the link to /usr/lib/x86_64-linux-gnu.  We have submitted an issue to canonical to get it fixed, but we should check and add the link in our install.

**Comment by JumpingYang001** [comment]
In my machine shows the link libgssapi_krb5.so exist as following:
```
Linux omi64-ubun16-t2 4.4.0-21-generic #37-Ubuntu SMP Mon Apr 18 18:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
root@omi64-ubun16-t2:~# lsb_release -a 
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04 LTS
Release:        16.04
Codename:       xenial
root@omi64-ubun16-t2:~# ls -al /usr/lib/x86_64-linux-gnu/|grep libgssapi_krb5
lrwxrwxrwx  1 root root       26 Jan 23  2017 libgssapi_krb5.so -> mit-krb5/libgssapi_krb5.so
lrwxrwxrwx  1 root root       21 Jan 23  2017 libgssapi_krb5.so.2 -> libgssapi_krb5.so.2.2
-rw-r--r--  1 root root   301376 Jan 23  2017 libgssapi_krb5.so.2.2

```

**Comment by JumpingYang001** [comment]
Our Kerberos configuration script is here: https://github.com/Microsoft/ostc-automation/blob/master/OMIAutomation/OMIAutomation/EnableKerberos.sh

**Comment by JumpingYang001** [comment]
your fix is right, we should use libgssapi_krb5.so.2

**Comment by JumpingYang001** [comment]
Fixed in https://github.com/Microsoft/omi/releases/tag/v1.4.0-4, close it.
