### ISSUE TITLE
Omi installer should verify that expected OpenSSL version matches the target platform

### ISSUE THREAD

**Issue by palladia** [Microsoft/omi#418]
As part of IcM 48374708, customer tried to install omi-1.4.0-4 to correct a memory issue.  Instead of using omi-1.4.0-4.ssl_100.ulinux.x64.deb, customer incorrectly used the SSL 0.98 version.  The only visible symptom of this mistake is that the omiserver failed to start after installation.  

Although omi kits are not installed often, mistakes of this kind are easy to make, and we should identify it early in the installation process.  

As part of installation, we should verify that the intended OpenSSL libraries match those on the target platform(i.e. a 0.98 kit should fail to install on a system with OpenSSL 1.0.*).

**Comment by jeffaco** [comment]
https://github.com/Microsoft/omi/pull/419

**Comment by jeffaco** [comment]
Resolved via #419
