### ISSUE TITLE
base class XYZ_ColorBase doesn't work properly

### ISSUE THREAD

**Issue by JumpingYang001** [Microsoft/omi#421]
I found this issue when debugging https://github.com/Microsoft/omi-script-provider/issues/53

Then I try this provider: https://github.com/Microsoft/omi/tree/master/Unix/samples/Providers/Color, it is OMI issue, so file it, thanks.
```
omicli ei root/cimv2 XYZ_ColorBase
instance of XYZ_ColorBase
{
    [Key] Id=1000
}
instance of XYZ_Color
{
    [Key] Id=1001
    Caption=This is Red
    Name=Red
}
instance of XYZ_Color
{
    [Key] Id=1002
    Caption=This is Green
    Name=Green
}
instance of XYZ_Color
{
    [Key] Id=1003
    Caption=This is Blue
    Name=Blue
}
instance of XYZ_Color
{
    [Key] Id=1004
    Caption=This is Yellow
    Name=Yellow
}
```

Here is what I debugged into the issue possible root cause area "**_DispatchEnumerateInstancesReq**": (Hope it is helpful to find the root cause.)
https://github.com/Microsoft/omi/blob/88e7d2a7d216fbff99c799c36dd6ce83ddc6394b/Unix/disp/disp.c#L346
`gdb attach pidofomiengine`
```
Breakpoint 1, _HandleEnumerateInstancesReq (self=0x779040 <s_data>, 
    interactionParams=0x7fff1049b370, req=0x1481a30) at disp.c:857
857     {
(gdb) break _DispatchEnumerateInstancesReq
Breakpoint 3 at 0x44953c: file disp.c, line 345.
(gdb) c
Continuing.

Breakpoint 3, _DispatchEnumerateInstancesReq (disp=0x779040 <s_data>, 
    request=0x1481a30, className=0x1481b80 "XYZ_ColorBase", 
    enumEntry=0x1486338, interactionParams=0x0) at disp.c:345
345     {
(gdb) c
Continuing.

Breakpoint 3, _DispatchEnumerateInstancesReq (disp=0x779040 <s_data>, 
    request=0x1481a30, className=0x1482000 "XYZ_Color", enumEntry=0x1486448, 
    interactionParams=0x0) at disp.c:345
345     {

```

**Comment by JumpingYang001** [comment]
This issue exist for 1.3.0,1.2.0 and 1.1.0, thanks.
Verified on these builds:
https://github.com/Microsoft/omi/releases/tag/v1.3.0-2
https://github.com/Microsoft/omi/releases/tag/v1.2.0-35
https://github.com/Microsoft/omi/releases/tag/v1.1.0-0

**Comment by paulcallen** [comment]
@JumpingYang001 can you be more specific as to what does not work? It is working based on the way it is implemented which is probably done that way for some unittest reason. The base class itself does not contain any other properties than the key. If you just want the actual colors then enumerate the XYZ_Color itself, which is correct. This does show that the polymorphic way the classes work together does in fact work.
also `-shallow` only returns the base class.
omicli is missing one of the polymorphic options OMI supports which does a deep enumeration returning the shallow class only, so you would only get the key property for all instances... assuming OMI does support that. The WSMAN standard does have that option.

**Comment by JumpingYang001** [comment]
I was expecting this this:
```
omicli ei root/cimv2 XYZ_ColorBase
instance of XYZ_ColorBase
{
    [Key] Id=1000
}
```
It should not list XYZ_Color, if I have many classes based on XYZ_ColorBase, it will list all classes when calling `omicli ei root/cimv2 XYZ_ColorBase`, that's by design?

**Comment by paulcallen** [comment]
This is by design. If you only want the XYZ_ColorBase then you would need the -shallow option on omicli. OMI uses an object oriented model of polymorphic objects, That is why you get derived classes also.

**Comment by JumpingYang001** [comment]
all right, this is very speicial design and it is different with OOP programming languages like C++, java or C#. :)
