### ISSUE TITLE
`download.sh` needs to be replaced with `install-powershell.sh` in 'installntlm-ubuntu16'

### ISSUE THREAD

**Issue by daxian-dbw** [Microsoft/omi#434]
I find the references to the powershell `download.sh` in [`installntlm-ubuntu16`](https://github.com/Microsoft/omi/blob/c962c76aecae4dbe4eafa5cd3c00e075c07fe0fb/Unix/scripts/installntlm-ubuntu16#L73) from a search in Github.

The `download.sh` file under the `tools` folder of the [PowerShell repository](https://github.com/PowerShell/PowerShell) was deprecated and now is removed. Please use the `install-powershell.sh` file from the same folder to install powershell on Linux.

**Comment by JumpingYang001** [comment]
It is fixed on PowerShell side: https://github.com/PowerShell/PowerShell/commit/55f6827aa9841466508640e8e63e29bcffb7856a
and it is only available on source code and doesn't show in production.

So just close it, thanks.
