### ISSUE TITLE
Port 5589 disabled by default in version 1.4.1.0

### ISSUE THREAD

**Issue by CooperCOK** [Microsoft/omi#447]
Installaing OMI version 1.4.1.0 sets the https port to 0:

$ cat /etc/opt/omi/conf/omiserver.conf
# omiserver configuration file

##
##
httpport=0

##
##
httpsport=0

Is this by intention? So no DSC push is possible by default?

**Comment by JumpingYang001** [comment]
omi is by design for this since 1.1.0.

**Comment by JumpingYang001** [comment]
DSC should do enable the ports they need, thanks.
