### ISSUE TITLE
OMI Logging: OMI logs ERROR message (NTLM creds) in absolutely normal case

### ISSUE THREAD

**Issue by jeffaco** [Microsoft/omi#449]
When starting up OMI v1.4.1-0 on a machine that is not domain joined (the normal case for many of our customers), I see an error in the OMI log file:

```
2017/11/17 15:00:44 [125770,125770] ERROR: null(0): EventId=20135 Priority=ERROR NTLM Credentials file does not exist or invalid permissions: null
```

OMI should not log error messages in normal cases. This causes needless OMI log growth and customer confusion.

**Comment by palladia** [comment]
This message has been changed to INFO.
