### ISSUE TITLE
OMI Logging: OMI logs warnings during enumeration in non-error cases

### ISSUE THREAD

**Issue by jeffaco** [Microsoft/omi#450]
When performing an absolutely normal enumeration via a command like:

```
/opt/omi/bin/omicli ei root/scx SCX_Agent                    
```

I get errors logged:

```
2017/11/17 15:01:08 [125771,125771] WARNING: null(0): EventId=30107 Priority=WARNING Sock_Read: Error 9
2017/11/17 15:01:08 [125771,125771] WARNING: null(0): EventId=30112 Priority=WARNING Socket: 0x1d9dac0, Error: 1 while reading header

2017/11/17 15:01:08 [125771,125771] WARNING: null(0): EventId=30214 Priority=WARNING Selector_RemoveHandler: selector=0x5df9e8, handler=0x1d9dac0, name=null NOT REGISTERED
```

Given that the warnings were logged when no error occurred, these messages should be removed (or only emitted in true error cases).

OMI should not log error or warning messages in normal cases. This causes needless OMI log growth and customer confusion. In this particular case, this occurs on EVERY enumeration, causing huge OMI log file growth over time.

**Comment by palladia** [comment]
Fixed in 1.4.2.
