### ISSUE TITLE
OMI Logging: OMI log file is MUCH too chatty in INFO mode

### ISSUE THREAD

**Issue by jeffaco** [Microsoft/omi#452]
The OMI log file is much too "chatty" when INFO-level logging is enabled. INFO-level logging should show, and should ONLY show (in addition to valid errors or warnings):

1. The Request/operation (1 message per operation)
2. Instance posted (0 or more, depending on provider)
3. Actual result (MI_RESULT_OK, _FAILED, etc) (1 message per operation)

Add handler, removing handler, closing connections are all "normal", and are useless noise, causing rather explosive growth of the OMI log file. This grep eliminates most of the useless messages, leaving valuable ones for customers with problems:

```
jeffcof:log> grep INFO omiserver.log  | grep -v Handler | grep -v msg | grep -v -i "Connection"
2017/11/17 15:20:59 [126706,126706] INFO: null(0): EventId=40019 Priority=INFO /opt/omi/bin/omiserver exiting
2017/11/17 15:20:59 [126752,126752] INFO: null(0): EventId=40038 Priority=INFO Starting OMI: version: (1.4.1-0), platform: (LINUX_X86_64_GNU)
2017/11/17 15:21:29 [126752,126752] INFO: null(0): EventId=40039 Priority=INFO New request received: command=(EnumerateInstancesReq), namespace=(root/scx), class=(SCX_Agent)
2017/11/17 15:21:33 [126752,126752] INFO: null(0): EventId=40039 Priority=INFO New request received: command=(EnumerateInstancesReq), namespace=(root/scx), class=(SCX_Agent)
2017/11/17 15:21:33 [126752,126752] INFO: null(0): EventId=40004 Priority=INFO _SendErrorResponse, RequestItem: 0x181e330
2017/11/17 15:38:45 [126752,126752] INFO: null(0): EventId=40039 Priority=INFO New request received: command=(EnumerateInstancesReq), namespace=(root/omi), class=(OMI_Identify)
jeffcof:log> 
```

We do specifically want version information (that's important), as well as start/exit messages of the server. Beyond that, we only need new request received, instance posted, and actual result. We clearly want to know about abnormal terminations, like this:

```
2017/11/17 15:21:33 [126751,126751] WARNING: null(0): EventId=30209 Priority=WARNING child process with PID=[127048] terminated abnormally
```

However, this is a warning message, and would still log in INFO mode. This sort of message indicates that the omiagent process crashed, highly likely due to a provider bug (not an OMI bug).

**Comment by palladia** [comment]
This has been fixed.
