### ISSUE TITLE
will support more OS in the future?

### ISSUE THREAD

**Issue by JumpingYang001** [Microsoft/omi#456]
[PowerShell](https://github.com/PowerShell/PowerShell) has supported Ubuntu 17.04,OpenSUSE 42.2, Fedora 25,Fedora 26 and Kali Linux, maybe we will support it in the future? I just pick it up here, thanks.

A lots of things we need to do if we want to support:
1. Setup OS images in Nebula
2. Install OMI manually and check "omicli id" if it works or not.
3. Full test pass on the new platforms.

**Comment by jeffaco** [comment]
I'm going to close this. There has been considerable discussion of what we choose to support. All of the examples that you specified are all "development" versions (Ubuntu 17 has no LTE releases, Fedora is only around for 6 months, etc). We will only formally support versions of Linux that have long-term support by their respective vendors. None of the above cases fit that criteria.

That said, OMI may very well work on those platforms. But that's strictly "as is", and unsupported by us.
