### ISSUE TITLE
Remove WCHAR and Windows support from OMI code base

### ISSUE THREAD

**Issue by jeffaco** [Microsoft/omi#460]
WCHAR support doesn't really work in OMI, nor does Windows support.

These capabilities should be stripped from the code base since they aren't functional anyway. Doing so would simplify further development on the OMI project.

**Comment by palladia** [comment]
Windows code has been removed.   WCHAR removal will be done later.

**Comment by BingyuLiu** [comment]
I am working on it.

**Comment by sarojcare** [comment]
Windows support has already dropped. George will investigate further on removing WCHAR support.

**Comment by BingyuLiu** [comment]
I am working on it

**Comment by JumpingYang001** [comment]
we can close this issue now, my account has some problem now and I don't have permission to close it now, possibly will have permission 2 days later.

**Comment by BingyuLiu** [comment]
Fixed and closed it.
