### ISSUE TITLE
omsagent PerformRequiredConfigurationChecks fails to create configuration directory

### ISSUE THREAD

**Issue by thiezn** [Microsoft/omi#477]
Hello,

We are deploying cloudfoundry hardened linux stem cells to Microsoft Azure but having difficulty getting OMI to register itself. Because of this Microsoft Security Center is unable to scan for security updates, etc. 

The output of 'PerformRequiredConfigurationChecks.py' seems to indicate this is a permissioning issue somewhere but I haven't been able to find a reference to the configuration directory the output points to. Is there some way to determine where the agent is trying to write?

```
sudo -u omsagent /opt/microsoft/omsconfig/Scripts/PerformRequiredConfigurationChecks.py
instance of OMI_Error
{
    OwningEntity=OMI:CIMOM
    MessageID=OMI:MI_Result:1
    Message=The creation of the configuration directory failed. Verify the directory permissions and try again.
    MessageArguments={}
    PerceivedSeverity=7
    ProbableCause=0
    ProbableCauseDescription=Unknown
    CIMStatusCode=1
    OMI_Code=1
    OMI_Category=0
    OMI_Type=MI
    OMI_ErrorMessage=A general error occurred, not covered by a more specific error code.
}

/opt/omi/bin/omicli: result: MI_RESULT_FAILED
/opt/omi/bin/omicli: result: The creation of the configuration directory failed. Verify the directory permissions and try again.

```

**Comment by paulcallen** [comment]
I believe this is not an OMI error, rather an OMS error, so you will need to follow up with them instead.

**Comment by thiezn** [comment]
Thanks, I don't mind raising it against the omsagent repository but thought I should raise it here because the error seems to be generated by /opt/omi/bin/omicli?

**Comment by thiezn** [comment]
raised https://github.com/Microsoft/OMS-Agent-for-Linux/issues/625

**Comment by paulcallen** [comment]
omicli is a client-side protocol implementation for what is going on within the server. In this case the error is coming from a provider hosted in omiserver running on the local machine. As the error is not being generated from omicli or omiserver directly it needs to be that provider that has the bug.
