### ISSUE TITLE
"omiagent" segfault libnss_dns on Linux

### ISSUE THREAD

**Issue by srice01** [Microsoft/omi#491]
On our RM provisioned VMs in Azure we noticed that the root partition is filling up with large numbers of "core.###" files in the /var/opt/omi/run directory.

Further investigation shows segmentation faults (in /var/log/messages) as follows:
```
Jan 30 10:17:17 ML001 kernel: omiagent[2054]: segfault at 7f6b7e181e00 ip 00007f6b7e181e00 sp 00007f6b78846d50 error 14
Jan 30 10:32:12 ML001 kernel: omiagent[3298]: segfault at 7fa8356f4e00 ip 00007fa8356f4e00 sp 00007fa82fdb9d50 error 14
Jan 30 11:02:19 ML001 kernel: omiagent[5873]: segfault at 7fbd84d3de00 ip 00007fbd84d3de00 sp 00007fbd7ede0d50 error 14 in libnss_dns-2.17.so[7fbd84ec5000+5000]
Jan 30 11:17:19 ML001 kernel: omiagent[13175]: segfault at 7fbac740ae00 ip 00007fbac740ae00 sp 00007fbac54bcd50 error 14 in libnss_dns-2.17.so[7fbac7592000+5000]
Jan 30 11:32:21 ML001 kernel: omiagent[20049]: segfault at 7f79230dfe00 ip 00007f79230dfe00 sp 00007f791d7a4d50 error 14
Jan 30 12:02:14 ML001 kernel: omiagent[46782]: segfault at 7f9fa8939e00 ip 00007f9fa8939e00 sp 00007f9fa296dd50 error 14 in libnss_dns-2.17.so[7f9fa8ac1000+5000]
```
Environment information:

- OMS Agent: 1.4.3-174 (latest)
- OMI 1.4.1
- Operating System: CentOS Release 7.4.1708 (fully patched, that is, "yum update" shows no updates pending)

So far the workaround has been to write a cron job (!) to periodically wipe the core files but obviously this is not an ideal situation.  Note that this issue was originally posted to the "OMS-Agent-for-Linux" repository though requested by "NarineM" to move here.

**Comment by palladia** [comment]
From our experience, problems like this with omiagent are nearly always with the provider, not OMI itself.  Some suggestions:

1.  A more recent version of OMS and OMI are now available.  Does problem still exist with newer version? 
2.  If still a problem, enable INFO-level debugging.
2.  Take a look in omiagent log file to see which provider and what command was being executed just before the crash.

A more general debugging document is available at:  https://github.com/Microsoft/omi/blob/master/Unix/doc/diagnose-omi-problems.md

**Comment by JumpingYang001** [comment]
@srice01 , can you send one core file to my email? I want to check the core file, thanks.
my email: yzpcreate@qq.com

**Comment by srice01** [comment]
Thank you @palladia for your suggestions.  The environment here is provisioned in Azure using the RM model with the "OpenLogic CentOS 7.3" image.  This results in the specific versions of OMI and OMS software being pre-installed or installed by Azure itself.

I have attempted to update OMI to 1.4.2.  OMI 1.4.2 requires the "1.1.0" version of OpenSSL which is not available in the yum repository so I manually compiled and installed however the OMI install still fails as it is not finding the OpenSSL that was installed (I cannot remove the existing "openssl" packages as it will remove many other packages that that the Azure VM depends on).  

So, I am afraid I am a bit stuck.

**Comment by vwbusguy** [comment]
Running into the same issue on Fedora 27.  There's a mismatch on expected SSL version between 1.4.1 and 1.4.2:

```
Running transaction
  Preparing        :                                                                                                                                                                                           1/1 
  Running scriptlet: omi-1.4.2-1.x86_64                                                                                                                                                                        1/2 
Expecting SSL version (compatible with): 1.0.0
SSL version found on system:             1.1.0g-fips

Incorrect version of OMI for your system, please check SSL version.
error: %prein(omi-1.4.2-1.x86_64) scriptlet failed, exit status 3
Error in PREIN scriptlet in rpm package omi
Error in PREIN scriptlet in rpm package omi
omi-1.4.2-1.x86_64 was supposed to be installed but is not!
  Verifying        : omi-1.4.2-1.x86_64                                                                                                                                                                        1/2 
omi-1.4.1-0.x86_64 was supposed to be removed but is not!
  Verifying        : omi-1.4.1-0.x86_64                                                                                                                                                                        2/2 

Failed:
  omi.x86_64 1.4.2-1                                                                                                                                                                                               

Error: Transaction failed
```

**Comment by JumpingYang001** [comment]
@srice01 @vwbusguy I think you should install incorrect version of omi, we provided 0.9.8, 1.0 and 1.1 here: https://github.com/Microsoft/omi/releases/tag/v1.4.2-1, please don't do remove/install about openssl, just pick up the correct version package according to `openssl version`, thanks.

**Comment by JumpingYang001** [comment]
@srice01 I can try to help to debug issues if I have a core file, thanks.

**Comment by srice01** [comment]
@JumpingYang001 - Again, I have attempted to install OMI 1.4.2 but the insists on a different version of OpenSSL be installed (even though this new version is installed, it does not see it).  

I have been working on seeing whether I have security clearance to send you the core file as it may contain confidential information.

**Comment by JumpingYang001** [comment]
you should install https://github.com/Microsoft/omi/releases/download/v1.4.2-1/omi-1.4.2-1.ssl_100.ulinux.x64.deb or https://github.com/Microsoft/omi/releases/download/v1.4.2-1/omi-1.4.2-1.ssl_100.ulinux.x64.rpm if you openssl version is 1.0.

**Comment by JumpingYang001** [comment]
In fact, you should upgrade OMS to https://github.com/Microsoft/OMS-Agent-for-Linux/releases/download/OMSAgent_GA_v1.4.4-210/omsagent-1.4.4-210.universal.x64.sh using `sh omsagent-1.4.4-210.universal.x64.sh --upgrade`. (OMS contains omi)

**Comment by vwbusguy** [comment]
@JumpingYang001 - I installed it from the packages.microsoft.com yum repo, which only appears to ship the -100.  https://packages.microsoft.com/yumrepos/microsoft-rhel7.3-prod/  I'll try with the -110 on the GitHub releases.

**Comment by srice01** [comment]
@JumpingYang001 - The openssl version I had WAS 1.0 but the OMI 1.4.2 RPM installer said it required 1.1.0, as follows:

> Expecting SSL version (compatible with): 1.1.0
> SSL version found on system:             1.0.2k-fips

**However**, I have followed your instructions regarding running the OMS upgrade and that appears to have worked, so the question will be whether I still see the core dumps.  Will have to watch for it and advise.

**Comment by vwbusguy** [comment]
@JumpingYang001  Installing from the GitHub release -110 worked on Fedora 27.  I assume the best thing to do from here to to exclude omi from the yum repo until -110 packages become available there (or a Fedora-specific repo is provisioned).

**Comment by JumpingYang001** [comment]
@srice01 your message shows you was trying to install incorrect version omi packing, the package expect to run on openssl 1.1 but your openssl is 1.0.

**Comment by srice01** [comment]
@JumpingYang001 - I am still seeing core dumps with the new versions of OMS and OMI.  Will send through one of those as soon as I can.

**Comment by JumpingYang001** [comment]
@srice01 @vwbusguy from what you shows, looks like yum pick up incorrect omi package for you.

**Comment by srice01** [comment]
@JumpingYang001 - Yes, what you are saying about "yum" is correct but the https://github.com/Microsoft/OMS-Agent-for-Linux/releases/download/OMSAgent_GA_v1.4.4-210/omsagent-1.4.4-210.universal.x64.sh script installed the newer versions.  I am now using OMI 1.4.2 and OMS 1.4.4

**Comment by JumpingYang001** [comment]
@srice01 from your provided core file, the issue should be from scx provider, I think you should report the issue to scx provider: https://github.com/Microsoft/SCXcore

you might need help from scx provider team to debug what does scx doing cause the crash, they might need to enable OMI Logging as George said in https://github.com/Microsoft/omi/issues/491#issuecomment-368994391 

omiagent is doing anything that provider make/implement the detailed thing that they want it to do.

Following debug info shows omiagent loaded scx provider:
```
(gdb) info sharedlibrary                                                                                                                
From                To                  Syms Read   Shared Object Library
0x00007fa598b2f900  0x00007fa598b3ace1  Yes (*)     /lib64/libpthread.so.0
0x00007fa598926e60  0x00007fa59892795e  Yes (*)     /lib64/libdl.so.2
0x00007fa598719670  0x00007fa598720d0c  Yes (*)     /lib64/libpam.so.0
0x00007fa5984bfbb0  0x00007fa5984fb58d  Yes (*)     /opt/omi/lib/libssl.so.1.0.0
0x00007fa5980b0f00  0x00007fa5981e8bd7  Yes (*)     /opt/omi/lib/libcrypto.so.1.0.0
0x00007fa597ca0480  0x00007fa597de6bcf  Yes (*)     /lib64/libc.so.6
0x00007fa598d46b10  0x00007fa598d61440  Yes (*)     /lib64/ld-linux-x86-64.so.2
0x00007fa597a5c100  0x00007fa597a62402  Yes (*)     /lib64/libaudit.so.1
0x00007fa597818650  0x00007fa59784aa1a  Yes (*)     /lib64/libgssapi_krb5.so.2
0x00007fa597549a10  0x00007fa5975b0e8a  Yes (*)     /lib64/libkrb5.so.3
0x00007fa597321570  0x00007fa597322143  Yes (*)     /lib64/libcom_err.so.2
0x00007fa5970f18c0  0x00007fa59710fc0f  Yes (*)     /lib64/libk5crypto.so.3
0x00007fa596ed9170  0x00007fa596ee56f8  Yes (*)     /lib64/libz.so.1
0x00007fa596cd2580  0x00007fa596cd43bc  Yes (*)     /lib64/libcap-ng.so.0
0x00007fa596ac6890  0x00007fa596acd42b  Yes (*)     /lib64/libkrb5support.so.0
0x00007fa5968c05b0  0x00007fa5968c11cc  Yes (*)     /lib64/libkeyutils.so.1
0x00007fa5966a89d0  0x00007fa5966b77e1  Yes (*)     /lib64/libresolv.so.2
0x00007fa596484ac0  0x00007fa59649a8c6  Yes (*)     /lib64/libselinux.so.1
0x00007fa59621d5f0  0x00007fa5962635b0  Yes (*)     /lib64/libpcre.so.1
0x00007fa595ed6430  0x00007fa596034438  Yes         /opt/omi/lib/libSCXCoreProviderModule.so
0x00007fa598e0fcc0  0x00007fa598e2b568  Yes         /opt/omi/lib/libmicxx.so
0x00007fa595b78e50  0x00007fa595b7daac  Yes (*)     /lib64/libcrypt.so.1
0x00007fa595972250  0x00007fa59597504c  Yes (*)     /lib64/librt.so.1
0x00007fa5956c3510  0x00007fa59572a5ba  Yes (*)     /lib64/libstdc++.so.6
0x00007fa59536b370  0x00007fa5953d6276  Yes (*)     /lib64/libm.so.6
0x00007fa595152af0  0x00007fa5951622a5  Yes (*)     /lib64/libgcc_s.so.1
0x00007fa594f4dba0  0x00007fa594f4e309  Yes (*)     /lib64/libfreebl3.so
0x00007fa58e8131d0  0x00007fa58e81a3e1  Yes (*)     /lib64/libnss_files.so.2
0x00007fa58e60c090  0x00007fa58e60f4f0  Yes (*)     /lib64/libnss_dns.so.2
0x00007fa58d908ec0  0x00007fa58d933b0f  Yes (*)     /lib64/libssl3.so
0x00007fa58d6df380  0x00007fa58d6f3e57  Yes (*)     /lib64/libsmime3.so
0x00007fa58d3c5740  0x00007fa58d498654  Yes (*)     /lib64/libnss3.so
0x00007fa58d18b390  0x00007fa58d199d45  Yes (*)     /lib64/libnssutil3.so
0x00007fa58cf7bf10  0x00007fa58cf7cc78  Yes (*)     /lib64/libplds4.so
0x00007fa58cd77510  0x00007fa58cd78b78  Yes (*)     /lib64/libplc4.so
0x00007fa58cb44ca0  0x00007fa58cb64cc0  Yes (*)     /lib64/libnspr4.so
0x00007fa58c27e2d0  0x00007fa58c2a7f5c  Yes (*)     /lib64/libsoftokn3.so
---Type <return> to continue, or q <return> to quit---
0x00007fa57e552a00  0x00007fa57e5da860  Yes (*)     /lib64/libsqlite3.so.0
0x00007fa57e2c8bc0  0x00007fa57e32196d  Yes (*)     /lib64/libfreeblpriv3.so
0x00007fa58c077cd0  0x00007fa58c0783cb  Yes (*)     /lib64/libnsssysinit.so
0x00007fa57e09e7e0  0x00007fa57e0b8496  Yes (*)     /lib64/libnsspem.so
(*): Shared library is missing debugging information.
(gdb) 
```

The crash is on 0x00007fa58e405e00 which is in /lib64/libnss_dns.so.2, that is same as your segmentation faults in /var/log/messages.
```
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /opt/omi/bin/omiagent...done.
[New LWP 123588]
[New LWP 108293]
[New LWP 108369]
[New LWP 108394]
[New LWP 108295]
[New LWP 108294]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/opt/omi/bin/omiagent 9 10 --destdir / --providerdir /opt/omi/lib --loglevel WA'.
Program terminated with signal 11, Segmentation fault.
#0  0x00007fa58e405e00 in ?? ()
Missing separate debuginfos, use: debuginfo-install omi-1.4.2-1.x86_64
(gdb) bt
#0  0x00007fa58e405e00 in ?? ()
#1  0x00007fa58e449f47 in ?? ()
#2  0x00007fa58e449b60 in ?? ()
#3  0xffffffff00000073 in ?? ()
#4  0x0000000000000000 in ?? ()
```

here is threads:
```
(gdb) info threads
  Id   Target Id         Frame 
  6    Thread 0x7fa598e01f00 (LWP 108294) 0x00007fa598b35cf2 in pthread_cond_timedwait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
  5    Thread 0x7fa598dc2f00 (LWP 108295) 0x00007fa598b35cf2 in pthread_cond_timedwait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
  4    Thread 0x7fa58e5caf00 (LWP 108394) 0x00007fa598b35cf2 in pthread_cond_timedwait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
  3    Thread 0x7fa58e609f00 (LWP 108369) 0x00007fa598b35cf2 in pthread_cond_timedwait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
  2    Thread 0x7fa598f53880 (LWP 108293) 0x00007fa597d707a3 in select () from /lib64/libc.so.6
* 1    Thread 0x7fa57ffff700 (LWP 123588) 0x00007fa58e405e00 in ?? ()
```

**Comment by johanburati** [comment]
If you are having this issue check https://github.com/Azure/azure-linux-extensions/issues/875 for details and solution.
