### ISSUE TITLE
segfault error 14 in libMSFT_nxOMSAuditdPluginResource.so

### ISSUE THREAD

**Issue by tho-wa** [Microsoft/omi#493]
We have segfault on multiple hosts with Version  1.4.2-1:
kernel: [2707120.628530] omiagent[21214]: segfault at 7f79c5e1f6fa ip 00007f79c5e1f6fa sp 00007fffef896af8 error 14 in libMSFT_nxOMSAuditdPluginResource.so[7f79c6066000+18000]

**Comment by JumpingYang001** [comment]
it is DSC provider crash issue, recommend you move it to dsc repo: https://github.com/Microsoft/PowerShell-DSC-for-Linux , thanks.
if you can send me crash core dump(should be under /etc/opt/omi/run or other place call core.*), I can help to check the debug information. my mail is yzpcreate@qq.com. if you want to send me core file, you can share with me about your operating system, oms vesrion, is it on Azure, that will be useful.
