### ISSUE TITLE
OMI support for Ubuntu 18.04 LTS 

### ISSUE THREAD

**Issue by sreedharsingaraju** [Microsoft/omi#507]
The supported OS is mentioned only till Ubuntu 16.04, is there any version of OMIServer which supports Ubuntu 18.04

**Comment by JumpingYang001** [comment]
I tried it on latest Ubuntu 18.04, it shows 3 errors when installing omi:
![ub18error](https://user-images.githubusercontent.com/16585827/38979200-0b72bb72-43a9-11e8-90f0-136f48750cfe.PNG)

**Comment by JumpingYang001** [comment]
Found the inner error:
![ub18innererror](https://user-images.githubusercontent.com/16585827/38982825-753e3b40-43b2-11e8-8440-57a993000920.PNG)

**Comment by JumpingYang001** [comment]
`system enable` will call `system daemon-reload`: https://github.com/systemd/systemd/blob/eb2c3192dc6f4f4d86023f9379e1fb964a3c6c8c/src/systemctl/systemctl.c#L6119

Need to investigate [daemon-reload function](https://github.com/systemd/systemd/blob/eb2c3192dc6f4f4d86023f9379e1fb964a3c6c8c/src/systemctl/systemctl.c#L5451) tomorrow.

**Comment by JumpingYang001** [comment]
@sreedharsingaraju  , have you tried it? :) do you meet same issue with me?

**Comment by JumpingYang001** [comment]
Found the error and solution:
https://ubuntuforums.org/archive/index.php/t-1163250.html
/dev/fd0 is a floppy drive, if you are getting the error and you don't have a floppy drive, disable it in the bios and you shouldn't have any more problems.

It is not omi issue, the error has gone after add a floppy or disable floppy in BIOS.
![ub18error_fixed](https://user-images.githubusercontent.com/16585827/39034786-37019858-4467-11e8-943d-d6653a327494.PNG)

**Comment by JumpingYang001** [comment]
@sreedharsingaraju , OMI test team has signoff with new v1.4.3 release, but we need to wait all related teams signoff, then we can publish it on GitHub, thanks.
It will be published here: https://github.com/Microsoft/omi/releases/tag/v1.4.3

**Comment by palladia** [comment]
Support for Ubuntu 18.04 is now included.
