### ISSUE TITLE
Split ulinux installation package into individual linux platform packages

### ISSUE THREAD

**Issue by palladia** [Microsoft/omi#508]
This is a request from a customer.  Currently, we have a single installation distro for all linux platforms (not counting the ssl and x86/x64 differences).  This was probably done for historical reasons.  But as we add support for more platforms, a number of problems are seen:

1.  Scripts in installbuilder/datafiles/Linux.data and installbuilder/service_scripts/service_control.linux are getting more and more complicated.  Large if-else statements are becoming unwieldy.

2.  Different platforms support different mechanism for service control - init, upstart, systemd, etc.  Some platforms support multiple methods, and not all mechanisms behave identically across platforms.  This adds more complications.

3.  Changing anything requires full retest of all platforms.

**Comment by JumpingYang001** [comment]
this is a big design change, any idea or related design example for individual package we want?

**Comment by palladia** [comment]
With cleaning up of old platforms (due to TLS1.2 support) from the support matrix,   this problem should be addressed to some extent as we would clean-up the   installation scripts for these deprecated platforms.
--
