### ISSUE TITLE
Azure OMI user automatically created

### ISSUE THREAD

**Issue by dcbrown16** [Microsoft/omi#514]
Hi, I'm assisting a customer who had what looks to be an OMI-related user automatically created on his Azure VM, something like the following.

    omi:x:XXXXXX:784::/home/omi:/bin/false

Am I in the right place to ask about that? If so, the question at hand is if the VM owner can change the user ID of this user to something else. Would that cause any negative consequences?

Thanks!

**Comment by JumpingYang001** [comment]
@dcbrown16 it will affect omi permission will cause an omi permission issue if you change its uid.
currently, we have been requested for omi uid to be less 1000, and we are publishing a hotfix on https://github.com/Microsoft/omi/releases/tag/v1.4.2-3, it is in progress.
Not sure whether you met same issue or other requrements to change the uid? can you share the reason to change its uid? thanks.

**Comment by dcbrown16** [comment]
From what I understand, the ID here is 784, so I think it's already lower than 1000?
I'm not exactly sure what the customer meant about wanting to change the uid, from what I understand they said it was created with a uid for an admin.

**Comment by JumpingYang001** [comment]
We are pubilshing the above v1.4.2-3 hotfix from normal user to system user, does a system user meet customer's requirement?

**Comment by dcbrown16** [comment]
So with the hotfix, the OMI user will be created as (or changed to?) a system user?
I'll check with the customer about that, thank you.

**Comment by JumpingYang001** [comment]
Yes, we are changing it to a system user.

**Comment by JumpingYang001** [comment]
Only for Linux, and we doesn't change Unix(Aix, HP, Solaris) omi uid.

**Comment by dcbrown16** [comment]
Thanks so much @JumpingYang001 , I figured out that OMI gets installed automatically on Linux machines at least for communication with a Log Analytics workspace when configuring monitoring. And yes, the actual user ID in this case was over 20000, so changing it to under 1000 might help.
Should the user try to apply the hotfix now, or will that be wrapped up in an official update soon?

**Comment by JumpingYang001** [comment]
The hotfix is in progress, we will publish it on https://github.com/Microsoft/omi/releases/tag/v1.4.2-3 at first (might be this week, but I am not sure now), then OMS has their publish model might be later.
So just upgrade to v1.4.2-3 once it is published on GitHub, I will tell you in this page once we publish the hotfix, thanks.

**Comment by dcbrown16** [comment]
Great, thanks so much!

**Comment by dcbrown16** [comment]
@JumpingYang001 , just checking, the hotfix is not officially released yet right? Thanks!

**Comment by JumpingYang001** [comment]
yeah, we have internal build  before 2 days, but it need to wait OMS team to signoff, thanks.

**Comment by dcbrown16** [comment]
@JumpingYang001 , just checking in, still waiting on OMS team signoff? Thanks!

**Comment by JumpingYang001** [comment]
@dcbrown16 , we remain SCX team and LAD team to signoff, possible next week...
About 4 teams signoff(OMS, DSC, PowerShell, Container), we remain 2 teams to signoff now, thanks.

**Comment by dcbrown16** [comment]
Thanks for responding, I'll check in next week then!

**Comment by JumpingYang001** [comment]
@dcbrown16 All signoff, but Looks like Need another team to sign with pgp v3, thanks.
OMI release, version 1.4.2-3.  Release notes are available here:  https://github.com/Microsoft/omi/releases/tag/v1.4.2-3
 
In addition to OMI Github page, you can also find downloads from https://github.com/Microsoft/omi-kits and \\redmond\wsscfs\OSTCData\Builds\omi\release\1.4.2-3

**Comment by dcbrown16** [comment]
Thanks @JumpingYang001 ! Will this switch the existing omi user to a system user with ID under 1000, or do they need to do any extra steps to change the user ID?

**Comment by JumpingYang001** [comment]
both new installation and upgrade to the hotfix will do, needn't extra steps.

**Comment by dcbrown16** [comment]
Thanks @JumpingYang001 , it sounds like the customer decided not to install so I wasn't able to verify, but they were satisfied that this change was made. Closing the issue.
