### ISSUE TITLE
Handle session cookies over HTTP to reliably work with office365.

### ISSUE THREAD

**Issue by dantraMSFT** [Microsoft/omi#523]
PowerShell has received a number of reports of errors when connecting to office365 through https://outlook.office365.com/powershell-liveid/.

The symptoms are as follows:
1: Connect to office 365
$Session = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri https://outlook.office365.com/powershell-liveid/ -Credential $O365Credential -Authentication Basic -AllowRedirection

2: Perform various commands

3: At somewhat random times, commands on the connection start returning ERROR_WSMAN_INVALID_SELECTORS and the connection is no longer usable.

Analysis of the logs shows office365 is behind a load balancer and returns a cookie in the response.
Set-Cookie: MS-WSMAN=S-1-5-21-2553855760-3398840149-2091067650-9554679=rJqNiZqNgbKot6+tzc6yvc/Nx8fRkZ6Sj42bzc7Rj42Qm9GQiouTkJCU0ZyQkoHOxsvMzM/Iz8fOgc3PzsfSz8rSzcarzsjFzsrFysg=; expires=Tue, 29-May-2018 17:15:57 GMT; path=/powershell-liveid; secure; HttpOnly

The problem can be reproduced but no consistently since it's subject to load balancing.

The PowerShell issue tracking the problem is https://github.com/PowerShell/PowerShell/issues/3771

**Comment by JumpingYang001** [comment]
This looks like a DCR, @Microsoft/omi-devs

**Comment by paulcallen** [comment]
it kind of is a DCR. However it was believed that psrp remoting worked against office365 and this is blocking that from working.
If a cookie is returned for a request on the session it should be included in all future requests on that session.

**Comment by dantraMSFT** [comment]
@JumpingYang001 PSRP does work with office365 until the load balancer directs requests to another server.  I've seen it remain valid for multiple hours and also seen it fail in ~1 minute.  At that point, the session cannot be used.

**Comment by JumpingYang001** [comment]
I didn't use psrp/PowerShell to remote to office365, Let me try it first and then try to understand the problem, thanks.

**Comment by paulcallen** [comment]
The problem is understood! The http client code needs to support cookies!

**Comment by JumpingYang001** [comment]
@paulallen could you help to explain the logic? is my below understand right or wrong?
1. powershell call psrp, then psrp call libmi.so to send http request to office365.
2. libmi.so get http response from office365, and then send it back to psrp, then powershell get the data.

the problem is in point 2, libmi.so doesn't save response cookie from office365 while it send back to psrp, right?

**Comment by JumpingYang001** [comment]
BTW, we have reproduced the issue today.

**Comment by dantraMSFT** [comment]
FYI: I'm currently working on a fix for this but can't assign it to myself in this repo.  ETA for PR is 6/29

**Comment by dantraMSFT** [comment]
Fixed wtih https://github.com/Microsoft/omi/pull/539

**Comment by dantraMSFT** [comment]
Reactivating ; the solution breaks backwards compat in binary serialization.
