### ISSUE TITLE
ktstrip cron job not calling ktutil correctly

### ISSUE THREAD

**Issue by twstdpear** [Microsoft/omi#529]
Running Ubuntu 16.04 in Azure with Heimdal Kerberos.  

Every minute, we're receiving the following email for around 80 systems:
Subject: 
> Cron <root@ase1cp-itmg-001> [ -f /etc/krb5.keytab ] && [ \( ! -f /etc/opt/omi/creds/omi.keytab \) -o \( /etc/krb5.keytab -nt /etc/opt/omi/creds/omi.keytab \) ] && /opt/omi/bin/support/ktstrip /etc/krb5.keytab /etc/opt/omi/creds/omi.keytab || true

Body:
> src kt = /etc/krb5.keytab
> Usage: ktutil [-hv] [--version] [--help] [--keytab=keytab to operate on]
>    [-k keytab to operate on] [--verbose] command
> -k keytab to operate on, --keytab=keytab to operate on keytab
> -v, --verbose                                          verbose
> Creating /etc/opt/omi/creds/omi.keytab
> Usage: ktutil [-hv] [--version] [--help] [--keytab=keytab to operate on]
>    [-k keytab to operate on] [--verbose] command
> -k keytab to operate on, --keytab=keytab to operate on keytab
> -v, --verbose                                          verbose
> Move /tmp/tmp.kt to /etc/opt/omi/creds/omi.keytab
> mv: cannot stat '/tmp/tmp.kt': No such file or directory
> chown: cannot access '/etc/opt/omi/creds/omi.keytab': No such file or directory
> could not set user   omi:omi  as owner of /etc/opt/omi/creds/omi.keytab
> 

I think the assumption by the /opt/omi/bin/support/ktstrip script that the system is running MIT Kerberos is possibly to blame here.  My reasoning follows.

Reading through /opt/omi/bin/support/ktstrip, it appears that it's trying to do the equivalent of the following command:

`echo -e '/etc/krb5.keytab\nlist\n' |  ktutil`

which implies that ktutil has an interactive mode, but it doesn't. It only accepts command line arguments.  The correct command should be:

`ktutil -k /etc/krb5.keytab list`

It's possible that not only the command format is different, but the output is different as well, but I didn't install MIT Kerberos to determine if that's the case or not.

**Comment by JumpingYang001** [comment]
looks like inconsistent command between Heimdal Kerberos and MIT Kerberos, I will check it today.

**Comment by JumpingYang001** [comment]
obviously, omi only support MIT Kerberos on Linux at present:
**Heimadal Kerberos:** https://www.systutorials.com/docs/linux/man/8-heimdal-ktutil/
**MIT Kerberos:** https://web.mit.edu/kerberos/krb5-1.12/doc/admin/admin_commands/ktutil.html

**Comment by JumpingYang001** [comment]
ktutil is same name but different commands on Heimadal Kerberos and MIT Kerberos:
**Heimadal Kerberos:** add, change, copy, get, list, remove, rename, purge .
**MIT Kerberos:** list, read_kt, read_st, write_kt, write_st, clear_list, delete_entry, add_entry, list_requests, quit .

**Comment by palladia** [comment]
Talked to Bruce, our Kerberos guy, and he said that MIT Kerberos is our only supported Kerberos.  But he also added that customers who wish to use Heimadal is welcome to tweak/play with the code to get it to work.  Our code was designed to be flexible with other implementations of Kerberos, he said.

**Comment by twstdpear** [comment]
@JumpingYang001 We weren't doing anything fancy - stock Azure image for 16.04, add and configure "heimdal-clients" which depends on all of the other components we use, as well as a few other related tools that aren't necessary for this discussion. 

I was just thinking more along the lines of a quick/simple check to ensure MIT Kerberos was installed before enabling the cron job to avoid the potential for bulk emails from Cron (e.g., the 115000 notifications a day from our 80ish systems).  Fortunately, I caught this early on before doing a widespread deployment, so only about 5 systems were affected before I started disabling the non-functional cron job.  Hopefully it won't get re-enabled when updates for omi come along.

**Comment by JumpingYang001** [comment]
@twstdpear each time OMS updates will re-install omi, and any new omi installation will set crontab, and the crontab only affetct when Kerberos enabling. I assume you are using OMS or other products?

I am thinking a fix, any suggestion?

**Comment by JumpingYang001** [comment]
After installing both Heimadal and MIT (I installed MIT first, then install heimdal-clients), here is what I get:
```
root@omi64-ubun16-03:~# ls -al /usr/bin/|grep ktutil                                                       
lrwxrwxrwx  1 root   root          24 Jun 15 17:16 ktutil -> /etc/alternatives/ktutil
-rwxr-xr-x  1 root   root       36216 Jul 13  2017 ktutil.heimdal
root@omi64-ubun16-03:~# ktutil
Usage: ktutil [-hv] [--version] [--help] [--keytab=keytab to operate on] [-k keytab to operate on] [--verbose]
   command
-k keytab to operate on, --keytab=keytab to operate on keytab
-v, --verbose                                          verbose
root@omi64-ubun16-03:~# 
```
