### ISSUE TITLE
Release libmi.so for musl runtime

### ISSUE THREAD

**Issue by adityapatwardhan** [Microsoft/omi#533]
libmi.so will be required by PowerShell on [Alpine Linux](https://www.alpinelinux.org/). 

For this, libmi.so should be released with support for `musl`

**Comment by JumpingYang001** [comment]
@edyoung Hi Edwin, do we have any plan for this? thanks

**Comment by JumpingYang001** [comment]
BTW, we are not only using gcc, we also use xlc_r on AIX, aCC on HP, clang on Mac, cc on Solaris. https://github.com/Microsoft/omi/blob/master/Unix/buildtool#L321

we also use g++, clang++, etc. https://github.com/Microsoft/omi/blob/master/Unix/buildtool#L618
from https://www.musl-libc.org/faq.html, it shows:
> Be aware that, "out of the box", the wrapper only supports C applications, not C++. This is because the C++ libraries and headers are missing from the musl include/library path. The existing libstdc++ is actually compatible with musl in most cases and could be used by copying it into the musl library path, but the C++ header files are usually not compatible. One option may be rebuilding just libstdc++ against musl; however, if C++ support is needed, it's recommended just to build a native toolchain targetting musl.

**Comment by JumpingYang001** [comment]
Since in offline discussion, it will not be supported, just close it. If it will be supported in the future, then let's re-open it that time. thanks all!

Just pick up a try build musl libmi.so branch: https://github.com/Microsoft/omi/tree/jumping-musl
