### ISSUE TITLE
I got below crontab entry autogenerated on server hosted on Cloud.

### ISSUE THREAD

**Issue by vbajpai9** [Microsoft/omi#535]
I got below crontab entry autogenerated on server hosted on Cloud.

* * * * * [ -f /etc/krb5.keytab ] && [ \( ! -f /etc/opt/omi/creds/omi.keytab \)

I have Java application running on Server, I guess this is auto killing some java processes, but I have not create this crontab entry. Please help me to understand why this script is created automatically and if I delete this, with my application get affects??

**Comment by JumpingYang001** [comment]
@vbajpai9 this is omi script installed to crontab while installing omi.
I will not kill any process.
it is normal and will not affect anything if you don't have `/etc/krb5.keytab` file on box.

**Comment by JumpingYang001** [comment]
@vbajpai9 one possible thing is that you are using LAD(Linux Azure Diagnostic) or OMS or DSC. they all use omi at present.
DSC: https://github.com/Microsoft/PowerShell-DSC-for-Linux
OMS: https://github.com/Microsoft/OMS-Agent-for-Linux
LAD: https://docs.microsoft.com/en-us/azure/virtual-machines/extensions/diagnostics-linux

**Comment by JumpingYang001** [comment]
The crontab code is here: https://github.com/Microsoft/omi/blob/a0aa5e42fa4e632aa7d96afe07b7f8ff3b55ec53/Unix/scripts/config_keytab_update.sh#L39

It was some problems before, but it should be fine since omi v1.4.2-3.

BTW, It will not kill any process.

**Comment by JumpingYang001** [comment]
omi will not kill any process and the cron log shows normal, so just close it, thanks.

**Comment by vbajpai9** [comment]
We have tried to install OMI version on Production server. We get below error, please check this ASAP.
![1](https://user-images.githubusercontent.com/16671257/42510066-608d92f0-846b-11e8-8b03-5b87621a07d3.PNG)
![2](https://user-images.githubusercontent.com/16671257/42510067-60c5d4e4-846b-11e8-90bb-7e075549ea9d.PNG)

**Comment by JumpingYang001** [comment]
@vbajpai9 , you were installed incorrect openssl deb package.
please run `openssl version` to check your openssl version, 0.9.8 pick 098 deb, 1.0.0 pick 100 deb, 1.1.0 pick 110 deb.

**Comment by JumpingYang001** [comment]
you are 1.0.1f openssl version, you need to install 100.unlinux.x64.deb instead of 098.unlinux.x64.deb

**Comment by vbajpai9** [comment]
Please share link to download the required package. We are not getting required package to install 100.unlinux.x64.deb

Please suggest as soon as possible.

**Comment by vbajpai9** [comment]
Please call me on below Number when you are online.
 +91 8127240240

We have to resolve this issue as soon as possible.

**Comment by vbajpai9** [comment]
Hi Jumping,

Please update. We are not getting package suggest by you. Please share link to download required package.

**Comment by JumpingYang001** [comment]
we are not in same time zone. I'm UTC+8.
here is link: https://github.com/Microsoft/omi/releases/download/v1.4.2-3/omi-1.4.2-3.ssl_100.ulinux.x64.deb
