### ISSUE TITLE
omiserver crashes with "Socket connect() failed"

### ISSUE THREAD

**Issue by jwueste** [Microsoft/omi#536]
When quering omiserver with cli I get an error "MI_RESULT_FAILED"
`/opt/omi/bin/omicli noop
/opt/omi/bin/omicli: result: MI_RESULT_FAILED
`
It seems as if omiserver is restarting every few seconds.

Version of OMI:
```
/opt/omi/bin/omiserver 
/opt/omi/bin/omiserver: OMI-1.4.2-2 - Mon Mar 19 10:19:49 PDT 2018

```
Errors in /var/opt/omi/log/omiserver.log (repeting every cli request):
```
2018/07/03 09:50:47 [78193,78193] INFO: null(0): EventId=40032 Priority=INFO Selector_AddHandler: selector=0x5dfda8, handler=0x131cb40, name=BINARY_SERVER_CONNECTION
2018/07/03 09:50:47 [78193,78193] INFO: null(0): EventId=40011 Priority=INFO (E)done with receiving msg(0x132d278:15:BinProtocolNotification:0)
2018/07/03 09:50:47 [78193,78193] ERROR: null(0): EventId=20129 Priority=ERROR Socket connect() failed, /etc/opt/omi/conf/sockets/omi_lEOfQW9xv, error 13
2018/07/03 09:50:47 [78193,78193] ERROR: null(0): EventId=20125 Priority=ERROR (E)Socket connect failed, locator /etc/opt/omi/conf/sockets/omi_lEOfQW9xv
2018/07/03 09:50:47 [78193,78193] ERROR: null(0): EventId=20141 Priority=ERROR Failed to create new server connection
2018/07/03 09:50:47 [78193,78193] INFO: null(0): EventId=40012 Priority=INFO (E)Socket: 0x131cb40, closing connection (mask 2)
2018/07/03 09:50:47 [78193,78193] INFO: null(0): EventId=40033 Priority=INFO Selector_RemoveHandler: selector=0x5dfda8, handler=0x131cb40, name=BINARY_SERVER_CONNECTION

```

**Comment by JumpingYang001** [comment]
it is a bug fixed in below 2 release (we still doesn't signoff with binaries, it will be available after all related teams all signoff.)
https://github.com/Microsoft/omi/releases/tag/v1.4.2-4
https://github.com/Microsoft/omi/releases/tag/v1.4.3

Work around at present:
```
sudo chown omi:omi /etc/opt/omi/conf/sockets
sudo /opt/omi/bin/service_control restart
```

**Comment by JumpingYang001** [comment]
Let me clarify the reason why this happen, LAD extension use remove mode to uninstall OMS, in this mode, it will not purge the folder `/etc/opt/omi/conf/sockets` which was set by omiserver process, and its owner was omi:omi was involved in non-root feature design, a new OMI installation will not set the permission again for the folder, then omiengine can't read the folder cause the error. (current fix is to set the folder permission to omi:omi after omi installation.)

1. If LAD use purge mode, then all folders will be deleted then won't have this issue.
2. If omi uninstallation purge all folders then won't have this issue, too.

Anyway, above 2 points don't change now, and we used another way to fix the issue in OMI installation script in new release v1.4.2-4 and v1.4.3.

**Comment by palladia** [comment]
This is fixed in latest OMS and OMI releases.
