### ISSUE TITLE
Page 1 missing from https://github.com/Microsoft/omi/blob/master/Unix/doc/omi/omi.pdf

### ISSUE THREAD

**Issue by dotmh** [Microsoft/omi#54]
The Page 1 is missing from the PDF that explains what OMI is.

**Comment by niroyb** [comment]
I see it, can you post a screenshot of the issue?

---
![image](https://cloud.githubusercontent.com/assets/1450009/17981736/c2c11a46-6ab9-11e6-93e6-7538c38c2eb5.png)

**Comment by niroyb** [comment]
Closing for no repro
