### ISSUE TITLE
omiagent uses 100% cpu, yet again

### ISSUE THREAD

**Issue by mikhail-manuilov** [Microsoft/omi#541]
Using ubuntu server 16.04 Azure

```
dpkg -l | egrep "^.*  omi"
ii  omi                                 1.4.2.2                                    amd64        Open Management Infrastructure
```
```/opt/omi/bin/omiagent --version
/opt/omi/bin/omiagent: OMI-1.4.2-2 - Mon Mar 19 10:19:49 PDT 2018
```
```
sudo apt-get upgrade omi
Reading package lists... Done
Building dependency tree       
Reading state information... Done
omi is already the newest version (1.4.2.2).
```

```
top - 13:38:26 up 14 days, 20:35,  3 users,  load average: 2.27, 2.15, 2.06
Tasks: 210 total,   2 running, 154 sleeping,   0 stopped,   2 zombie
%Cpu(s): 56.7 us,  5.3 sy,  0.0 ni, 37.9 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem :  8145492 total,   896288 free,  1591296 used,  5657908 buff/cache
KiB Swap:        0 total,        0 free,        0 used.  5655520 avail Mem 

   PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                               
 46987 root      20   0  375304  11516   8756 R  98.3  0.1 935:19.56 omiagent   ```

```  sudo gcore -o zalupa 46987
[New LWP 47007]
[New LWP 47009]
[New LWP 47010]
[New LWP 47011]
[New LWP 47114]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
_int_free (av=0x7f60797bcb20 <main_arena>, p=0xc2cc90, have_lock=0) at malloc.c:3924
3924	malloc.c: No such file or directory.
warning: target file /proc/46987/cmdline contained unexpected null characters
Saved corefile zalupa.46987```

```$ ps aux | grep 'Z'
USER        PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
omsagent   1864  0.0  0.0      0     0 ?        Z    Jun25   0:00 [sh] <defunct>
omsagent   1866  0.0  0.0      0     0 ?        Z    Jun25   0:00 [sh] <defunct>
```

Looks like it's better to completely unistall omi to sleep well

**Comment by JumpingYang001** [comment]
@mikhail-manuilov omiagent is provider code, we have many providers, like scx,dsc,omsconfig,docker,mysql,apache,etc.

you can `gdb zalupa.46987` and run `info sharedlibrary`, it will show which provider, so we can transfer the issue to the specified provider team, thanks.

**Comment by JumpingYang001** [comment]
try `gdb /opt/omi/bin/omiagent zalupa.46987`
then `info sharedlibrary`

**Comment by mikhail-manuilov** [comment]
$ gdb /opt/omi/bin/omiagent zalupa.46987
GNU gdb (Ubuntu 7.11.1-0ubuntu1~16.5) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
/opt/omi/bin/omiagent: No such file or directory.
[New LWP 46987]
[New LWP 47007]
[New LWP 47009]
[New LWP 47010]
[New LWP 47011]
[New LWP 47114]
Core was generated by `/opt/omi/bin/omiagent'.
#0  0x00007f6079477df0 in ?? ()
[Current thread is 1 (LWP 46987)]
(gdb) info sharedlibrary
No shared libraries loaded at this time.
(gdb) 

(gdb) 
```

I've deleted it, how to reinstall?

```sudo apt install omi
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package omi is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'omi' has no installation candidate
```

**Comment by JumpingYang001** [comment]
since I don't know your openssl version, possible https://github.com/Microsoft/omi/releases/download/v1.4.2-2/omi-1.4.2-2.ssl_100.ulinux.x64.deb or https://github.com/Microsoft/omi/releases/download/v1.4.2-2/omi-1.4.2-2.ssl_110.ulinux.x64.deb, depends on your openssl version.

**Comment by JumpingYang001** [comment]
@mikhail-manuilov , any updates? still meet the issue? If not, I want to close it, thanks.

**Comment by JumpingYang001** [comment]
No response and just close it, thanks.
