### ISSUE TITLE
httpClient: Log a timestamp in omiclient-send.trc to support correlating with omiclient-recv.trc

### ISSUE THREAD

**Issue by dantraMSFT** [Microsoft/omi#544]
When debug logging of http traffic, responses include a GMT date stamp in the header but the requests do not. This makes it difficult to correlate requests with responses.

The fix would be to log a GMT timestamp in the block where the the client headers are logged; something like the following:

if (FORCE_TRACING || handler->enableTracing)
{
     // log  a timestamp before the client headers
     char timestamp[40];
     GetUtcTimeStamp(timestamp, 40);
     _WriteTraceFile(ID_HTTPCLIENTSENDTRACEFILE, timestamp, Strlen(timestamp);

    _WriteTraceFile(ID_HTTPCLIENTSENDTRACEFILE, buf, buf_size);
}

**Comment by JumpingYang001** [comment]
looks like it doesn't recv file or send file special, I found timestamp here: https://github.com/Microsoft/omi/blob/master/Unix/base/log.c#L204

**Comment by dantraMSFT** [comment]
@JumpingYang001: I'm not sure what you're referring to.

The current httpclient code doesn't log with timestamps for http debug tracing.  It's not an issue for responses since it contains a Date header.  Requests do not.

This is what I've been using to debug session cookie issues.
https://github.com/Microsoft/omi/commit/7fdde2eec4f9aefeeb8210c52dcd3bc090417229

It probably makes sense to also log the generated session id to improve correlation.

**Comment by JumpingYang001** [comment]
ok, looks like my provided link is about normal logging, and trace logging is in another function: https://github.com/Microsoft/omi/blob/ba1958ec946fc7705550d4d78796d5719e54c2cd/Unix/http/http.c#L398.  BTW, I don't see any log timestamp in response trace log code.  will check it today.

**Comment by dantraMSFT** [comment]
The response headers have a Date header so I didn't need to log one.  It makes sense though to log a session id/timestamp logged for each header set.
