### ISSUE TITLE
OMIagent crashes sporadically when starting DSC

### ISSUE THREAD

**Issue by mgrudl** [Microsoft/omi#546]
### OMI Version:
/opt/omi/bin/omiserver: OMI-1.4.2-2 - Mon Mar 19 10:19:49 PDT 2018
### OMI Logfiles:
[omilog.zip](https://github.com/Microsoft/omi/files/2205065/omilog.zip)

### Provider Registration Name:
/etc/opt/omi/conf/omiregister/root-Microsoft-Windows-DesiredStateConfiguration/dsccore.reg

### Description
OMIagent sporadically crahes when retrieving request from DSC module.
We have this issue on a high amount of Debian based switches.

The issue occurs nearly daily between 1 and 5 times. (without a temporal relationship)

### logs from working request: 
2018/07/18 08:30:01 [21708,21708] INFO: null(0): EventId=40032 Priority=INFO Selector_AddHandler: selector=0x5bb558, handler=0x14c3720, name=BINARY_FROM_SOCKET
2018/07/18 08:30:01 [21708,21708] INFO: null(0): EventId=40032 Priority=INFO Selector_AddHandler: selector=0x5bb558, handler=0x5bb4c0, name=PROVMGR_TIMEOUT_MANAGER
2018/07/18 08:30:01 [21708,21708] INFO: null(0): EventId=40003 Priority=INFO agent started; fd 9
2018/07/18 08:30:01 [21708,21708] INFO: null(0): EventId=40011 Priority=INFO (U)done with receiving msg(0x14c4228:15:BinProtocolNotification:3f)
2018/07/18 08:30:01 [21708,21708] INFO: null(0): EventId=40011 Priority=INFO (U)done with receiving msg(0x14c4db8:4103:InvokeReq:40)
2018/07/18 08:30:01 [21708,21708] INFO: null(0): EventId=40039 Priority=INFO New request received: command=(InvokeReq), namespace=(root/Microsoft/Windows/DesiredStateConfiguration), class=(MSFT_DSCLocalConfigurationManager)
2018/07/18 08:32:31 [21708,21708] INFO: null(0): EventId=40001 Priority=INFO sending 'agent-idle' notification to the server
2018/07/18 08:32:31 [21708,21708] INFO: null(0): EventId=40028 Priority=INFO (U)Socket: 0x14c3720, Connection Closed while reading header

2018/07/18 08:32:31 [21708,21708] INFO: null(0): EventId=40012 Priority=INFO (U)Socket: 0x14c3720, closing connection (mask 2)
2018/07/18 08:32:31 [21708,21708] INFO: null(0): EventId=40033 Priority=INFO Selector_RemoveHandler: selector=0x5bb558, handler=0x14c3720, name=BINARY_FROM_SOCKET
2018/07/18 08:32:31 [21708,21708] INFO: null(0): EventId=40000 Priority=INFO disconnected form server; exiting
2018/07/18 08:32:31 [21708,21708] INFO: null(0): EventId=40034 Priority=INFO Selector_RemoveAllHandlers: selector=0x5bb558, handler=0x5bb4c0, name=PROVMGR_TIMEOUT_MANAGER
2018/07/18 08:32:31 [21708,21708] INFO: null(0): EventId=40001 Priority=INFO sending 'agent-idle' notification to the Server

### Logs from failed request:
2018/07/18 08:00:01 [18073,18073] INFO: null(0): EventId=40032 Priority=INFO Selector_AddHandler: selector=0x5bb558, handler=0x24fe720, name=BINARY_FROM_SOCKET
2018/07/18 08:00:01 [18073,18073] INFO: null(0): EventId=40032 Priority=INFO Selector_AddHandler: selector=0x5bb558, handler=0x5bb4c0, name=PROVMGR_TIMEOUT_MANAGER
2018/07/18 08:00:01 [18073,18073] INFO: null(0): EventId=40003 Priority=INFO agent started; fd 9
2018/07/18 08:00:01 [18073,18073] INFO: null(0): EventId=40011 Priority=INFO (U)done with receiving msg(0x24ff228:15:BinProtocolNotification:3d)
2018/07/18 08:00:01 [18073,18073] INFO: null(0): EventId=40011 Priority=INFO (U)done with receiving msg(0x24ffdb8:4103:InvokeReq:3e)
2018/07/18 08:00:01 [18073,18073] INFO: null(0): EventId=40039 Priority=INFO New request received: command=(InvokeReq), namespace=(root/Microsoft/Windows/DesiredStateConfiguration), class=(MSFT_DSCLocalConfigurationManager)

**Comment by JumpingYang001** [comment]
@mgrudl ,  omiagent runs provider code, logs shows it runs dsc provider, you need to log issue on dsc: https://github.com/Microsoft/PowerShell-DSC-for-Linux

omiagent is not omi issue, so I just close it, thanks.
