### ISSUE TITLE
Please publish the scx and omi packages on Microsoft repo for Ubuntu 18.04

### ISSUE THREAD

**Issue by canfikret** [Microsoft/omi#556]
Could you put the scx-1.6.3-659.universal.x64.deb and omi-1.4.2-3.ulinux.x64.deb on http://packages.microsoft.com/ubuntu/18.04/

Preferably with OpenSsl version 1.1.

Thanks,
Fikret.

**Comment by JumpingYang001** [comment]
@palladia @sarojcare, I didn't publish repo packages before, maybe you can help this when free? thanks.

**Comment by sarojcare** [comment]
Jumping will look into it.

**Comment by palladia** [comment]
Actually, since the request involves both scx and omi, Saroj, could you look into doing this?  I will send you instructions on how to do this via a separate email.

**Comment by sarojcare** [comment]
Package already pushed. Closing the case.
