### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [Microsoft/omi#562]
[An extra null pointer check is not needed in functions](https://stackoverflow.com/questions/18775608/free-a-null-pointer-anyway-or-check-first "Free a null pointer anyway or check first?") like the following.
- [_Delete](https://github.com/Microsoft/omi/blob/edbe231042173018c52903e4170dd8b782fc4f8a/Unix/tests/codec/mof/blue/class.c#L390 "_Delete function")
- [LifecycleIndicationItem_New](https://github.com/Microsoft/omi/blob/d2285767491fccefe3a4e723f7e1954e684f6063/Unix/samples/Providers/Indication/Lifecycle/XYZ_ComputerSystem.c#L133 "LifecycleIndicationItem_New function")
- [XmlDeserializer_DeserializeClass](https://github.com/Microsoft/omi/blob/edbe231042173018c52903e4170dd8b782fc4f8a/Unix/xmlserializer/xmldeserializer.c#L213 "XmlDeserializer_DeserializeClass")

**Comment by JumpingYang001** [comment]
check null just ensure we don't make crash, since omi is multi-thread programs, you cannot be sure if it is possible which will be freed first. anyway, thanks for filing it!

we don't want to fix it , thanks.

**Comment by elfring** [comment]
I wonder that you do not want to avoid the mentioned redundant condition checks so far.

**Comment by JumpingYang001** [comment]
thanks for picking it up!  avoid redundant condition is a good thing, we'll consider to do it in the future but we don't want to fix it at present, also that depends on plan  and schedule.


Below 2 examples are in tests and samples:
•_Delete
•LifecycleIndicationItem_New

**Comment by elfring** [comment]
I am still curious then if another software developer (besides me) can get into the mood to apply a corresponding update suggestion which could be generated by [the software “Coccinelle”](http://coccinelle.lip6.fr/ "Source code transformation with Coccinelle") (also with the help of a variant from the following script).

```
@Remove_unnecessary_pointer_checks@
expression x;
@@
-if (\(x != 0 \| x != NULL\))
    free(x);
```
