### ISSUE TITLE
Trying to copy file from Windows to Linux hangs

### ISSUE THREAD

**Issue by iga1976** [Microsoft/omi#567]
Installed on Suse 12 with SP2 the following
powershell-6.0.4-1.rhel.7.x86_64
omi-1.4.3-1.x86_64   for the installed SSL 1.0.2
omi-psrp-server-1.4.2-2.x86_64

I am trying to run on Windows the following but Copy-Item hangs:

$SecurePass = ConvertTo-SecureString -String "root_password" -AsPlainText -Force
$Cred = New-Object System.Management.Automation.PSCredential "root" , $SecurePass 
$Opt = New-PsSessionOption -SkipCACheck -SkipCNCheck -SkipRevocationCheck 
$Session = New-PsSession -Credential $Cred -ComputerName 11.0.0.21 -Port 5986 -Authentication Basic -SessionOption $Opt -UseSSL
Copy-Item -Path 'C:\Downloads\App-LinuxX86.tar' -Destination /home/user/ -ToSession $Session

Note: 11.0.0.21 is the Linux IP address.
Note 2: Enter-PSSession $Session works. Remote Powershell was configured OK.

omiserver.log says:
2018/08/27 16:59:55 [21765,21765] WARNING: null(0): EventId=30161 Priority=WARNING WsmanConnection: 0x2503e50 _ProcessInstanceConnectionData: expired
2018/08/27 16:59:55 [21765,21765] WARNING: null(0): EventId=30162 Priority=WARNING WsmanConnection: 0x2503e50 _ProcessResultConnectionData: no request
2018/08/27 16:59:55 [21765,21765] WARNING: null(0): EventId=30119 Priority=WARNING ssl-read: unexpected sys error 104

2018/08/27 16:59:55 [21765,21765] WARNING: null(0): EventId=30161 Priority=WARNING WsmanConnection: 0x2503e90 _ProcessInstanceConnectionData: expired
2018/08/27 16:59:55 [21765,21765] WARNING: null(0): EventId=30162 Priority=WARNING WsmanConnection: 0x2503e90 _ProcessResultConnectionData: no request
2018/08/27 16:59:58 [21765,21765] WARNING: null(0): EventId=30119 Priority=WARNING ssl-read: unexpected sys error 104

2018/08/27 16:59:58 [21765,21765] WARNING: null(0): EventId=30161 Priority=WARNING WsmanConnection: 0x2513110 _ProcessInstanceConnectionData: expired
2018/08/27 16:59:58 [21765,21765] WARNING: null(0): EventId=30162 Priority=WARNING WsmanConnection: 0x2513110 _ProcessResultConnectionData: no request

shellserver.log says
2018/08/27 16:37:14 [21164,21164] ERROR: null(0): Shell_Load PostResult 0x7ffd6cf8af80, 0
2018/08/27 16:44:40 [21441,21441] ERROR: null(0): Shell_Load PostResult 0x7ffcaa0d3400, 0
2018/08/27 16:51:14 [21795,21795] ERROR: null(0): Shell_Load PostResult 0x7ffc43f32410, 0

**Comment by JumpingYang001** [comment]
it seems psrp issue, could you file the bug on https://github.com/powershell/psl-omi-provider/issues ? thank you!

**Comment by iga1976** [comment]
https://github.com/PowerShell/psl-omi-provider/issues/125
