### ISSUE TITLE
Couldn't install omi successfully in Windows 10 Subsystem for Linux(WSL)

### ISSUE THREAD

**Issue by PajonYang** [Microsoft/omi#568]
Operating System: Windows 10 Bash (18.04.1 LTS)
omi build version: 1.5.0-0

An message "System has not been booted with systemd as init system (PID 1). Can't operate." appears when installing omi package.

![image](https://user-images.githubusercontent.com/28045728/44706814-6be92e80-aad5-11e8-8c65-e93b83027212.png)

**Comment by JumpingYang001** [comment]
win 10 bash is very similar with docker environment for omi, so I suggest to work around with below steps:
```
touch /etc/.omi_disable_service_control
```
Then install omi.

**Comment by PajonYang** [comment]
@JumpingYang001  Thanks for help, it is work well. 
Below is my result:
root@ostc-pajon:/mnt/c/Users/v-peiy# touch /etc/.omi_disable_service_control
root@ostc-pajon:/mnt/c/Users/v-peiy# dpkg -i omi-1.5.0-0.ssl_110.ulinux.x64.deb
(Reading database ... 28530 files and directories currently installed.)
Preparing to unpack omi-1.5.0-0.ssl_110.ulinux.x64.deb ...
Unpacking omi (1.5.0.0) over (1.5.0.0) ...
Setting up omi (1.5.0.0) ...

************************************************************
* Warning: The certificate and keyfile were not generated  *
* since they already exist.                                *
************************************************************
2018-08-28 15:27:55 : Crontab no longer configured to update omi keytab.
2018-08-28 15:27:55 : Crontab configured to update omi keytab automatically
Processing triggers for ureadahead (0.100.0-20) ...
Processing triggers for systemd (237-3ubuntu10.3) ...
root@ostc-pajon:/mnt/c/Users/v-peiy# ps -ef|grep omi
root      1614     1  0 15:27 ?        00:00:00 /opt/omi/bin/omiserver -d
omi       1615  1614  0 15:27 ?        00:00:00 /opt/omi/bin/omiengine -d --logfilefd 3 --socketpair 9
root      1628  1329  3 15:28 tty1     00:00:00 grep --color=auto omi
root@ostc-pajon:/mnt/c/Users/v-peiy# /opt/omi/bin/omicli id
instance of OMI_Identify
{
    [Key] InstanceID=2FDB5542-5896-45D5-9BE9-DC04430AAABE
    …    
}
root@ostc-pajon:/mnt/c/Users/v-peiy# /opt/omi/bin/service_control restart
/opt/omi/bin/omiserver: stopped server
root@ostc-pajon:/mnt/c/Users/v-peiy# ps -ef|grep omi
root      1649     1  0 15:29 ?        00:00:00 /opt/omi/bin/omiserver -d
omi       1650  1649  0 15:29 ?        00:00:00 /opt/omi/bin/omiengine -d --logfilefd 3 --socketpair 9
root      1653  1649  0 15:29 ?        00:00:00 /opt/omi/bin/omiagent 9 10 --destdir / --providerdir /opt/omi/lib --loglevel WARNING
root      1655  1329  0 15:29 tty1     00:00:00 grep --color=auto omi
root@ostc-pajon:/mnt/c/Users/v-peiy# /opt/omi/bin/omicli id
instance of OMI_Identify
{
    [Key] InstanceID=2FDB5542-5896-45D5-9BE9-DC04430AAABE
    …
}

**Comment by JumpingYang001** [comment]
OK, I think I can close the issue with the provided workaround.
