### ISSUE TITLE
OMI cron with Kerberos creating boot issues - 1 hour to reboot

### ISSUE THREAD

**Issue by superudu** [Microsoft/omi#570]
I have this issue on many of my Azure VMs: rebooting them takes a really long time, an hour or more.
What I have found is that the OMI cron fails to remove the temporary files and this makes my /tmp directory to have up to 1 million files in it, and adding 3 new files every minute:

```
tmp.001gqDWeTO
tmp.003kaLPkdz
tmp.005lyx3CFp
```

The cron exit code is 0, but a fake 0 because of that "OR true" option:

```
# [ -f /etc/krb5.keytab ] && [ \( ! -f /etc/opt/omi/creds/omi.keytab \) -o \( /etc/krb5.keytab -nt /etc/opt/omi/creds/omi.keytab \) ] && /opt/omi/bin/support/ktstrip /etc/krb5.keytab /etc/opt/omi/creds/omi.keytab >/dev/null 2>&1 || true

# echo $?
0
```

However this part of the cron command errors out:

```
# /opt/omi/bin/support/ktstrip /etc/krb5.keytab /etc/opt/omi/creds/omi.keytab
src kt = /etc/krb5.keytab
Creating /etc/opt/omi/creds/omi.keytab
ktutil:  read_kt /etc/krb5.keytab 
ktutil:  delete_entry 1
ktutil:  write_kt /tmp/tmp.kt
ktutil:  Move /tmp/tmp.kt to /etc/opt/omi/creds/omi.keytab
mv: cannot stat '/tmp/tmp.kt': No such file or directory
chown: cannot access '/etc/opt/omi/creds/omi.keytab': No such file or directory
could not set user   omi:omi  as owner of /etc/opt/omi/creds/omi.keytab
```

Having so many files in /tmp is a problem at reboot time. It takes a really long time to remove them all.

Since this cron job is somehow useless I've tried to remove it, but something adds it back after reboot. Could be the OMI service restart.

My VM has the /etc/krb5.keytab file. SSH login is managed by central AD and some Windows AD groups per sshd configuration.

What is the intended purpose of this cron? Since it never worked I probably do not miss it. But I would like to know.
Can this cron be either removed or at least fixed so it will not leave behind all those tmp files? #425

**Comment by JumpingYang001** [comment]
@superudu  ,the cron was used by omi to support Kerberos authentication feature with non-root feature(run omiengine in non-root account) . So if you don't use omi's Kerberos authentication, then you are safe to remove the crontab entry.

For the ktstrip error, I am investigating.

**Comment by JumpingYang001** [comment]
@superudu , we use [mktemp](https://github.com/Microsoft/omi/blob/master/Unix/tools/ktstrip#L49) in our script, and the mktemp is a system utility to create a tmp file: https://www.gnu.org/software/autogen/mktemp.html, looks like your system doesn't remove it, it should be managed by `cat /etc/cron.daily/tmpwatch` and 
```
[jumping@osd64-ct5-01 ~]$ man tmpwatch
TMPWATCH(8)              System Administratorâs Manual             TMPWATCH(8)

NAME
       tmpwatch - removes files which havenât been accessed for a period of time
...
```

**Comment by JumpingYang001** [comment]
@superudu , sure, we'll fix it, but OMS/OMI push to Azure seems need several month according to previous releasing experience.

For rebooting the vm will make the cron back, I am sure OMI doesn't install cron every reboot, omi only install the cronjob when installing omi, so it is possible that your omi was re-installed by OMS upgrading after or before reboot. could you try it again to confirm that the cron really come back again for rebooting but not the re-install omi by oms? thanks.

**Comment by superudu** [comment]
I can confirm that just rebooting will not reinstall the OMI cron. It could be the omsagent upgrade that does that.
So I should probably prevent this package from upgrading. And also remove the cron.

I will wait for that fix, even if pushing it to Azure takes months. Thanks.

**Comment by JumpingYang001** [comment]
thanks for confirming! we'll fix the error and the temp files.

**Comment by JumpingYang001** [comment]
fixes is in master branch and it will publish when next release, thanks.
