### ISSUE TITLE
OmiAgent with excessive memory and cpu usage

### ISSUE THREAD

**Issue by fracklen** [Microsoft/omi#597]
I have ~25 RHEL VMs running in Azure. After they've been running for about 10 days, the `omiagent` consumes all available cpus and way too much memory.

The VMs are completely bogged down.

![screen shot 2018-11-01 at 10 19 11](https://user-images.githubusercontent.com/2706577/47848650-4a573c80-ddcf-11e8-8305-3f81017bc719.png)
![screen shot 2018-11-01 at 10 18 13](https://user-images.githubusercontent.com/2706577/47848684-6f4baf80-ddcf-11e8-8fb1-7b71e17459b9.png)

Details:

On the VMs with less than 4GB memory, the omiagent lingers between 50% and 100% memory usage.
It seems that the agent doesn't go above 4GB memory usage.
While the memory usage goes down from 100% to 50%, there is 100% cpu usage on one core.

The problem is less "critical" on larger VMs. On our elasticsearch hosts with 64GB ram and 8 cores, the behaviour is the same, but the consequences are less noticable.

Help?

What other details can I provide?

**Comment by JumpingYang001** [comment]
omiagent is omi providers, there are many providers, to know which provider possibly run `strace -p 31227` in your screen picture, then we can provide the specified provider product link to  you, then you can go there, thanks.
providers are other products.

**Comment by JumpingYang001** [comment]
if above command don't show the loaded libs, then we should try `pmap 31227` or `strace -S -p 31227` or `ltrace -S 31227`.

**Comment by JumpingYang001** [comment]
@fracklen any updates for this? have you got right provider team to track your issue?

**Comment by JumpingYang001** [comment]
Since no responsive for a long time, just close this issue, thanks.
Please create ticket on Azure if you meet same issue, thanks.

**Comment by abenbachir** [comment]
Hi, please follow resolution steps in this documentation: https://github.com/microsoft/OMS-Agent-for-Linux/blob/master/docs/Troubleshooting.md#i-see-omiagent-using-100-cpu
