### ISSUE TITLE
AIX login.cfg: /bin/false appended to end of all lines

### ISSUE THREAD

**Issue by gd-ksc** [Microsoft/omi#598]
The following appends "/bin/false" to the end of each line in AIX /etc/security/login.cfg:

https://github.com/Microsoft/omi/blob/232a38192e16ca724f3f3438419f8ccaead10f34/Unix/installbuilder/datafiles/AIX.data#L52

Perhaps, match on "shells =" line:

> sed '/shells =/s?$?,/bin/false?' /etc/security/login.cfg > /tmp/login.cfg

**Comment by JumpingYang001** [comment]
I will check it today, thanks for filing!

**Comment by JumpingYang001** [comment]
@gd-ksc , good catch! I will new a PR to fix it.
