### ISSUE TITLE
1.6.0 release date?

### ISSUE THREAD

**Issue by Iristyle** [Microsoft/omi#600]
The last release was in late July, over three months ago. I see that 1.6.0 has been tagged, but corresponding binaries for various platforms have not been added to the releases pages at https://github.com/Microsoft/omi/releases

Are there any plans to produce those binaries soon?

Thanks!

**Comment by JumpingYang001** [comment]
It will come soon, after all partner teams signed off the binaries will be published, thanks.

**Comment by Iristyle** [comment]
@JumpingYang001 just checking on the status here? Working on a demo for a webinar in less than 2 weeks and was hoping to use published binaries.


Thanks!

**Comment by JumpingYang001** [comment]
@Iristyle  we still have 1 team didn't feedback, I am tracking with them, will update here if all signoff, thanks.

**Comment by Iristyle** [comment]
Ok thanks for the update. Fingers crossed as our webinar is on Tuesday.

**Comment by Iristyle** [comment]
Looks like this can be closed now - thanks!

**Comment by JumpingYang001** [comment]
ok, thanks.
