### ISSUE TITLE
New-Cimsession - The SSL certificate is expired

### ISSUE THREAD

**Issue by kunaludapi** [Microsoft/omi#602]
Even after install centos 7 from scratch all the time I am getting error, when connecting from windows system.

> New-CimSession : The server certificate on the destination computer (ubuntu01:5986) has the following errors:
> **The SSL certificate is expired.**
> At line:1 char:13
>  $Sesssion = New-CimSession -Credential:$credential -ComputerName:$Nod ...
>              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>      CategoryInfo          : NotSpecified: (:) [New-CimSession], CimException
>      FullyQualifiedErrorId : HRESULT 0x80072f8f,Microsoft.Management.Infrastructure.CimCmdlets.NewCimSessionCommand
>      PSComputerName        : ubuntu01
 
![error 2018-11-18_19-18-41](https://user-images.githubusercontent.com/10530852/48674315-c643d980-eb70-11e8-9b74-bd7733dec74a.png)

**Below are the information and details on my centos system.**

powershell-6.1.1-1.rhel.7.x86_64
omi-1.4.2-5.ssl_100.ulinux.x64.rpm
dsc-1.1.1-294.ssl_100.x64.rpm

[root@ubuntu01 ~]$  **openssl version**
OpenSSL 1.0.2k-fips  26 Jan 2017

[root@ubuntu01 ~]$  **openssl s_client -servername ubuntu -connect ubuntu01:5986 2>/dev/null | openssl x509 -noout -dates**
notBefore=Nov 18 17:59:41 2018 GMT
notAfter=Nov 15 17:59:41 2028 GMT

[root@ubuntu01 ~]$  **sudo /opt/omi/bin/omicli ei root/omi OMI_Identify**
instance of OMI_Identify
{
    [Key] InstanceID=2FDB5542-5896-45D5-9BE9-DC04430AAABE
    SystemName=ubuntu01
    ProductName=OMI
    ProductVendor=Microsoft
    ProductVersionMajor=1
    ProductVersionMinor=4
    ProductVersionRevision=2
    ProductVersionString=1.4.2-5
    Platform=LINUX_X86_64_GNU
    OperatingSystem=LINUX
    Architecture=X86_64
    Compiler=GNU
    ConfigPrefix=GNU
    ConfigLibDir=/opt/omi/lib
    ConfigBinDir=/opt/omi/bin
    ConfigIncludeDir=/opt/omi/include
    ConfigDataDir=/opt/omi/share
    ConfigLocalStateDir=/var/opt/omi
    ConfigSysConfDir=/etc/opt/omi/conf
    ConfigProviderDir=/etc/opt/omi/conf
    ConfigLogFile=/var/opt/omi/log/omiserver.log
    ConfigPIDFile=/var/opt/omi/run/omiserver.pid
    ConfigRegisterDir=/etc/opt/omi/conf/omiregister
    ConfigSchemaDir=/opt/omi/share/omischema
    ConfigNameSpaces={root-omi, root-Microsoft-DesiredStateConfiguration, root-Microsoft-Windows-DesiredStateConfiguration}
}

**There is no DSC.log generated.**

**Comment by JumpingYang001** [comment]
your message seems incorrect from powershell Linux command, "notBefore=Nov 18 17:59:41 2018 GMT notAfter=Nov 15 17:59:41 2028 GMT" is NOT expired. so it seems an incorrect/unmatch message from Windows powershell client command, @kunaludapi are you using native PowerShell command to issue the commands or PowerShell Core? you should file the issue on native PowerShell or PowerShell core.

**On omi side:**
omi server used self-signed certs by default.
There is a way to use your own ssl certs: 
1. generate your own valid ssl certs. 
2. modify omiserver.conf setting and ssl certs files permission according to https://github.com/Microsoft/omi/blob/master/Unix/installbuilder/conf/omiserver.conf#L47

If you are using DSC/PowerShell Linux, I think they might just export omiserver as the WSMan server for `New-CimSession` to query.

**Comment by JumpingYang001** [comment]
@kunaludapi better message from powershell windows client side should be like 'The SSL certificate is self-signed! For security reason, please replace them with CA signed certs.' like so.

And that message cannot control by omiserver, and omiserver cannot generate CA certs (that possibly should be generated by user or DSC/PowerShell, I am not sure.), so I close this issue, thanks.
