### ISSUE TITLE
Broken OMI 1.4.1.0 still installed on new deployments on Azure

### ISSUE THREAD

**Issue by directhex** [Microsoft/omi#608]
I created a brand new VM on Azure yesterday at around 4pm UTC-5. I enabled diagnostics (as I always do for mission critical VMs), and it installed OMI as part of that.

Apparently, in the final days of 2018, enabling diagnostics in Azure installs OMI 1.4.1.0, which is affected by this bug: https://github.com/Microsoft/omi/issues/425 which out of the box causes error messages to be sent to root@ _every 60 seconds_. My mail service has been disabled _again_.

What possible reason is there for Azure VMs to still deploy a known-defective version as standard?

**Comment by JumpingYang001** [comment]
@directhex I cannot answer the Azure deployment things, I suggest you to new an Azure ticket or ICM that might reach the suitable team to help you, thanks.

**Comment by JumpingYang001** [comment]
@directhex , please create a ticket on Azure according to https://docs.microsoft.com/en-us/azure/azure-supportability/how-to-create-azure-support-request, thanks.

Please let me know once you created it and got the suitable team to follow with your issue, thanks.

Please kindly let me know if you have any concern, thanks.

**Comment by JumpingYang001** [comment]
@directhex any updates? have you issue been fixed?

**Comment by directhex** [comment]
It's not "my" issue, it's an issue affecting all Linux-using customers on Azure. Which is... a whole bunch.

And submitting a support ticket so some v- in India can tell me to turn if off and on again is not a resolution.

The OMI team really has no idea which PM is responsible for the insertion of OMI into Azure's OMI-dependent functionality?

**Comment by JumpingYang001** [comment]
@directhex can you send me a test email? I can add you to LAD team, thanks.
my mail is v-zhenpy@microsoft.com

**Comment by directhex** [comment]
This is fixed in staging, and should be public fairly soon. Thanks to @JumpingYang001 for finding the right people to start the process of getting this fix out to customers.
