### ISSUE TITLE
MI_RESULT_FAILED occuring intermittently when using DSCForLinux

### ISSUE THREAD

**Issue by escogom** [Microsoft/omi#611]
Hello, here is the required information:
1) **Version**
./omiserver -v
./omiserver: OMI-1.6.0-0 - Tue Oct 16 09:54:51 PDT 2018

2) Related Provider: DSCforLinux extension for Azure
3) Logs: please find attached (with DEBUG logging level)
4) Replicating error: 
- Compile DSC powershell file to .MOF file
- Assign MOF file to my virtual machine in Azure 
-Trigger the DSC config check using python /opt/microsoft/dsc/Scripts/PerformRequiredConfigurationChecks.py
-NOTE: the first time I do this (and I purposely set my config to trigger the DSC SetScript), it **works** perfectly.
-However if I revert my server config back to trigger the DSC SetScript again (without generating a new MOF), and I rerun the config check again, I persistently get the same OMI error :(.

Additional Info: This is a SLES 12 SP3, non-production server.

[OMI_ee_issue.zip](https://github.com/Microsoft/omi/files/2753777/OMI_ee_issue.zip)

**Comment by JumpingYang001** [comment]
I am checking it, I don't have Azure box, can you send more detail about "-However if I revert my server config back to trigger the DSC SetScript again (without generating a new MOF), and I rerun the config check again, I persistently get the same OMI error :(.", especially what is your server config?
my email is v-zhenpy@microsoft.com, welcome to contact me using my mail, thanks.

**Comment by JumpingYang001** [comment]
@escogom  , I have checked your attached logs, no any omi error.
so please contact me with mail: v-zhenpy@microsoft.com, thanks.

**Comment by JumpingYang001** [comment]
no update for more than 2 weeks, and DSC things should file on https://github.com/Microsoft/PowerShell-DSC-for-Linux , thanks.
