### ISSUE TITLE
DSC Composite resource, nxScript fails if the OMID Service isn't running in interactive mode.

### ISSUE THREAD

**Issue by gesandovalr** [Microsoft/omi#621]
Hi, I'm building a sample DSC composite resource using along with an Automation Account for a RHEL VM a weird thing that is happening when the omi service is running as a background process the configuration fails, but if I stop the OMID service and started in interactive mode /opt/omi/bin/ ./omiserver. the configuration applies.

**Comment by JumpingYang001** [comment]
@gesandovalr for DSC things, please file on https://github.com/Microsoft/PowerShell-DSC-for-Linux , thanks.
