### ISSUE TITLE
Server start failures in RHEL-8 as RHEL-8 is not yet in support matrix

### ISSUE THREAD

**Issue by Divya273** [microsoft/omi#622]
In RHEL-8 when omi-1.4.2-2 is installed, omiserver is unable to start, and it fails to function properly. From syslogs, "SELinux (a kernel security module) is preventing systemd from read access on the file omiserver.pid." omiserver crashes are intermittent.

**Comment by sarojcare** [comment]
Issue is under Investigation

**Comment by Divya273** [comment]
Attaching snap of syslog during failure and omi console logs from RHEL8

[syslog_snap.txt](https://github.com/Microsoft/omi/files/3041839/syslog_snap.txt)
[rhel8_Intermittent_FailureLog.txt](https://github.com/Microsoft/omi/files/3041840/rhel8_Intermittent_FailureLog.txt)
