### ISSUE TITLE
Log rotation scheduled in /etc/cron.d/omilogrotate should use its own state file

### ISSUE THREAD

**Issue by gpenin** [microsoft/omi#626]
As logrotate does not lock the state file when running (logrotate/logrotate#113), multiple parallel logrotate executions can lead to corrupted state file or strange behavior, including system standard log rotation regularly not happening. As of today, for our Azure servers, logrotate is scheduled :

- In /etc/cron.daily/logrotate (System standard for Ubuntu)
- In /etc/cron.d/omsagent (OMS Agent for Linux)
- In /etc/cron.d/omilogrotate (Open Management Infrastructure)

All of them are using the same default state file : /var/lib/logrotate/status

Regularly, the state file loses system standard entries, for example :

[root@server ~]# cat /var/lib/logrotate/status
logrotate state -- version 2
"/var/opt/omi/log/omiserver.log" 2019-4-15-8:0:0
"/var/opt/omi/log/miclient.log" 2019-4-15-8:0:0
"/var/opt/omi/log/omiagent.root.root.log" 2019-4-15-8:0:0
"/var/opt/microsoft/omsagent/ef4fb18d-a2d7-4fca-a4d3-ef66f986b6f8/log/omsagent.log" 2019-4-15-8:0:0
"/var/opt/microsoft/scx/log/*/scx.log" 2019-4-15-8:0:0
"/var/opt/microsoft/omsagent/log/urp.log" 2019-4-15-8:0:0
"/var/opt/microsoft/scx/log/scx.log" 2019-4-15-8:0:0

As a consequence, the next system standard log rotation won't rotate any system log file, and will just restore the system log files status. We encounter the same behavior with at least Ubuntu 14.04 LTS, Ubuntu 16.04 LTS & Ubuntu 18.04 LTS.

**Comment by JumpingYang001** [comment]
@gpenin  thanks for reporting it, we will investigate the issue.
