### ISSUE TITLE
Duplicate logrotate commands on Linux cause error

### ISSUE THREAD

**Issue by mcbsys** [Microsoft/omi#627]
It looks like log rotation was set up here https://github.com/Microsoft/omi/issues/531, so hopefully this is the right place to report an issue with that.

Yesterday, I created a new Ubuntu 18.04 VM from Microsoft image. I set "OS guest diagnostics" = On. This installed LinuxDiagnostic extension 3.0.119, which created /etc/logrotate.d/omsagent-LAD with this content:
```
/var/opt/microsoft/omsagent/LAD/log/omsagent.log {
    rotate 10 
    missingok
    notifempty
    compress
    size 100M
    copytruncate
}

/var/opt/microsoft/omsagent/log/urp.log {
    rotate 3
    missingok
    notifempty
    compress
    size 50k
    copytruncate
}
```
I also have Security Center - Security policy > Settings - Data Collection - Auto Provisioning set to On. So eventually OmsAgentForLinux 1.9.1 was auto-deployed. This created /etc/logrotate.d/omsagent-aaaaa1b3-1111-2222-bf39-700df40cffff with this content:
```
/var/opt/microsoft/omsagent/omsagent-aaaaa1b3-1111-2222-bf39-700df40cffff/log/omsagent.log {
    rotate 10 
    missingok
    notifempty
    compress
    size 100M
    copytruncate
}

/var/opt/microsoft/omsagent/log/urp.log {
    rotate 3
    missingok
    notifempty
    compress
    size 50k
    copytruncate
}
```
Because there are duplicate logrotate configurations on the same log file (urp.log), every day I get this via email:

> Cron <root@MYSERVER> test -x /usr/sbin/anacron || ( cd / && run-parts --report /etc/cron.daily )
> /etc/cron.daily/logrotate:
> error: omsagent-LAD:10 duplicate log entry for /var/opt/microsoft/omsagent/log/urp.log
> 

I'm not sure how these two versions of the OMS agent are supposed to interact, but somehow the log rotation needs to be consolidated. Maybe just a separate /etc/logrotate.d/urp file for urp.log so if it already exists, it doesn't create another one?

**Comment by JumpingYang001** [comment]
@mcbsys thanks report it! we will check the issue.

**Comment by JumpingYang001** [comment]
@mcbsys I have checked your description, it is about oms, you can report it on https://github.com/Microsoft/OMS-Agent-for-Linux, I just close this item, thanks.

**Comment by mcbsys** [comment]
Thank you. Posted here:  https://github.com/Microsoft/OMS-Agent-for-Linux/issues/926.
