### ISSUE TITLE
 README.md PDF Link broken

### ISSUE THREAD

**Issue by vexvoltage** [microsoft/omi#630]
The OMI Getting Started Guide does not currently lead anywhere and/or has an invalid link location to the PDF File.

**Comment by JumpingYang001** [comment]
it linked to https://github.com/microsoft/omi/blob/master/Unix/doc/omi/omi.pdf , is it right? I can access it.
let me know if you still can't access it, thanks.

**Comment by vexvoltage** [comment]
Hi, Might be a issue with my access to it. I get this screen: 
![image](https://user-images.githubusercontent.com/23745835/57354135-50d4c100-7130-11e9-890f-29e2683aecaa.png)

**Comment by JumpingYang001** [comment]
I think your browser has some issue, I use Chrome and it works.
![pdfscreenshot](https://user-images.githubusercontent.com/16585827/57356029-444a6b80-7124-11e9-8de2-7ae7933081bc.PNG)
