### ISSUE TITLE
Resource leak

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [microsoft/omi#643]
Stream is opened
https://github.com/microsoft/omi/blob/62114349ba09a9df18c5137a1ab05f8dc562644c/Unix/http/http.c#L1586

Opened file never closed
https://github.com/microsoft/omi/blob/62114349ba09a9df18c5137a1ab05f8dc562644c/Unix/http/http.c#L1602

**Comment by QiAnXinCodeSafe** [comment]
the same issue：
Stream is opened
https://github.com/microsoft/omi/blob/62114349ba09a9df18c5137a1ab05f8dc562644c/Unix/strhash/strhash.cpp#L48

at the end of function,Opened file never closed
https://github.com/microsoft/omi/blob/62114349ba09a9df18c5137a1ab05f8dc562644c/Unix/strhash/strhash.cpp#L172

**Comment by QiAnXinCodeSafe** [comment]
another issue in the same file 'strhash.cpp', please fix it together
Stream is opened
https://github.com/microsoft/omi/blob/62114349ba09a9df18c5137a1ab05f8dc562644c/Unix/strhash/strhash.cpp#L324
at the end of function,Opened file never closed
https://github.com/microsoft/omi/blob/62114349ba09a9df18c5137a1ab05f8dc562644c/Unix/strhash/strhash.cpp#L361

**Comment by JumpingYang001** [comment]
strhash is a tool for building, so might not fix, thanks anyway.

**Comment by JumpingYang001** [comment]
omi/Unix/http/http.c has issue, we will consider to fix.
