### ISSUE TITLE
SUSE: Under what scenario will omiagent invoke zypper commands?

### ISSUE THREAD

**Issue by jessie-pang** [microsoft/omi#645]
I have a customer who complains about omiagent keeps invoking zypper commands. For some reason, some repositories were not reachable, so the zypper refersh operation got stuck sometimes, and it caused high CPU utilization. I am still working with customer to get more details and logs. I'd like to confirm: Under what scenario will omiagent invoke zypper command (for updating omi component or so)?

Environment: Mooncake
VM: SUSE 12 SP4 with omsagent installed

**Comment by JumpingYang001** [comment]
omiagent is a omi provider process, many providers: https://github.com/microsoft/omi#omi-providers, but some has deprecated. omi provider is not belonged to omi.
omsagent is different with omiagent, if it is omsagent, you need to contact oms team.
