### ISSUE TITLE
Never used variable ‘str’

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [microsoft/omi#653]
https://github.com/microsoft/omi/blob/5f2bf38c4c8bb23a89714f915882ecffad3cbcc4/Unix/wql/wqlyaccinc.c#L965

https://github.com/microsoft/omi/blob/5f2bf38c4c8bb23a89714f915882ecffad3cbcc4/Unix/wql/wqlyaccinc.c#L977

**Comment by JumpingYang001** [comment]
it is generated by byacc, I don't think we need to fix it.
