### ISSUE TITLE
Null deference

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [microsoft/omi#654]
There is no check for the failed strstr
https://github.com/microsoft/omi/blob/232a38192e16ca724f3f3438419f8ccaead10f34/Unix/nits/ut2nits/ut2nits.cpp#L49
This in turn would cause a segfault， when off is dereferenced
https://github.com/microsoft/omi/blob/232a38192e16ca724f3f3438419f8ccaead10f34/Unix/nits/ut2nits/ut2nits.cpp#L50

**Comment by JumpingYang001** [comment]
thanks for filing! nits is an unit test framework out of product, so just close it.
