### ISSUE TITLE
Checksum Issue - Downloading successful, but checksum doesn't match

### ISSUE THREAD

**Issue by rohrerb** [microsoft/omi#662]
**Mirror:** packages.microsoft.com/rhel/7/prod 
**The URL of this particular RPM package is:** https://packages.microsoft.com/rhel/7/prod/omi-1.6.4-0.ssl_100.ulinux.x64.rpm

```
Downloading successful, but checksum doesn't match. Calculated: aeb801a2e2155848cdd07f44f9077b920e57ea04f1b550dc1070a07f0f53a106(sha256)  Expected: 33d64c8269e16daf7c2ed432fb7881976205d291bb38879fcf40cf6197bc7688(sha256)
```

**Comment by JumpingYang001** [comment]
it is MS Repo mirror sync issue, it is updating.

**Comment by drzxiang** [comment]
the related icm has been resolved, so just close it.
