### ISSUE TITLE
OMI packages missing on Microsoft Repo for Ubuntu 20.10 (possibly others)

### ISSUE THREAD

**Issue by DavidRawling** [microsoft/omi#678]
The omi package is not available when using the Ubuntu "Groovy" repo.

```
> cat /etc/apt/sources.list.d/microsoft-prod.list
deb [arch=amd64,arm64,armhf] https://packages.microsoft.com/ubuntu/20.10/prod groovy main

> sudo apt install omi
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package omi
```

Expected Result: Current omi package is downloaded and installed with any required dependencies.

**Comment by JumpingYang001** [comment]
@DavidRawling omi does not officially support Ubuntu 20 yet.
you can try `wget https://github.com/microsoft/omi/releases/download/v1.6.6-0/omi-1.6.6-0.ssl_110.ulinux.x64.deb` to install it manually.

**Comment by deepakjain111** [comment]
OMI package has been added to MSRepo for Ubuntu 20.10
