### ISSUE TITLE
SELinux module not removed on uninstall/purge

### ISSUE THREAD

**Issue by fl-max** [microsoft/omi#683]
When running the steps outline [here](https://docs.microsoft.com/en-us/troubleshoot/azure/general/reinstall-oms-agent-linux#reinstall-oms-agent-for-linux) in the Azure Docs to remove OMS, the SELinux module `omi-selinux` remains.
```bash
# semodule -l | grep omi-selinux
omi-selinux	1.0
```

**Environment**
- OS: (OpenLogic) CentOS Linux release 7.4.1708 (Core)
- Kernel: 3.10.0-693.11.1.el7.x86_64

**Steps to reproduce:**
1. Standup VM using the `OpenLogic|CentOS|7-CI|7.4.20171212` Marketplace image
2. `wget https://raw.githubusercontent.com/Microsoft/OMS-Agent-for-Linux/master/installer/scripts/onboard_agent.sh`
3. `sudo sh onboard_agent.sh --purge`
4. `semodule -l | grep omi-selinux`

**Comment by JumpingYang001** [comment]
thanks for filing this issue, we have new a PR to fix it: #681

**Comment by JumpingYang001** [comment]
Fixed in #681 and will be in next release, thanks.
