### ISSUE TITLE
Can't build with MacOSX SDK

### ISSUE THREAD

**Issue by gaelicWizard** [microsoft/omi#687]
Apple's SDKs have a macro "__API_AVAILABLE" which has an associated macro named just "macos"...but OMI's configure script adds "-Dmacos" to $CFLAGS so ń̥otḩing builds. 

I realize that OMI for Mac for server config is a bit niche, but I'm actually trying to build it for client side. I'm using VSCode and would like to be able to compile DSC configs, &c.

Thanks,
JP2

/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/pthread/qos.h:291:22: error: expected ','
__API_AVAILABLE(macos(10.10), ios(8.0))
                     ^
In file included from pthread_rwlock_t_func.c:1:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/pthread.h:218:22: error: expected ','
__API_AVAILABLE(macos(10.4), ios(2.0))
                     ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/pthread.h:222:22: error: expected ','
__API_AVAILABLE(macos(10.4), ios(2.0))
                     ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/pthread.h:225:22: error: expected ','
__API_AVAILABLE(macos(10.4), ios(2.0))
                     ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/pthread.h:228:22: error: expected ','
__API_AVAILABLE(macos(10.4), ios(2.0))
                     ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/pthread.h:231:22: error: expected ','
__API_AVAILABLE(macos(10.4), ios(2.0))
                     ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]

**Comment by gaelicWizard** [comment]
It seems like this can be resolved by changing the "-Dmacos" to "-Dmacos=macOS" in buildtool

**Comment by polluks** [comment]
Indeed, there's a name clash: We use the macro `macos` w/o parameter, Apple uses `macos(version)` w/ check for minimal version...

**Comment by JumpingYang001** [comment]
no supported scenarios.
