### ISSUE TITLE
rpm mirror failed - omi-1.6.6-0 and scx-1.6.6-0

### ISSUE THREAD

**Issue by Slm0n87** [microsoft/omi#690]
__Steps to reproduce:__
0. Use a rhel7 or centos7 system or use docker: `docker run -it --rm centos:7 bash`
1. Create data dir & configure the repo
```bash
mkdir /data /meta
cat > /meta/microsoft.repo
[rhel-7-microsoft]
name=packages-microsoft-com-prod
baseurl=https://packages.microsoft.com/rhel/7/prod/
enabled=1
gpgcheck=1
gpgkey=https://packages.microsoft.com/keys/microsoft.asc
[ctl+d]
```
2. Configure reposync:
```bash
cat > /rhel7_reposync.conf
[main]
reposdir=/meta
[ctl+d]
```
3. Start reposync:
```bash
reposync  -d -a x86_64 -p /data -c /rhel7_reposync.conf --downloadcomps --download-metadata --allow-path-traversal --repoid rhel-7-microsoft
[...]
omi-1.6.6-0.x86_64: [Errno 256] No more mirrors to try.
scx-1.6.6-0.x86_64: [Errno 256] No more mirrors to try.
```

__Expected behavior:__
The reposync has to sync all rpms successfully.

__Actual behavior:__
The reposync failed, because the two failing rpms can not be synced.

**Comment by JumpingYang001** [comment]
@Slm0n87 we have fixed it recently, you can try `rm -rf /var/cache/yum/packages-microsoft-com-prod/` and `yum update -y`, and retry `reposync`  again, it should work now, thanks.
