### ISSUE TITLE
Installation failure for SLES ppc64le (power Linux)

### ISSUE THREAD

**Issue by geralexgr** [microsoft/omi#691]
Installer cannot detect that Linux architecture is power instead of x86.

System:

Linux machine 4.12.14-95.19-default #1 SMP Tue Jun 11 11:04:48 UTC 2019 (a904a7f) ppc64le ppc64le ppc64le GNU/Linux

`machine~ # cat /etc/SUSE-brand `

SLE VERSION = 12

**Command:**

`./omsagent-1.13.35-0.universal.x64.sh file gets a wrong input as far as it concerns architecture of system.`

**Output:**

#######################################################################################
Checking host architecture ...
Extracting...
----- Installing package: omi (omi-1.6.4-0.ulinux.x64) -----
Preparing...                          ################################# [100%]
	package omi-1.6.4-0.x86_64 is intended for a different architecture
./omsagent-1.13.35-0.universal.x64.sh: line 1384: /opt/omi/bin/service_control: No such file or directory
OMI server failed to start due to OMI installation failed and exited with status 127
----- Installing package: scx (scx-1.6.4-7.universal.x64) -----
error: Failed dependencies:
	omi >= 1.0.8-6 is needed by scx-1.6.4-7.x86_64
----- Removing package: scx -----
error: package scx is not installed
----- Ignore previous errors for package: scx -----
----- Removing package: omi -----
error: package omi is not installed
----- Ignore previous errors for package: omi -----
----- Installing package: omi (omi-1.6.4-0.ulinux.x64) -----
Preparing...                          ################################# [100%]
	package omi-1.6.4-0.x86_64 is intended for a different architecture
omi-1.6.4-0.ulinux.x64 package failed to install and exited with status 1
Install failed
OMS Troubleshooter is installed.
You can run the Troubleshooter with the following command:

  $ sudo /opt/microsoft/omsagent/bin/troubleshooter

Shell bundle exiting with code 19
#######################################################################################

When running the troubleshooting tool, it also fails to determine the architecture.

> Checking if running a supported OS version...
> ERROR FOUND: Couldn't get if CPU is 32-bit or 64-bit.
> ERROR(S) FOUND.
> ================================================================================
> ================================================================================
> ALL ERRORS/WARNINGS ENCOUNTERED:
>   ERROR FOUND: Couldn't get if CPU is 32-bit or 64-bit.
> --------------------------------------------------------------------------------
> Please review the errors found above.
>

**Comment by JumpingYang001** [comment]
@geralexgr oms doesn't support PowerPPC and only omi/scx supports PowerPPC, you can refer to https://github.com/microsoft/OMS-Agent-for-Linux#64-bit, I think you can file issue on oms repo and that might be by design.
this is SUSE 12 PPC omi:
https://github.com/microsoft/omi-kits/blob/master/release/omi-1.6.8-0.suse.12.ppc.rpm
and scx only can get from SCOM:
https://docs.microsoft.com/en-us/system-center/scom/plan-supported-crossplat-os?view=sc-om-2019#suse-linux-enterprise-server-12-power
