### ISSUE TITLE
Publish GitHub Security Advisories

### ISSUE THREAD

**Issue by brandonweeks** [microsoft/omi#695]
[GitHub Security Advisories](https://docs.github.com/en/code-security/security-advisories/about-github-security-advisories) offer a way to inform users of a project about a security vulnerability. Microsoft should lead by example by publishing security advisories in the same manner GitHub expects of open source maintainers.

**Comment by deepakjain111** [comment]
Thanks @brandonweeks for the suggestion. We shall consider GitHub Security Advisories.
