### ISSUE TITLE
Issues with logrotate after  upgrading OMI

### ISSUE THREAD

**Issue by norman-smith** [microsoft/omi#708]
Hi,

I have a problem with my Wildfly application servers logging when the omi server is running.
It seems to be permission related as the log file being created is owned by root and not the wildfly user.
The problem resolves itself when the omi server is stopped.

Could you possibly assist with determining what would cause this problem.

Kind Regards
Norman

**Comment by JumpingYang001** [comment]
@norman-smith what is server.log? in which location? which product generate it?
and converis is the user of wildfly?

**Comment by norman-smith** [comment]
Hi @JumpingYang001 

I hope you are well. We seem to be experiencing this problem again and I would like to reopen this ticket to try and resolve this again please.

Kind regards
Norman
