### ISSUE TITLE
license inconsistent (MIT or Apache V2) 

### ISSUE THREAD

**Issue by zhiqiangwang08** [microsoft/omi#709]
The license of OMI is confusing. 

1. the Link below show it is MIT:
     https://github.com/microsoft/omi/blob/master/LICENSE

2. but another link show it is Apache V2:
   https://github.com/microsoft/omi/blob/master/Unix/doc/omi/omi.pdf
>   1.4 License
>OMI software is currently freely available for use by anyone under the terms of the Apache
>2.0 license (http://www.apache.org/licenses/LICENSE-2.0.txt).

Could you clarify it?  it is MIT or Apache V2?

**Comment by JumpingYang001** [comment]
@zhiqiangwang08 MIT is the correct one, our team will update it in the future.
