### ISSUE TITLE
OMI Reverts back from 1.6.8.1 to 1.6.4 on Azure VM

### ISSUE THREAD

**Issue by amrsharaf** [microsoft/omi#711]
I've updated the OMI package on my azure VM from 1.6.4 to 1.6.8.1 to mitigate the reported security vulnerability with:

`sudo apt-get install omi`

However, few days after the install I notice that the OMI version gets reverted back to 1.6.4, I'm not sure why that happens and how to debug this issue, any idea what could be going on?

Thanks!

**Comment by JumpingYang001** [comment]
@amrsharaf I think it is related to OMS/LAD, can you create a ticket on Azure?

**Comment by edwio** [comment]
Can anyone confirm this issue?

**Comment by amrsharaf** [comment]
Any updates on this? I haven't heard back from the OMS team at all, I also opened a ticket on Azure VM and no-one seems to understand what is going on. Many thanks!

**Comment by JumpingYang001** [comment]
@amrsharaf did you get contact support team when open a ticket on Azure? can you ask support team to create ICM to OMS team? I believe they will have progress when you ask support team to create ICM.

**Comment by amrsharaf** [comment]
I did open a ticket on Azure, I'll ask for the OMS ICM. Thanks!

**Comment by Abro61209** [comment]
Same issue here. It's just this one VM that keeps reverting back to 1.6.4. Can't figure out why. Every other VM is fine. I am going to open a support ticket with Azure but is there any update on this?

**Comment by JumpingYang001** [comment]
@Abro61209 I think only Azure ticket or ICM is the correct way to get the update about the issue from OMS team.

**Comment by Abro61209** [comment]
> I have a similar issue after upgrade to 1.6.8.1 it reverts to 1.6.4; do we have any active incident open? Its high critical as not able to meet the security compliance.
> 
> @Abro61209 / @amrsharaf - did they provide any solution on the support ticket ?

After trying to figure out the problem with Azure support for weeks, they found in the Log Analytics agent that two versions of the OMSagent were installed. One was 1.13.35 which is what was reverting it back to omi 1.6.4. We were advised to remove it from the Azure UI and it seems like it removed the old omsagent, and kept the new one, 1.13.40.
