### ISSUE TITLE
Ubuntu 22.04 LTS - Add support for OMI to work with OpenSSL v3.0.x

### ISSUE THREAD

**Issue by NoCoker** [microsoft/omi#715]
As of the upcoming LTS release of Ubuntu Jammy 22.04 i like t ask if there are plans to upgrade the package to support also OpenSSL 3.x branch ?

**Comment by chinmay241** [comment]
Testing on Ubuntu 22.04 LTS, Due for final release tomorrow.
As far as I can see from the Logs Ubuntu 22.04 LTS is not supported due to OpenSSL3 support.

```
Apr 20 13:51:10 systemd[1]: Starting OMI CIM Server...
Apr 20 13:51:10 installssllinks[62447]: Error: OpenSSL version '3.0.2' is not supported. Supported versions of OpenSSL are:
Apr 20 13:51:10 installssllinks[62447]:     1.0.*, and 1.1.*.
Apr 20 13:51:10 systemd[1]: omid.service: Control process exited, code=exited, status=2/INVALIDARGUMENT
Apr 20 13:51:10 systemd[1]: omid.service: Failed with result 'exit-code'.
Apr 20 13:51:10 systemd[1]: Failed to start OMI CIM Server.
```

**Comment by Divya273** [comment]
By when can we get omi support for Ubuntu Jammy 22.04 (OpenSSL-3.x)?

**Comment by Divya273** [comment]
Hi @chinmay241,
We are looking for omi support in Ubuntu 22.04 to integrate with one of our products. Could you please tell us by when can we get this?
Thanks in advance!

**Comment by deepakjain111** [comment]
Hi @Divya273, 
Would you like to add your product details that make use of OMI?

**Comment by Divya273** [comment]
Hi Deepak,

We are using OMI in one of our tools named "Dell Command Monitor". This tool enables system administrators to manage inventory and monitor system health.

For Linux Clients we have integrated Dell Command Monitor with OMI so that our tool can retrieve management information through OMI interface.

Dell Command Monitor for Windows retrieves management information through the CIM Object Manager (CIMOM) interface, or Windows Management Instrumentation (WMI) stack. Hence in Linux, for an equivalent interface with CIM management server, Dell Command Monitor uses OMI.

For more details refer,
https://www.dell.com/support/kbdoc/en-us/000177080/dell-command-monitor

We are extending Dell Command Monitor support to Ubuntu-22.04 (Jammy) and to do this we need compatible OMI. Could you please let us know by when can we get the supported OMI?

Regards,
Divya

**Comment by Divya273** [comment]
Hi @deepakjain111,

We are using OMI in one of our tools named “Dell Command Monitor”. This tool enables system administrators to manage inventory and monitor system health.

For Linux Clients we have integrated Dell Command Monitor with OMI so that our tool can retrieve management information through OMI interface.

Dell Command Monitor for Windows retrieves management information through the CIM Object Manager (CIMOM) interface, or Windows Management Instrumentation (WMI) stack. Hence in Linux, for an equivalent interface with CIM management server, Dell Command Monitor uses OMI.

For more details refer,
https://www.dell.com/support/kbdoc/en-us/000177080/dell-command-monitor

We are extending Dell Command Monitor support to Ubuntu-22.04 (Jammy) and to do this we need compatible OMI. Could you please let us know by when can we get the supported OMI?

**Comment by deepakjain111** [comment]
Hi @Divya273, It is good to know "Dell Command Monitor" uses OMI. 
Just curious to know, have you been maintaining providers for your purposes or just make use of providers provided by OMI, for example SCX.
Regarding Ubuntu-22.04 support: It is under discusson. It might takes at least 1-2 months from now. We will update here as and when we have more clear update.

**Comment by Divya273** [comment]
Hi @deepakjain111 , We are maintaining our own providers specific to Dell Command Monitor.

**Comment by betrotle** [comment]
I am also interested in this, but for support on RHEL 9 (released May 17).
Only using SCX provider though.

**Comment by anthonysomerset** [comment]
So we are installing omsagent to linux hosts which requires omi... we are using omsagent as our main method of capturing logs from linux hosts to send to log analytics and then into Microsoft Sentinel, we also install the same on our syslog collectors as well so this prevents our ability to roll out 22.04 or upgrade

this is also mentioned over at https://github.com/microsoft/OMS-Agent-for-Linux/issues/1458

**Comment by Divya273** [comment]
Hi @deepakjain111/@JumpingYang001,

Since you have already working on it, could you please let us know by when can we get the fix or support for Ubuntu22.04.

Thanks!

**Comment by watsonb** [comment]
It is now September 8th 2022.  Any updates on this?  There is already a point release, Ubuntu 22.04.1, which is when most seriously consider using the newer version (myself included), but we really want this functionality before we start rolling out new or upgrading existing servers.

**Comment by damirkasper** [comment]
hello, just chiming in to say that getting Ubuntu 22 support and other distros that are now shipping with openssl 3.x is critical as this issue is likely holding many back from being able to upgrade.

**Comment by JumpingYang001** [comment]
It is in progress, possible will be in next release.

**Comment by deconma** [comment]
Hi,

Are there any updates regarding the next steps, open topics or eta for the next release @JumpingYang001 ?

Thanks in advance.

**Comment by JumpingYang001** [comment]
@deconma latest update: openssl 3.0 support is possible after omi 1.6.10-3 hotfix.

**Comment by deconma** [comment]
Hi @JumpingYang001 ,

Great to hear, do you have an eta for the hotfix release?
Or can we download this hotfix on a sperated release page?

Thanks in advance.
Kind regards

**Comment by JumpingYang001** [comment]
@deconma 1.6.10-3 hotfix. doesn't include openssl 3.0 support, and the openssl 3.0 support is after the hotfix. I don't know the openssl 3.0 support ETA, but it is possible after the small 1.6.10-3 hotfix.

**Comment by deconma** [comment]
Hi @JumpingYang001 ,

Thank you for the last feedback. Do you have an update regarding the OMI hotfix?
Or do we have a new eta on a potential release for the openssl 3.0 changes? Same for issue #723 .

**Comment by deconma** [comment]
Hi,

Are there additional changes in the pipeline due to the recent events with the OpenSSL v3.0.X issues?
Or will this not impact the next release of the omi agent? Same for issue #723 


Thanks in advance.

**Comment by JumpingYang001** [comment]
@deconma it is not related to openssl 3.0 , I think it was the hot fix, and the openssl 3.0  is still in progress.

**Comment by marslandp** [comment]
```
@deconma after an omi hotfix.
The openssl 3.0 support work is in progress. Will update here once done, it might cost 1~2 months.
```

Are there any timescale updates for the openssl 3.0 support?

**Comment by nitinkathpalia09** [comment]
> @deconma after an omi hotfix. The openssl 3.0 support work is in progress. Will update here once done, it might cost 1~2 months.

Are there any ETA updates on this?

**Comment by deconma** [comment]
Hi @JumpingYang001 

Could you provide us with a new ETA regarding the next release for OMI including the OpenSSL v3.x support?
We are waiting for an updated implementation of Ubuntu 22 and Red Hat 9 #723 .


Thanks in advance.

**Comment by JumpingYang001** [comment]
It is in progress, will update here once it is planned.

**Comment by deconma** [comment]
Hi @JumpingYang001 ,

Could you provide us with an update regarding the current planning/changes for the OpenSSLv3.0.x implementation?
We would like to go forward with the implementation of Ubuntu 22 and Red Hat Linux 9 servers (#723) , this using the newly OpenSSL versions.

Thanks in advance!

**Comment by JumpingYang001** [comment]
@deconma we are focusing on adding openssl 3.x support now.

**Comment by JumpingYang001** [comment]
@deconma
openssl 3.x : https://github.com/microsoft/omi/releases/tag/v1.7.0-0

**Comment by DaedalusEH** [comment]
I am getting an error with omi 1.7.0 only supporting OpenSSL 1.1.0 and not 3.0.2 in Ubuntu 22.04 LTS
<img width="712" alt="Screenshot 2023-03-31 at 15 55 39" src="https://user-images.githubusercontent.com/68499169/229155988-9b1f97bd-1a1a-4883-b9b1-41459f05ad20.png">

**Comment by JumpingYang001** [comment]
@DaedalusEH I guess you followed the guide of 20.04?  https://learn.microsoft.com/en-us/windows-server/administration/linux-package-repository-for-microsoft-software#ubuntu

please try use 22.04 repo instead of 20.04 repo,
1. Remove your 20.04 repo at first.
```
sudo apt-add-repository -r https://packages.microsoft.com/ubuntu/20.04/prod
```
2. Add 22.04 repo and update.
```
curl -sSL https://packages.microsoft.com/keys/microsoft.asc | sudo tee /etc/apt/trusted.gpg.d/microsoft.asc

sudo apt-add-repository https://packages.microsoft.com/ubuntu/22.04/prod

sudo apt-get update
```

**Comment by JumpingYang001** [comment]
Good as expected as my guess. https://github.com/microsoft/omi/issues/739
