### ISSUE TITLE
omicli commandline  memory corrupted and output invalid chars

### ISSUE THREAD

**Issue by zhiqiangwang08** [microsoft/omi#716]
1. the bug is not reproducible in one time run but inside infinite loop
2. run the command below:
`while true ; do 
         omicli  --auth NegoWithCreds -synchronous  --hostname 172.30.59.137 -u administrator -p 'password-here' --port 5985 --encryption http wql root/cimv2 "Select * from Win32_ComputerSystem";
 done  | grep -a  -P -n "[\x00-\x1F\x7F-\xFF]"`

3. wait for some times:
4. check the output:
    4.1 corrupted double-linked list (not small)
    4.2 instance of Win32_ComputerSys?Áª<90>ðÛ  (invalid chars here).
5. happened in synchronous mode only (-synchronous)

**Comment by JumpingYang001** [comment]
thanks for filing it! there is no supported scenario for remoting from Linux to Windows now. just close it.
and we also don't use -synchronous in our product scenarios.
