### ISSUE TITLE
root/dcim/sysman - MI_RESULT_INVALID_NAMESPACE Issue

### ISSUE THREAD

**Issue by lokesh-chitla** [microsoft/omi#720]
Hello All,

Able to run sample case "# /opt/omi/bin/omicli ei root/omi OMI_Identify" Ok , 
but, somehow for mention scenario getting issues related to namespace, not sure its something to do with setup or limitations issue(known).. any thoughts would be appreciated, thanks. 

# /opt/omi/bin/omicli ei root/dcim/sysman DCIM_BIOSEnumeration
/opt/omi/bin/omicli: result: MI_RESULT_INVALID_NAMESPACE
/opt/omi/bin/omicli: result: The target namespace does not exist.
instance of OMI_Error
{
    OwningEntity=OMI:CIMOM
    MessageID=OMI:MI_Result:3
    Message=The target namespace does not exist.
    MessageArguments={}
    PerceivedSeverity=7
    ProbableCause=0
    ProbableCauseDescription=Unknown
    CIMStatusCode=3
    OMI_Code=3
    OMI_Category=10
    OMI_Type=MI
    OMI_ErrorMessage=The target namespace does not exist.
}
#

**Comment by JumpingYang001** [comment]
@lokesh-chitla make sure you have DCIM_BIOSEnumeration class defined in /etc/opt/omi/conf/omiregister/root-dcim-sysman/yourprovidername.reg, I believe DCIM_BIOSEnumeration is not our provider. :)
