### ISSUE TITLE
Support for OMI package on RHEL9.x

### ISSUE THREAD

**Issue by GulhaneChaitanya** [microsoft/omi#723]
Hi,

As in RHEL 9.x, openssl has been upgraded to 3.x, available OMI packages supporting openssl version 1.x are not working on RHEL 9.x.

Would you please let me know when can the OMI package with openssl 3.x support on RHEL9.x be available?

Is there any alternate solution available for existing OMI packages to work on RHEL 9.x?

Regards,
Chaitanya.

**Comment by JumpingYang001** [comment]
same with #715

**Comment by GulhaneChaitanya** [comment]
Hi @JumpingYang001 

Could you please let us know any ETA for this?

Regard,
Chaitanya.

**Comment by deconma** [comment]
Hi @JumpingYang001 ,

Do you have a further update regarding the current state of this implementation?
Or would this be in the same ETA of #715 ?


Thanks in advance,
Maxim

**Comment by JumpingYang001** [comment]
@deconma yes, same time release.

**Comment by GulhaneChaitanya** [comment]
Hi @JumpingYang001 ,

I see that there is a release '1.6.11-0' has been released. 

Would you please let us know when can we expect OMI support for OpenSSL 3.x?

Regards,
Chaitanya.

**Comment by JumpingYang001** [comment]
@GulhaneChaitanya 1.6.11-0 is NOT including openssl 3.x, and openssl 3.x is still in progress.

**Comment by JumpingYang001** [comment]
@GulhaneChaitanya we are focusing on adding openssl 3.x support now.

**Comment by GulhaneChaitanya** [comment]
@JumpingYang001
any ETA for that?

**Comment by JumpingYang001** [comment]
> @JumpingYang001 any ETA for that?

no ETA, but will update here once it is completed.

**Comment by wouterhummelink** [comment]
RHEL 9 provides a compat-openssl11 package for runtime compatibility with older software. However the prein scripts for both OMI and SCX ignore that the correct libraries are available, but rather checks the version of the openssl binary. This seems wrong.

**Comment by wouterhummelink** [comment]
By nixing the rpm scripts I was able to get OMI and SCX installed and started, so compat-openssl11 is a viable platform.
I did have to perform some extra configuration that would normally be taken care of by the postin rpm scripts

**Comment by JumpingYang001** [comment]
@wouterhummelink you use `/usr/bin/openssl11`? I think your provided  compat-openssl11 with openssl11 looks something similar to SUSE openssl1 way, https://github.com/microsoft/omi/blob/e4d72481fa2f805148c9c8f4d0183b3e2d7814a8/Unix/installbuilder/datafiles/ULinux.data#L28
anyway, openssl 3.0 omi/scx packages will be released soon.

**Comment by wouterhummelink** [comment]
The compat library does not provide an openssl binary, just libssl and libcrypto on RHEL

**Comment by JumpingYang001** [comment]
@GulhaneChaitanya 
openssl 3.x : https://github.com/microsoft/omi/releases/tag/v1.7.0-0

**Comment by wouterhummelink** [comment]
Any update on when the packages are available in microsoft-prod repository?

**Comment by JumpingYang001** [comment]
@wouterhummelink it is already in MS Repo.

**Comment by JumpingYang001** [comment]
The issue has been fixed so I close the issue.
