### ISSUE TITLE
Issue with MD5 checksum.

### ISSUE THREAD

**Issue by abhishekdgc** [microsoft/omi#724]
Hello Support, 

I'm trying to download the latest OMI (v1.6.9-1) package from Github repo.

But after downloading the RPM I'm receiving a different MD5 checksum than the one displayed on https://github.com/microsoft/omi/releases/tag/v1.6.9-1
Tried from 2 different machines, can someone please check and let me know if there's any typo or if I'm doing something incorrectly?

WINDOWS:
certutil -hashfile omi-1.6.9-1.ssl_100.ulinux.x64.rpm MD5
MD5 hash of omi-1.6.9-1.ssl_100.ulinux.x64.rpm:
3064dfce1d4a58fc60d00c300cf15dc7
CertUtil: -hashfile command completed successfully.

LINUX:
md5sum omi-1.6.9-1.ssl_100.ulinux.x64.rpm 
3064dfce1d4a58fc60d00c300cf15dc7  omi-1.6.9-1.ssl_100.ulinux.x64.rpm

**Comment by JumpingYang001** [comment]
@abhishekdgc thanks for filing it! we are checking.

**Comment by JumpingYang001** [comment]
@abhishekdgc updated new packages.
