### ISSUE TITLE
omi 1.6.10 crashes while running Desired State Configuration PerformRequiredConfigurationChecks.py

### ISSUE THREAD

**Issue by eehret** [microsoft/omi#727]
Same issue has been observed on RHEL 7.9, RHEL 8.6, and Ubuntu 18.04 LTS so far.

Azure DSC VM extension version: 3.7.0 (note that this also happens with other versions such as 3.0.0.7)
dsc package version: dsc-1.2.3
OMI version: 1.6.10

As a controlled test to rule out as many external factors as possible, I set up an environment using a 'vanilla' RHEL 8.6 VM from Azure Marketplace (From Red Hat publisher), using a bare bones DSC configuration containing a single configuration item to just ensure a single package is present was was already present.

If I downgrade to 1.6.9 again, then it works once again.

Error output from /var/log/messages:

Aug 16 15:17:48 rhel-8-dsctest kernel: traps: omiagent[8605] general protection fault ip:46cdfe sp:7ffc445ddc50 error:0 in omiagent[400000+b8000]
Aug 16 15:17:48 rhel-8-dsctest systemd[1]: Started Process Core Dump (PID 8701/UID 0).
Aug 16 15:17:48 rhel-8-dsctest systemd-coredump[8702]: Process 8605 (omiagent) of user 0 dumped core.#012#012Stack trace of thread 8605:#012#0  0x000000000046cdfe n/a (omiagent)#012#1  0x00000000004049d8 n/a (omiagent)#012#2  0x00007f1e727f2cf3 __libc_start_main (libc.so.6)#012#3  0x0000000000404129 n/a (omiagent)
Aug 16 15:17:48 rhel-8-dsctest systemd[1]: systemd-coredump@1-8701-0.service: Succeeded.

**Comment by JumpingYang001** [comment]
@eehret I see latest dsc is 1.2.3-0, can you run `rpm -qa|grep dsc;dpkg -l|grep dsc` to check your dsc version?
https://github.com/microsoft/PowerShell-DSC-for-Linux/releases

**Comment by eehret** [comment]
Hi @JumpingYang001 
Yes, that's right.   We're running 1.2.3 here as well.  The DSC version I mentioned above was the version of the DSC VM extension for linux (for which dsc-1.2.3 is a dependency)

**Comment by JumpingYang001** [comment]
@eehret  we don't have azure box, we just installed OMI-1.6.10-2 + DSC-1.2.3-0 locally and run PerformRequiredConfigurationChecks.py, it outputs
```
instance of PerformRequiredConfigurationChecks
{
    ReturnValue = 0
}
```
do we need to set anything on local?

**Comment by eehret** [comment]
Hi @JumpingYang001 
No, not that I'm aware of.   This was basically a "vanilla" VM from Azure marketplace, nothing was done to it other than turning it on and installing a couple of VM extensions.

**Comment by JumpingYang001** [comment]
@eehret can you ask support or create ticket on Azure portal or ask them to create ICM, etc. , so they might provide us a reproduced VM?

**Comment by JumpingYang001** [comment]
@eehret could you ping my name 'Jumping Yang' in MS Teams and share me the reproduced VM so we can help to check the issue?

**Comment by JumpingYang001** [comment]
@eehret There might be some issue with OMI provider (DSC in this case) itself, it is better to open up a ticket with respective Azure service for first level of investigation, if required, OMI team will internally sync up with them.

**Comment by eehret** [comment]
@JumpingYang001 If you don't believe this is the right place to report this issue then can you help me find the right place?   I presume you understand how Microsoft is organized better than I do, since you work for them and I do not.
Thanks!

**Comment by eehret** [comment]
I have now opened a support case with Microsoft.  I don't know what ICM is, but hopefully we'll figure out how to get the problem resolved this way.

**Comment by JumpingYang001** [comment]
@eehret once you create support case, someone from support team will contact you, then you can ask him/her to create ICM to reach DSC team at first, if required, DSC will add OMI team there, thanks.

**Comment by eehret** [comment]
@JumpingYang001 Thanks.  Someone is taking a look at it now!

**Comment by JumpingYang001** [comment]
Fixed in https://github.com/microsoft/omi/commit/a26b52a748bf942af5bc72aef80b7fb72e79b3df .
