### ISSUE TITLE
Kernel trap errors

### ISSUE THREAD

**Issue by ronaldbckl** [microsoft/omi#733]
On a bunch of Redhat 7.9 servers we get a lot of messages like this:

[ 1079.381159] traps: omiengine[38343] general protection ip:7f08cf2048c1 sp:7ffe816e95c8 error:0 in libc-2.17.so[7f08cf095000+1c4000]
messages-20230122:Jan 19 07:58:14 hostname kernel: [ 1037.095796] traps: omiengine[2417] general protection ip:7fae689668c1 sp:7ffc5a4208b8 error:0 in libc-2.17.so[7fae687f7000+1c4000]

These are the installed version of the libc components:
yum list installed | grep libc
glibc.i686 2.17-326.el7_9 @local_rhel-7-server-rpms
glibc.x86_64 2.17-326.el7_9 @local_rhel-7-server-rpms
glibc-common.x86_64 2.17-326.el7_9 @local_rhel-7-server-rpms
glibc-devel.x86_64 2.17-326.el7_9 @local_rhel-7-server-rpms 

Omi version is:
omi.x86_64                     1.6.10-2                installed

**Comment by JumpingYang001** [comment]
@ronaldbckl thanks for filing it! If you are Azure OMS customer, you can create a ticket on the portal. If you are SCOM customer, you can contact your SCOM support team to create a ticket.

**Comment by JumpingYang001** [comment]
@ronaldbckl have you created the SCOM ticket?
as no update for this issue, just close it.
