### ISSUE TITLE
Ubuntu 22.04 LTS , OMI 1.7.0 issue with OpenSSL 3.0.2

### ISSUE THREAD

**Issue by DaedalusEH** [microsoft/omi#739]
Looks like OpenSSL 3.0.2 still not supported in OMI 1.7.0 ? The error that I am getting is that it only supports up to 1.1.0 .
<img width="712" alt="Screenshot 2023-03-31 at 15 55 39" src="https://user-images.githubusercontent.com/68499169/229156912-76b9e6af-7d73-4917-9610-cd0e390a412d.png">

**Comment by JumpingYang001** [comment]
@DaedalusEH I guess you followed the guide of 20.04?  https://learn.microsoft.com/en-us/windows-server/administration/linux-package-repository-for-microsoft-software#ubuntu

please try use 22.04 repo instead of 20.04 repo,
1. Remove your 20.04 repo at first.
```
sudo apt-add-repository -r https://packages.microsoft.com/ubuntu/20.04/prod
```
2. Add 22.04 repo and update.
```
curl -sSL https://packages.microsoft.com/keys/microsoft.asc | sudo tee /etc/apt/trusted.gpg.d/microsoft.asc

sudo apt-add-repository https://packages.microsoft.com/ubuntu/22.04/prod

sudo apt-get update
```

**Comment by DaedalusEH** [comment]
I guess the IT hasnt updated the microsoft repo when they delivered the OS to me (possibly they did upgrade from 20.04 to 22.04).
Thanks for the guide, I removed the old repo installed the new one and that works fine now.  Thanks. Closing down the issue as it is resolved.

**Comment by JumpingYang001** [comment]
Good to know it. :)
