### ISSUE TITLE
check target

### ISSUE THREAD

**Issue by polluks** [microsoft/omi#740]
check should work without a prior install but the server is missing
```
$ make check
[...]
+ set +x
( LD_LIBRARY_PATH=/tmp/omicheck.root//opt/omi-1.0.8/lib;  \
  export LD_LIBRARY_PATH;  \
  DYLD_LIBRARY_PATH=/tmp/omicheck.root//opt/omi-1.0.8/lib;  \
  export DYLD_LIBRARY_PATH; \
  /tmp/omicheck.root//opt/omi-1.0.8/bin/omiserver -i -d --livetime 60 --httpport 0 --httpsport 0 --destdir=/tmp/omicheck.root )
/bin/sh: 5: /tmp/omicheck.root//opt/omi-1.0.8/bin/omiserver: not found

**Comment by JumpingYang001** [comment]
@polluks we dropped `omicheck` in omi package, and if you want to use `make check` in your own development environment, you should `make` or `make install` at first, we don't use the option now.
and I see it seems you are using omi-1.0.8, it is 10 years ago omi version...

**Comment by polluks** [comment]
I see. By the way "*** UNABLE TO LOCATE FILE omi.version; USING VERSION 1.0.8.6 ***".

**Comment by JumpingYang001** [comment]
@polluks we build it with https://github.com/microsoft/build-omi .
