### ISSUE TITLE
Support release attribute better

### ISSUE THREAD

**Issue by dylan-bartos-tanium** [microsoft/omi#741]
Packages released typically have multiple version attributes (Epoch, Version, Release). The omi package provides a major/minor version tag in the Version attribute (1.7.0 at the time of this posting). It additionally provides a Release attribute which is commonly noted as either 0 or 1 in the release notes. In the repodata, this is maintained across all OSes.

The industry best practice is to provide some form of additional identifying information on a per-OS basis. For instance, RHEL7 and derivatives use an "{int}.el7" or "{int}.el7_9" format to denote the major/minor release of the OS. RHEL8 and derivatives use a formatting like "{int}.el8". This helps clearly identify which OS a particular RPM was built for.

If we look at the curl package, you find attributes:
Epoch: (none)
Name: curl
Version: 7.61.1
Release: 22.el8
Architecture: x86_64

The omi package has attributes:
Epoch: (none)
Name: omi
Version: 1.7.0
Release: 0
Architecture: x86_64

The omi package should better conform to industry standards for RedHat, SUSE, DEB, and derivatives.

**Comment by JumpingYang001** [comment]
@dylan-bartos-tanium thanks for filing it!
it was a history reason, that omi designed and used **same universal package** for all different kinds of system, so no el7, el8 in the Release attribute.

CentOS 6 and 7,8 
Alma9x64
Rocky9x64
Rocky8x64
Alma8x64
Oracle Linux 5, 6, and 7, 8,9
Red Hat Enterprise Linux Server 5 and 6, and 7,8 ,9
suse 11,15
