### ISSUE TITLE
omi and scx packages missing digest information for RHEL

### ISSUE THREAD

**Issue by sodds-eq** [microsoft/omi#742]
Packages:

   - omi
   - scx

These packages does not contain digest information, which means they will fail to install on a system that is running in FIPS mode.
The packages are available in both RHEL and packages.microsoft.com, and the latter is needed for getting mdatp packages.

So in my mind the packages.microsoft.com repository should contain all necessary digest information to avoid having to use --nodigest --nofiledigest for updating from it. As it is now the autoupdate will fail when its pulling the packages from packages.microsoft.com repository. So this is not a proper way to deliver those packages.

**Comment by JumpingYang001** [comment]
@sodds-eq thanks for filing it! I will update here if any news.

**Comment by sodds-eq** [comment]
Still waiting for this. Rather disappointing that a large company like Microsoft can't package their software properly.

**Comment by JumpingYang001** [comment]
@sodds-eq, it will be in next release.

**Comment by JumpingYang001** [comment]
it is fixed in v1.7.3-0.
