### ISSUE TITLE
OMI 1.7.0-0 issues

### ISSUE THREAD

**Issue by amanpreetb** [microsoft/omi#754]
Version: 1.7.0-0 

2023/10/26 00:24:28 [12386524,1] WARNING: null(0): EventId=30119 Priority=WARNING ssl-read: unexpected sys error 73

2023/12/15 01:00:52 [21495980,1] ERROR: null(0): WSMAN_New_Listener() failed for encrypted port 4294966088. Err = 8
2023/12/15 01:00:52 [15335578,1] FATAL: null(0): EventId=10005 Priority=FATAL abnormal termination of engine process detected...shutting down server
2023/12/15 01:03:45 [13893684,1] FATAL: null(0): EventId=10023 Priority=FATAL Protocol_New_Listener() failed: /var/opt/omi/run/omiserver.sock
2023/12/15 01:03:45 [13893684,1] ERROR: null(0): Protocol_New_Listener() failed:
2023/12/15 01:03:45 [14483620,1] FATAL: null(0): EventId=10005 Priority=FATAL abnormal termination of engine process detected...shutting down server

**Comment by JumpingYang001** [comment]
@amanpreetb how to repro it? can you create ticket or ICM on SCOM or Azure OMS?

**Comment by JumpingYang001** [comment]
No response, just close.
