### ISSUE TITLE
Is OMI coming to PowerShell

### ISSUE THREAD

**Issue by Liturgist** [microsoft/omi#758]
It appears that Microsoft will not be bringing CIM to any platform other than Windows. Is that correct?

Will OMI be coming to Linux? Will there be an OMI interface through PowerShell?

**Comment by JumpingYang001** [comment]
@Liturgist currently official omi doesn't support PowerShell check this: https://learn.microsoft.com/en-us/powershell/scripting/learn/remoting/wsman-remoting-in-powershell?view=powershell-7.4#wsman-remoting-isnt-supported-on-non-windows-platforms

```
above doc says Note
Users may be able to get WSMan remoting to work using the [PSWSMan](https://www.powershellgallery.com/packages/PSWSMan) module. This module isn't supported or maintained by Microsoft.
```
