### ISSUE TITLE
missing 1.8.1 release

### ISSUE THREAD

**Issue by Klaas-** [microsoft/omi#759]
Hi,
it seems you forgot to release a new version here again (last time I noticed this was in #719) -- oms agent tells us it's a security release but doesn't mention much more.

omi-1.8.1-0.ulinux.s.x64.rpm
https://github.com/microsoft/OMS-Agent-for-Linux/pull/1559

Highlighting the people who did the last release @Yash-Khatri @S-Sujith-Kumar @deepakjain111 @dishantcr7

**Comment by Klaas-** [comment]
and it also doesn't seem to be on packages.microsoft.com yet

**Comment by Yash-Khatri** [comment]
https://github.com/microsoft/omi/releases/tag/v1.8.1-0
