### ISSUE TITLE
Unrecognized version of SSL

### ISSUE THREAD

**Issue by jgcanete** [microsoft/omi#764]
OS: Fedora 40
Package: omi-1.9.0-0.x86_64

Error: Preinstall script error: Unrecognized version of SSL on the system: 3.2.1

error: %prein(omi-1.9.0-0.x86_64) scriptlet failed, exit status 2

OMI it's only for OpenSSL < 3.0.0 ??

**Comment by JumpingYang001** [comment]
OMI doesn't support Fedora.
https://github.com/microsoft/omi?tab=readme-ov-file#supported-linux-operating-systems

**Comment by JumpingYang001** [comment]
@jgcanete yes, currently, only support openssl 3.0.x.

**Comment by JumpingYang001** [comment]
@jgcanete update: it will be in next release.

**Comment by johnlivi2019** [comment]
@JumpingYang001 How soon can we expect the release?

**Comment by JumpingYang001** [comment]
I don't know when next release come, will update here if I know, thanks.

**Comment by Mario-NTT** [comment]
> I don't know when next release come, will update here if I know, thanks.

Would you have any update on this yet?

**Comment by JumpingYang001** [comment]
@Mario-NTT as I known, the next omi will be released in another 2 weeks

**Comment by JumpingYang001** [comment]
new release:
https://github.com/microsoft/omi/releases/tag/v1.9.1-0
https://github.com/microsoft/SCXcore/releases/tag/v1.9.1-0
