### ISSUE TITLE
OMI fails with invalid character

### ISSUE THREAD

**Issue by vaibhavgulhane** [microsoft/omi#767]
I am running command on Linux to get Win32_ComputerSystemProduct from Windows. 
Expected Output:
![image](https://github.com/microsoft/omi/assets/53223274/b9fea93b-1001-4134-b5f4-aeb3fbd6e56e)

If I store the output in a variable or any file, then some characters of xml data is changed. These characters are changed randomly. 
![image](https://github.com/microsoft/omi/assets/53223274/63ec6380-dc5d-47b8-8ef7-f0a5853a77ed)

This issue is reproducing on 
- Ubuntu 22.04
- Ubuntu 24.04
- Debian 11 (bullseye)
- Debian 12 (bookworm)
- Rocky Linux 8.9
- Rocky Linux 9.3

Same command works on CentOS 7. 

locale is set to en_US.UTF-8 on all OS. 

Please help me in resolving this issue.

**Comment by JumpingYang001** [comment]
@vaibhavgulhane you use this in SCOM or Azure product? I don't see this scenario for supported products.
can you try `omicl ** > /tmp/yourresult.txt` and then read the content from /tmp/yourresult.txt? from you description it seems be related to encoding of bash command.

**Comment by vaibhavgulhane** [comment]
@JumpingYang001 I am using this on Hyper-V. Redirecting to a file shows same behavior. Hexdump shows that characters are different every time.
Below screenshots shows that string 32_Compu in Win32_ComputerSystem is changed with random characters. Changed characters are different in first and second screenshot:
![image](https://github.com/user-attachments/assets/b2b3bc1c-d6b9-478e-8404-175e73cc7524)

![image](https://github.com/user-attachments/assets/79d935a8-b67d-4978-9240-c90581e3b703)

Using `stdbuf -o0 cmd > file` resolves the issue.

**Comment by JumpingYang001** [comment]
glad to know you have work around, in fact, we don't have supported products that use that Linux omicli to query Windows now. :)
