### ISSUE TITLE
Couldn't install omi-1.9.1 with openssl 3.1.4 on SLES15 SP6

### ISSUE THREAD

**Issue by deamn** [microsoft/omi#769]
Couldn't install omi-1.9.1 with openssl 3.1.4 on SLES15 SP6:
```
Retrieving: omi-1.9.1-0.x86_64 (packages-microsoft)                                                 (1/1),   1.9 MiB
Retrieving: omi-1.9.1-0.x86_64.rpm ...............................................................................[done]

Checking for file conflicts: .....................................................................................[done]
Expecting SSL version (compatible with): 1.1.0
SSL version found on system:             3.1.4
Incorrect version of OMI for your system, please check SSL version.
error: %prein(omi-1.9.1-0.x86_64) scriptlet failed, exit status 3
error: omi-1.9.1-0.x86_64: install failed
```

and openssl version:
`OpenSSL 3.1.4 24 Oct 2023 (Library: OpenSSL 3.1.4 24 Oct 2023)`

**Comment by roelandjansen** [comment]
the issue here is that you try to install the version for ssl v1.

you can update the stuff:

sudo rpm --import https://packages.microsoft.com/keys/microsoft.asc
and install https://github.com/microsoft/omi/releases/download/v1.9.1-0/omi-1.9.1-0.ssl_300.ulinux.s.x64.rpm


instead.

**Comment by deamn** [comment]
Yes I know but I use the official repository for zypper and it contains only one version of the omi package (openssl v1): https://packages.microsoft.com/sles/15/prod/
It should be updated with all possibles versions isn't it?

**Comment by JumpingYang001** [comment]
> Yes I know but I use the official repository for zypper and it contains only one version of the omi package (openssl v1): https://packages.microsoft.com/sles/15/prod/ It should be updated with all possibles versions isn't it?

that's a limitation, we cannot upload both openssl 1.1 and openssl 3.x version pacakge in the repo.
https://packages.microsoft.com/sles/15/prod/Packages/o/

**Comment by ShirelyGu** [comment]
We support the openssl 3.* version package, for now you can try to install manually omi-1.9.1-0 packages from https://github.com/microsoft/omi/releases/download/v1.9.1-0/omi-1.9.1-0.ssl_300.ulinux.s.x64.rpm

**Comment by roelandjansen** [comment]
we know that but if we want to keep the versions tight, we should have a
new repo / url that has the latest 3.x package so that if a repo refresh
takes place, we have the latest version

**Comment by ShirelyGu** [comment]
With MS Repo Team's help, the new repo has been created, you can install the corresponding OpenSSL 3. * Packages from https://packages.microsoft.com/sles/15/sles15-sp6/ .
