### ISSUE TITLE
Any plans to support Ubuntu 24.04?

### ISSUE THREAD

**Issue by nitinkathpalia09** [microsoft/omi#771]
Do you have any plans to support Ubuntu 24.04? If so, when can we expect it?

**Comment by ShirelyGu** [comment]
Hi, @nitinkathpalia09 
We have supported Ubuntu 24.04 from omi1.9.0-0, for more details, you can refer to the readme file.

**Comment by ShirelyGu** [comment]
Hi, @nitinkathpalia09 
We have supported Ubuntu 24.04 from omi1.9.0-0.
https://github.com/microsoft/omi#:~:text=Ubuntu%2024.04%20LTS%20x64%20(omi%3E%3D1.9.0%2D0)

**Comment by nitinkathpalia09** [comment]
Hi @ShirelyGu , 

Thanks for the confirmation. I got it.
