### ISSUE TITLE
Test Pal multibyte character  test cases deactivated on aix solaris and hpux due to compiler issue

### ISSUE THREAD

**Issue by yakman2020** [Microsoft/omi#82]
The compilers for hpux, AIX and solaris do not support mixed width literal concatenation.  The macros defined in tests/pal/test_pal_strings.h depend on that feature.  It was necessary to deactivate the test cases that uses those macros on those platforms, for wchar.

This shows up in regress

**Comment by palladia** [comment]
wide chars are not supported, and code related to it are being removed.
