### ISSUE TITLE
Some test cases seem quite slow at 24 seconds

### ISSUE THREAD

**Issue by yakman2020** [Microsoft/omi#85]
A number of regress test cases seem to be timing out after a 24 second wait.

A partial list would be :
 libtest_protocol.so:TestTransferingEnumerateInstanceRequest   24.0015
          libtest_protocol.so:TestTransferingResult     24.0016
          libtest_protocol.so:TestTransferingGetInstanceReqt    24.0026
          libtest_protocol.so:TestTransferingPostInstance       24.0021
          libtest_protocol.so:TestTransferingInvoke     24.0017

**Comment by palladia** [comment]
Duplicate of #209
