### ISSUE TITLE
Need a clear list of dependencies

### ISSUE THREAD

**Issue by energizedtech** [Microsoft/omi#91]
Downloaded a clean Ubuntu 16 server.
Dependencies for compiling should be listed including libraries (they are not)
C++
cmake (to start - seems obvious but it isn't)

**Comment by paulcallen** [comment]
Hi @energizedtech, the OMI README.md has a [building and developing omi](https://github.com/Microsoft/omi/blob/master/README.md#building-and-developing-omi) section now, and that points you at the [build-omi readme](https://github.com/Microsoft/Build-omi#dependencies-to-build-a-native-package) which includes dependencies. Generally building OMI is built from a parent project that manages the versioning information.
If this information is not sufficient feel free to re-open the issue.
